### ISSUE TITLE
Blog Summaries & Code Scrollboxes

### ISSUE THREAD

**Issue by ArchangelUO** [datenstrom/yellow#101]
Hey everyone!

First off.. thank you for such an amazing piece of software. It is both elegant and beautiful! 

Now to suggestions:
I just installed Yellow and would really like to be able to do a couple of things.. 

1. Shorten the blog post summaries to specific number of characters
2. Make the code blocks fit in a scroll box so long piece of code don't take up the whole page

I hope you guys can help me! 

Thanks again!

**Comment by BsNoSi** [comment]
1. Try `[--more--]` as separator. This ist quite better than counting characters, because this may cut words off. 
2. I am not shure, if I understand exactly what you mean. But I believe, hhis is a challenge for your CSS stylesheet. Something like

` .content pre>code { display: block;  overflow: auto; font-family: …  }`

should help.

**Comment by ArchangelUO** [comment]
Thank you for the help!

The more separator is 100% better than what I was thinking and forgot it existed!

CSS is the correct route I think, but I think I have other issues with the default theme -- it seems like code blocks aren't even being styled.

**Comment by markseu** [comment]
Good that you found it, I updated [themes](https://github.com/datenstrom/yellow-extensions/tree/master/themes) and it should be working now. Here are some CSS examples:

```
.content pre { overflow:auto; }

.content pre { overflow:auto; height:15em; }

.content pre { overflow:auto; height:15em; padding:1em; background-color:#f7f7f7; border-radius:3px; }
```

First line shows horizontal scrollbar if a code block is too wide. Second line adds a vertical scrollbar if a code block is too long. Third line adds a grey background to the code block. Hope this helps.

**Comment by ArchangelUO** [comment]
Perfect! Thanks everyone!
