### ISSUE TITLE
new sidebar handling

### ISSUE THREAD

**Issue by meentix** [datenstrom/yellow#102]
Hello,

I think the actual handling of sidebars in yellow is not practicable, because you have to copy the content file of the sidebar into each directory you want to use it. That means you have no central sidebar file which is very impracticable if you want to edit it and so on. Therefore I suggest to solve this problem with a sidebar snippet.

That means you should be able to have multiple sidebars as much as you want, maybe as sidebar-long.php, sidebar-short.php, sidebar-categories.php and so on (prefix sidebar-XX.php) in one central place for example the snippet directory. Then you should be able to set the sidebar for each page individually in the meta data, for example in this way:

Title: test page
Sidebar: long

That means this page should use the sidebar-long.php from the snippet directory. In a second step you could also implentate the possibilty to add multiple sidebars (SidebarRight: long; SidebarLeft: short) if set in template.

Thanks and Regards,
Christian

**Comment by BsNoSi** [comment]
I love the simple assignment of sidebars to pages directly in the directory. A central directory with a lot of sidebars   imo does not improve handling. Usually I have a typical sidebar in one directory, but not usually one sidebar in several directories (=home page areas).

I did not test that, but: Did you try to point to a sidebar outside of the current directory? Maybe you can already do that by simply adding a directory path.

**Comment by markseu** [comment]
If you want a central sidebar, you can adjust your header snippet. For example replace:

`<?php if($page = $yellow->pages->find($yellow->lookup->getDirectoryLocation($yellow->page->location).$yellow->page->get("sidebar"))) $yellow->page->setPage("sidebar", $page) ?>`

with this one:

`<?php if($page = $yellow->pages->find('/'.$yellow->page->get("sidebar"))) $yellow->page->setPage("sidebar", $page) ?>`

For web developer there are many possibilities in the [Yellow API](https://github.com/datenstrom/yellow/wiki/Yellow-API) to make the website you want. 

Hope this helps. :smile:

**Comment by meentix** [comment]
Thanks Mark, it works :-)
