### ISSUE TITLE
Replace default text editor with a better one

### ISSUE THREAD

**Issue by nashv** [datenstrom/yellow#103]
The default text editor is sufficient but hardly the best. How difficult/easy would it be to intrgrate something like EpicEditor (http://epiceditor.com) into Yellow ?

**Comment by markseu** [comment]
Good idea to add another text editor. Can you describe what features you are missing most? Maybe someone has suggestions or wants to write a plugin? Any help would be much appreciated. :smile:

**Comment by nashv** [comment]
I missing the ability to save drafts without publishing using the Drafts plugin.  And simple formatting buttons/post preview.
I could write a plugin, but was looking for pointers on exactly how one would start. I am not too familiar with the Yellow source code.

**Comment by nibreh** [comment]
Hi. 

I think this editor will be great for Yellow: https://github.com/lepture/editor

[Demo](http://lab.lepture.com/editor/)

We already talk about WYSIWYG in issue https://github.com/datenstrom/yellow/issues/24

**Comment by markseu** [comment]
Yes would be great if someone wants to work on it, Yellow is open source and help is very welcome. 

 Here are some starting points for the source code: The [header snippet](https://github.com/datenstrom/yellow/blob/master/system/themes/snippets/header.php) where you can add any HTML/JavaScript, a good place for quick modifications and experiments. The [gallery plugin](https://github.com/datenstrom/yellow-extensions/tree/master/plugins/gallery) which gives you an example how to integrate HTML/JavaScript via event handler, shows how to load and initialise a library. Finally there's the [core-webinterface.js](https://github.com/datenstrom/yellow/blob/master/system/core/core-webinterface.js) which is the current editor, written in Vanilla JavaScript.

**Comment by i-do** [comment]
Yes, I think it's good idea. I'd like to see [ZenPen](https://github.com/tholman/zenpen) as editor.

**Comment by nibreh** [comment]
HI - I use jquery Markbar by reinink - https://github.com/reinink/jQuery.Markbar

I made a repository on how to install in Yellow:
https://github.com/nibreh/yellowcms-markbar

![](https://cloud.githubusercontent.com/assets/7314006/9836901/5bedad82-5a2c-11e5-8619-35bc6428eb28.png)

It's very usefull

**Comment by i-do** [comment]
Wow! Look on [this markdown editor](http://tibastral.github.io/markdownify/). It very simple, have preview and can upload files.

**Comment by nibreh** [comment]
Hey mardownify is really cool. But I don't know how to use it in Yellow, like many others editor.

Markbar is the only one that works with panel edit from yellow.

**Comment by markseu** [comment]
If someone would like to see this feature, please add +1 to this issue.

**Comment by BsNoSi** [comment]
Markdonify looks really nice. I love the "preview" option and the smart presentation of markdown. But I miss a way for uploading images or files in general. The formatting bar is something I do not need, because for me this as an antagonism to markdown ;)

**Comment by i-do** [comment]
+1

**Comment by redtide** [comment]
What about [SimpleMDE](https://simplemde.com/)? (MIT License, hosted here on GitHub)

**Comment by redtide** [comment]
It could be nice if the webinterface plugin could be splitted (e.g. in 2 'user-admin' and 'simple-editor' plugins), so it could be easier to replace the editor with a custom one (e.g. I would like to use simplemde on a new custom plugin) without removing the current one.

**Comment by markseu** [comment]
Do you want to play around with different options, see if you can make your favorite editor (and a few more) work with Yellow? Doesn't have to be perfect, just working. Once we know more about 3rd party editors, how to load and configure, we can integrate them properly into the webinterface plugin.

**Comment by redtide** [comment]
Actually IDK how webinterface works and so neither how create my own editor plugin (which JS action/events are exposed, API etc).
Since Yellow works with plugins I thought it could be a nice idea to have anything (un)pluggable, so the editor away from admin management, that way I could also use only the editor plugin as reference.

**Comment by redtide** [comment]
Ok, I did a preliminary plugin [here](https://github.com/redtide/yellow-simplemde-plugin). Feedbacks are welcome as usual.

**Comment by redtide** [comment]
Looking at my firefox web tools It seems that, at least for simplemde, a yellow support side is needed to make it work correctly.
The only mdeditor I tried that seems to work better with Yellow is [bootstrap-markdown](http://www.codingdrama.com/bootstrap-markdown/) but, as the name say, it requires bootstrap (and so also jquery) to work.

**Comment by markseu** [comment]
I am working on this now.

You can see what's already working in the [demo](https://developers.datenstrom.se/). There's a new editor with formatting toolbar. It's based on your feedback and I tried to integrate what features editors have in common. The formatting toolbar was difficult to do, it went trough many design reviews and cups of coffee, until it was no longer terrible to use. The preview feature was surprisingly little work, just a XMLHttpRequest and the server will run it trough the Markdown parser. I will upload the source code after some more testing. 

Let me know if you have questions or feedback.

**Comment by schulle4u** [comment]
Great work Mark! From a blind user's perspective I can say that this is one of the best online editing solutions I've seen so far. I never was a fan of WYSIWYG editors or formating toolbars as they often cause trouble for screenreaders, but your solution keeps the old editor working as usual, without breaking anything. It would be great to have some keyboard shortcuts for even easier text formating. 

As for the "Preview" button, I suggest to label it as "Toggle preview" for clarification and to avoid confusion after someone hits preview and is wondering how to return to the text input. 

Steffen

**Comment by schulle4u** [comment]
@markseu That was quick, thanks for adding keyboard shortcuts. The default shortcuts however are not usable in most browsers (ctrl+b opens bookmarks etc). I suggest to add an additional modifier key to the default values. Ctrl+alt should work in most cases, just tested this in two browsers without problems.

**Comment by markseu** [comment]
Doesn't GitHub use the same keyboard shortcuts, e.g. for ctrl+b (or cmd+b) for bold?

**Comment by schulle4u** [comment]
Hmm indeed. Thats interesting, Github's markdown shortcuts don't collide with the browser shortcuts, but I have no clue why this could happen in YellowEdit. Probably a nasty JS issue.

**Comment by markseu** [comment]
I can't reproduce a problem, it appears to be working fine on Safari, Chrome and Firefox (macOS). Perhaps you can configure different keyboard shortcuts in your `system/config/config.ini`?
