### ISSUE TITLE
Folder specific feed

### ISSUE THREAD

**Issue by daviga** [datenstrom/yellow#104]
It would be good for multi language sites where languages live in their respective folders to have a feed/language (i.e. folder). In this way users won't receive feeds in languages they don't speak.

Just a suggestion.

**Comment by markseu** [comment]
Hi David,

I gave you the wrong advice per email. The [multi language mode](https://github.com/datenstrom/yellow/wiki/Language-configuration#multi-language-mode) works exactly like you suggested and you don't need to change anything. You get a feed per language and not for the whole site. I am not using the multi language mode myself and forgot about that.

You can make a feed for the whole site by replacing `$pages = $this->yellow->pages->index(false, false);` with `$pages = $this->yellow->pages->index(false, true);`. Please note that there are two occurrences in the original feed plugin.

**Comment by daviga** [comment]
Well, that's good news. 

Thank you. I should have checked this my self.
