### ISSUE TITLE
Not an issue, but a sublime text plugin for Yellow

### ISSUE THREAD

**Issue by nashv** [datenstrom/yellow#105]
This plugin generates the template file that Yellow  requires for a new blog. 
https://github.com/nashv/YellowBlogExtensions

Combined with FTPSync (another Sublime text plugin), this gives all the goodness of Sublime Text while composing blog posts and direct upload to server.

Ideas for more functions to be added are welcome.

**Comment by markseu** [comment]
Thank you :+1:

**Comment by BsNoSi** [comment]
I am using [SynWrite](http://www.uvviewsoft.com/synwrite/) and its FTP client. I created some markdown templates (e.g. title header). It is close to Sublime but for free.

**Comment by nashv** [comment]
Great! I checked out SynWrite and it seems very capable. I prefer 
Sublime Text due to its interface.

BsNoSi wrote:

**Comment by nashv** [comment]
Yellow Blog Extensions is now added to the Sublime Text Package repository.

**Comment by markseu** [comment]
Also added to [Yellow extensions](https://github.com/datenstrom/yellow-extensions/tree/master/plugins/zzz-more) repository.
