### ISSUE TITLE
css based Gallery

### ISSUE THREAD

**Issue by dieli** [datenstrom/yellow#106]
Hi everyone,

Not a real issue, but I made a css based gallery plugin, based on fotorama plugin. The main reason is that I don't like js :-) You can check it out at http://www.dielacher.org/yellow/ . It currently has 2 problems (which I will look into tomorrow or so):
* ~~Multiple galleries on one side do not work~~
* The lightbox next/prev buttons do not change the normal gallery

If someone is interested, I have uploaded it to https://github.com/dieli/yellow-extension-ycssg ~~https://github.com/dieli/yellow-extensions/tree/ycssg/plugins/ycssg~~

Cheers,
Andi

P.S.: Same goes for the theme ... it uses purecss.io as baseline, adapted php for all content and https://github.com/heiseonline/shariff for social media buttons.

**Comment by markseu** [comment]
Nice work! :+1: 

Do you want to add it to the plugins list? Let's put new plugins into individual repositories. I think this takes some stress away and allows to experiment with plugins apart from the stable ones. https://github.com/datenstrom/yellow-extensions/tree/master/plugins/zzz-more

**Comment by dieli** [comment]
Thanks, I will put it into a seperate repo (hopefully I find time this week).

**Comment by dieli** [comment]
I have put it into a seperate repo: [ycssg](https://github.com/dieli/ycssg). Feel free to add it.

**Comment by markseu** [comment]
What do you think about renaming it yellow-ycssg or yellow-extension-ycssg? Makes it [easier to find](http://phptrends.com/dig_in/yellow).

**Comment by dieli** [comment]
There you go https://github.com/dieli/yellow-extension-ycssg

**Comment by markseu** [comment]
Done. Let me know if you want me to test something, happy coding.
