### ISSUE TITLE
Markdown formatting with CSS classes

### ISSUE THREAD

**Issue by BsNoSi** [datenstrom/yellow#107]
Hi,

I am trying to go into deep with Yellow and created my first own plugin for adding style class into generated code. My PHP knowledge is „beginner status“, so I currently have no idea, how to solve it "nice".

I want to add formating into my parsed markdown. Therefore I created a plugin (to be true: modified an existing one) with this main function:

``` .php

function onParseContentBlock($page, $name, $text, $shortcut)
    {
        $output = NULL;
        if($name=="format" && $shortcut)
        {
            list($class, $style) = $this->yellow->toolbox->getTextArgs($text);
      if($class == "end" || $class == "/")
       {
       $output = "<div></div></div>";  
//     $output = "</div>";  // creates wrong html code, "<p></div></p>"
     }
      else
      {
        $output = "<div class=\"".htmlspecialchars($class)."\"";
              if($style) $output .= " style=\"".htmlspecialchars($style)."\"";
              $output .= ">";
      }
        }
        return $output;
    }

```

Starting the div with `[format classname]` creates a line as expected:

``` .html

<div class="classname">

```

To achieve valid html, the closing parameter with `[format end]` or `[format /]` requires as $output

``` .html

<div></div></div>

```

because a simple `</div>` is parsed into `<p></div></p>` in the final output.

For security reasons, I want to keep "parserSafeMode = 1" , so option `markdown="1"` in the output of opening tag does not heal this, if it is not set to "0".

In general, the code delievers, what I want. But I want to understand, what is happening there. Any hints to improve this welcome.

NoSi

**Comment by markseu** [comment]
I assume it's happening in the the Markdown parser. Can you upload a working project to reproduce it?

**Comment by BsNoSi** [comment]
I will prepare something and send a link to you.

**Comment by BsNoSi** [comment]
You can [download a zip-file](http://kd.nosi.de/format.zip) for testing. ZIP-File contains working php-file and readme, how to use.

**Comment by markseu** [comment]
I suggested support for CSS classes a while ago, see michelf/php-markdown#157. 

Not sure what's the best way to implement it with a plugin. It would be great if it could work without an ending marker `[format]`...`[format end]`. One alternative is `{.classname}`, which then assigns a class to the next upcoming element – whatever that might be.

**Comment by BsNoSi** [comment]
I designed this, to get more than one paragraph into one div for creating sporadically needed columns of different size. [format end] marks clearly the area, that is enclosed in a column.

**Comment by markseu** [comment]
I understand what you mean. I have a feeling I regret this advice in the future.... but here it is anyway. Have you considered using a codeblock to create divs, which is a block-level element and not limited to one paragraph. Here is an example:

    ```div {.classname}
    Markdown goes here
    ```

**Comment by markseu** [comment]
Okay, after some experimentation I'd like to suggest two alternatives for DIV with CSS classes. The first alternative is the format that you suggested, with a block ending marker. The second alternative is a so called definition list, which can have paragraphs. Here are examples:

```
[format columns]
First column with two paragraphs. Lorem ipsum dolor sit amet, 
consectetur adipisicing elit, sed do eiusmod tempor incididunt 
ut labore et dolore magna pizza.

Ubicumque homo est, ibi benefici locus est.
[/forma end]
[format columns]
Second column, just one paragraph.
[/forma end]
[format columns]
Third column has an image and a list.

[image icon.png]

1.  first list item
2.  second list item
[/format end]
```

Now the same with a definition list:

```
[div columns]
:   First column with two paragraphs. Lorem ipsum dolor sit amet, 
    consectetur adipisicing elit, sed do eiusmod tempor incididunt 
    ut labore et dolore magna pizza.

    Ubicumque homo est, ibi benefici locus est.

:   Second column, just one paragraph.

:   Third column has an image and a list.

    [image icon.png]

    1.  first list item
    2.  second list item
```

The first syntax is already possible with the Markdown plugin. You can get rid of the extra wrapper that you mention. Please see `function _doAutoLinks_shortcut_callback()` and handle `<div>` and `</div>` as block elements. 

The second syntax is possible but needs more work in the Markdown plugin. Special handling is usually done by overriding the Markdown callbacks and generate the HTML code that you need. There are callbacks like `doDefLists_callback` which can be used for the second syntax. 

We can work together if you like, I am happy to help if you put the source code on Github.

**Comment by markseu** [comment]
A third alternative could be a [wrapper](michelf/php-markdown#191), it creates an invisible DIV and parses content as usual:

~~~
::: columns
-   First column with two paragraphs. Lorem ipsum dolor sit amet, 
    consectetur adipisicing elit, sed do eiusmod tempor incididunt 
    ut labore et dolore magna pizza.

    Ubicumque homo est, ibi benefici locus est.

-   Second column, just one paragraph.

-   Third column has an image and a list.

    [image icon.png]

    1.  first list item
    2.  second list item
:::
~~~

The third syntax is possible with the Markdown plugin, but it would need a couple of changes in the Markdown library. What's interesting about this approach, it would be easy-to-read and very flexible, just one syntax and no need to invent more plugins.

**Comment by markseu** [comment]
Unfortunately the third alternative is not available in Markdown, there is still no handling for divs. As soon as features are added there they become available in Yellow as well.

**Comment by markseu** [comment]
I keep coming back to this problem and updated the [Markdown extension](https://github.com/datenstrom/yellow-extensions/tree/master/features/markdown).

Start each line with `!` and class name:

```
!custom Here's a notice with custom CSS class.
!custom **Text with Markdown** can be used optionally.
!custom [Link to website](https://datenstrom.se).
```

...this will generate the following HTML, nicely wrapped inside a `<div>`:

``` html
<div class="custom">
<p>Here's a notice with custom CSS class.
<strong>Text with Markdown</strong> can be used optionally.
<a href="https://datenstrom.se">Link to website</a>.</p>
</div>
```

For now it's an experimental feature. Let me know how this works for you.

**Comment by pbuzdin** [comment]
Neat!
Thank you!

**Comment by GiovanniSalmeri** [comment]
Just for the record: I checked the relevant discussions at Commonmark:

https://talk.commonmark.org/t/block-directives/802/69
https://talk.commonmark.org/t/generic-directives-plugins-syntax/444/158
https://talk.commonmark.org/t/consistent-attribute-syntax/272/86

... and they seem stalled without any consensus about a syntax. @markseu Your solution seems to me very good. Perhaps I would have a slight preference for the syntax `::: custom .... :::`, which would allow to apply a class to a block of text without modifying it by prefixing each line with a `!`, but definitively your solution works well and is easier to read (the block to which the class is applied is easier to recognise). Thank you!

**Comment by BsNoSi** [comment]
@GiovanniSalmeri : Thanks for the links – I haven't had the idea to check if there is an "offical discussion" about formating blocks. I share your opition `::: custom` block as shown [at the end of this demo](https://markdown-it.github.io/).

**Comment by markseu** [comment]
Thanks for your feedback. I don't have a strong opinion what the best syntax is, at the end of the day we need something. If there's consensus what the Markdown syntax should be, we simply update the Markdown extension. The following is supported in Datenstrom Yellow 0.8.5:

* simple notices, with predefined classes in the official themes
* custom notices, with custom class or ID
* complex notices, can be nested if necessary

Here are some examples, from simple to complex:

```
! Here's a notice with warning

!! Here's a notice with error

!!! Here's a notice with tip
```

```
! {.class}
! Here's a notice with custom class.
! Text can span over several lines
! and contain Markdown formatting.
```

```
! {.class1}
!! {.class2}
!! Here's a nested `<div>`
!
!! {.class2}
!! Here's a nested `<div>`
```

For you developers, there's an [experimental extension based on Parsedown Extra](https://github.com/datenstrom/yellow-extensions/tree/master/features/markdown). It's a good starting point, if you want to experiment with Markdown and work on a different syntax. Parsedown Extra is not as bug-free as Markdown Extra, but it's made to be extended.
