### ISSUE TITLE
Local hosting of cloudflare files?

### ISSUE THREAD

**Issue by BsNoSi** [datenstrom/yellow#109]
Is there a config option, to load the fotorama/photoswipe, etc. files (css, js) locally?

In recent days I had several times the problem is that the CloudFlare page was unreachable. As a result, my created pages with Yellow where not accessable.

Update:

I found the required config settings:

// fotoramaCdn = /system/cloudflare/
// jqueryCdn = /system/cloudflare/
// galleryPhotoswipeCdn = /system/cloudflare/

The path is updated, but it does not work. The path is set as expected, but fotorama, gallery, … do not work any more.

**Comment by markseu** [comment]
If you put your files into folder `/media/cloudflare/` 
then you can access them via location `/media/cloudflare/`.

...or if you want to put them into folder `/system/plugins/` 
then you can access them with location `/media/plugins/`. 

The direct access to the system folder is not possible. :wink: 

Where to put files? I think it all depends on what you want to do. For example if you want to customise a website, then the `media` folder is great. That’s what I usually do. If you want to write a plugin that others can use as well, then the `plugins` folder or a CDN is the better way to go. That’s what most plugins do.

Hope this helps.

**Comment by BsNoSi** [comment]
Sometimes it is that simple, … thanks.
