### ISSUE TITLE
Edit destroyes sometimes hyperlinks  or leads to a server error

### ISSUE THREAD

**Issue by BsNoSi** [datenstrom/yellow#110]
Without recognizable rule, edit saves quoation marks of hyperlinks as text:

       [the text](http://thelink.tld "Some description")

is saved as

     [the text](http://thelink.tld \"Some description\")

and the file is "messed up". 

Or I receive the message

### Server error

Something went wrong. Page has been modified by someone else!

and my changes are lost.

Any ideas?

**Comment by markseu** [comment]
It doesn't happen on the demo server with Yellow 0.6.1, PHP 5.5.9, Apache/2.4 Linux.

Which software version are you using?

**Comment by BsNoSi** [comment]
Newer version? Did I miss something? Ok. I have to check that, but I am off for holidays in a few minutes :)  for a week… .

**Comment by markseu** [comment]
Yes, a new release is coming. 

Can you also check if you are using PHP 5.3? I suspect your problem is related to [magic quotes](https://en.wikipedia.org/wiki/Magic_quotes).

**Comment by BsNoSi** [comment]
Sorry for delay. Yes. You are right, I am (to be correct: was…) using PHP 5.3. After switching to 5.6 I can no more reproduce the described effect. Thanks for hint.

**Comment by markseu** [comment]
Let's keep the bug and investigate some more, I think it's simple to fix.

If someone has an old PHP 5.3 server available for testing let me know.

**Comment by markseu** [comment]
Should be working now.
