### ISSUE TITLE
Rename of numbered files

### ISSUE THREAD

**Issue by BsNoSi** [datenstrom/yellow#112]
Maybe it is solved with V0.6.x:

Editing a file `1-the-name.txt` with title `this is the title`, it is saved as `this-is-the-title.txt`.

(This is just a note, that I don´t forget it, I am in a hurry. If it does not happen any more, close this, please).

**Comment by markseu** [comment]
Hi Norbert, I am not sure what you like to do. Can you elaborate?

**Comment by BsNoSi** [comment]
I tested again with v0.6.1 AND PHP 5.6. I could not reproduce this effect again.

Details for error:

I have "numbered" files named

1-filez.txt
2-filex.txt
3-filey.txt

to get desired order in navigation. This worked (and works) fine.

Editing "1-filez.txt" worked, too, but it was saved as new file with it´s title as filename. This does not happen any more.

**Comment by markseu** [comment]
Editing pages in the [webinterface](https://github.com/datenstrom/yellow-extensions/tree/master/plugins/webinterface) may change the filename. The filename changes if you change the title, then the filename will be changed correspondingly. The filename doesn't change if you are editing the content of a page.

**Comment by markseu** [comment]
Perhaps the webinterface can be improved in the future. I don't want to add extra code, as long as I am not sure what the prefered solution is for people using it. Maybe someone wants to add special handling. Would be nice. :smile:
