### ISSUE TITLE
Video embed doesn't work

### ISSUE THREAD

**Issue by treipatru** [datenstrom/yellow#113]
I'm trying to embed a youtube video in some test pages and after following the instructions on how to do that I fail to make it work. I've also tried the Vimeo plugin and that doesn't work for me either.

What I've done so far is installed the youtube plugin as instructed in */plugins* and made sure that all files have correct permissions (not sure if it could be an issue, but I've checked anyway). I've also checked that the video is *embed-able* and tried all options (height, width).

My input in page.txt in */content* is:
```
[youtube FdMzngWchDk]
```
The browser displays the following code for the *page* section:

```
<div class="page">
<a href="/"><div class="sitename"></div></a>
<div class="sitename-banner"></div><div class="content">
[youtube FdMzngWchDk]
</div>
</div>
```

Any ideas? I don't really know PHP but have experience with HTML/CSS.

Thanks

**Comment by markseu** [comment]
Can you check in which folder the plugin is? Make sure it's in your `system/plugins` folder, [looks like this](https://github.com/datenstrom/yellow/tree/master/system/plugins). 

This should fix it.

**Comment by treipatru** [comment]
Yes, that is where it is - /var/www/website/system/plugins/youtube.php

Sorry I didn't mention it the first time.

I'm using one of the default themes and made some minor modifications to snippets (pagination.php and footer.php) and the theme itself (just the CSS). Not sure if this has anything to do with it.

**Comment by treipatru** [comment]
Solved! I was using some older core files that just didn't work well with the youtube plugin. Everything works fine now that I've updated the installation.

Thanks!

**Comment by treipatru** [comment]
Solved! I was using some older core files that just didn't work well with the youtube plugin. Everything works fine now that I've updated the installation.

Thanks!
