### ISSUE TITLE
Enhancements to the feed plugin

### ISSUE THREAD

**Issue by schulle4u** [datenstrom/yellow#124]
Hello, 

I'd like to request a few enhancements to the feed plugin, assuming they are not possible with the current configuration and I've not missed anything. :)

* add a date and time-based sorting in the xml and html output. This would allow more than one entry per day and have them sorted in the correct order. Currently, pages are sorted only by date, not by date and time, even if pages have time settings in their header. 
* add time and date information to the xml output. There seems to be a kind of timestamp in the guid field, however my feed reader only displays the date of subscription for each entry, not the actual publication date. 
* add an optional category filter to the feed plugin, for example to subscribe only to blog pages and ignore all other categories. 

Steffen

**Comment by schulle4u** [comment]
OK issue #94 solves the last problem on my list. However, modifying the feed.php directly is a bit uncomfortable when this plugin is being updated, so I add a configuration parameter for filtering categories to my request.

**Comment by markseu** [comment]
Sounds like a good idea. Let's add it to the [feed plugin](https://github.com/datenstrom/yellow-extensions/tree/master/plugins/feed), any hep is much appreciated. :smile: 

About the date and time, I was not able to reproduce a sorting problem in the Yellow demo. I think what's happening is that the blog sorts by `Published` date and the feed by `Modified` date. I suggest to modify the feed so that it uses the correspoding sorting, if the blog filter was choosen.

**Comment by schulle4u** [comment]
OK I managed to implement a quick and probably dirty category filter which can be set in system/config/config.ini. Since I don't have any experience with git commits, here is the file as a gist: 

https://gist.github.com/schulle4u/1404bf7a3029abffcd44

To enable the filter, just add a line like "feedFilterTemplate: blog" to your config.ini. If this line is not present, all pages are being displayed in the feed as usual. 

Steffen

**Comment by markseu** [comment]
I plan to make an update this weekend. Are you available for testing?

**Comment by schulle4u** [comment]
Yes, I'm available and will keep an eye on the extensions repo. 

Steffen

**Comment by markseu** [comment]
Thank you, feed plugin is updated.
