### ISSUE TITLE
Language switcher example?

### ISSUE THREAD

**Issue by peterkelm** [datenstrom/yellow#127]
Referring to https://github.com/datenstrom/yellow/wiki/Language-configuration

At the bottom of the page the documentation refers to crafting a language switcher similar to using "custom navigation". However, the API documentation is really scarce how to accomplish that - e.g. "getLanguages()" is not documented. 

This is what I tried so far - php code only as the HTML is pretty obvious anyway
<pre><code>
    $languages = $yellow->pages->getLanguages()
    foreach($languages as $language):
        // check if this is the active language
        echo ($yellow->page->get("language") == $language) ? " class=\"active\"" : "" 

        // need the same page in another language --- HOW TO DO THIS?
        echo $yellow->page->getLocation() // THIS DOES NOT WORK

        // get language name from text string file
        echo $yellow->text->getTextHtml("languageDescription", $language)
    endforeach
</code></pre>

What is the intended way to implement a language switcher?

BTW: I wonder how Yellow determines which pages belong together as translations. (Other systems like Kirby keep track of this "relationship" by keeping all translations of a page in one folder.)

**Comment by markseu** [comment]
I added an example, you can now use `Navigation: navigation-multilanguage`. 

To answer your questions: In the [Yellow API](https://github.com/datenstrom/yellow/wiki/Yellow-API) the function `$yellow->pages->multi()` returns a page collection with multiple languages. If you enable the [multi language mode](https://github.com/datenstrom/yellow/wiki/Language-configuration#multi-language-mode), then Yellow knows what pages belong together by looking at the directory structure.

**Comment by peterkelm** [comment]
Mark,

Yes, it does - helps a lot in fact.

I was tinkering with multi() already as that seemed to be the right direction anyway. However, in my "experiments" that call always returned zero results. Looking at the differences between my code and yours, the difference became evident:

You used <pre>$yellow->page->location</pre> as the argument to the multi() call, I used <pre>$yellow->page->getLocation()</pre>. Just by looking at the API function name I expected both (location vs. getLocation()) do do the same. However, after reading through core.php and the docs again it turns out that I tried to use an "absolute location" instead of a relative one. That subtle difference did not catch my attention before.

Case resolved.

**Comment by markseu** [comment]
Yes, that's right. Perhaps an argument for `getLocation()` would work too and remove the confusion between the formats. Something to look at when doing an API redesign. Appreciate the feedback!

**Comment by peterkelm** [comment]
Mark, I'd prefer two separate API calls with clear names to one with an argument - even if there is a "sane" default. But that's just my 2ct.

**Comment by nogginfuel** [comment]
I haven't really played around with multiple languages yet, however, I am fine with either approach as long as it is documented and added to the wiki documentation in the appropriate place.

**Comment by wunderfeyd** [comment]
The argumented form would be perfect if a switch between absolute and relative location at one place in the code is needed. Is there any usecase for this? If not two separate function calls would be fine, with precise naming like `getAbsoluteLocation` and `getRelativeLocation`. When doing this one could consider to rename other functions begining with `getLocation` depending on what kind of location is processed there.

**Comment by markseu** [comment]
Yellow works with relative locations per default. There are some API functions that work with either relative or absolute location, like `$yellow->pages->find($location, $absoluteLocation = false)`. There are four API functions which stand out and return an absolute location, like `$yellow->page->getLocation()`. 

From my personal view I would use relative locations and use absolute locations only when needed: 

Classes working together: `$yellow->pages->find($location, $yellow->page->getLocation())`
Snippet for navigation: `<a href="<?php echo $page->getLocation(true) ?>">Text</a>`

**Comment by wunderfeyd** [comment]
What about the `find(..., $absoluteLocation...)`, `path(..., $absoluteLocation...)` and `multi(..., $absoluteLocation...)`, it won't be changed I think. In this case I would tend to the `getLocation($absoluteLocation)` variant because it would fit better together and one can pass through this argument if someone wraps the function call.

**Comment by peterkelm** [comment]
It might be easiest for now to just document the difference between `$yellow->page->location` and `$yellow->page->getLocation()` properly and re-evaluate changes to the find/path/multi API calls there is continuous demand for further clarification. I'm a big fan of working with relative locations, so I can relate very well to your comments, Mark.

As an alternative I would propose using `absLocation()`instead of `getLocation()` to make it clear that this is an absolute location/path. It would make sense to me to introduce `location()` as a documented way to access the relative location of a page.

@All, your thoughts?

**Comment by markseu** [comment]
I updated the [Yellow API](https://github.com/datenstrom/yellow/wiki/Yellow-API) with notes about locations.

**Comment by markseu** [comment]
I like to close this issue, since the original question has been resolved. Thanks a lot for your feedback about the location handling. Appreciate the feedback! If someone wants to improve the Yellow API, please let us know or send a patch/pull request.
