### ISSUE TITLE
"Navigation" and "Sidebar" properties should not be "config.ini"

### ISSUE THREAD

**Issue by peterkelm** [datenstrom/yellow#128]
I was in the process of porting one of our themes to yellow when I discovered that there are "Navigation" and "Sidebar" properties in "config.ini" that a theme "silently" depends on. This seems odd to me as it increases complexity (of adding or changing a theme). Instead, I feel a theme should be self contained as much as possible.

Furthermore, it seems like both properties are not quite used anywhere inside core.php or any (of the default) plugins. Only "snippets/header.php" in the theme directory uses them (once). Is there any other place where these would really be needed? If not I'd like to suggest that both properties are removed and "header.php" adapted accordingly. If these are used in another context that I haven't discovered yet: Maybe these could be auto generated (maybe as "read only" properties)?

What are your thoughts?

**Comment by markseu** [comment]
Yellow shouldn't tell you what to do, you should be able to make your own themes/templates exactly the way you like. I think the existing themes/templates are just an example of what can be done and to get you started quickly. How about ignoring navigation and sidebar in your own themes? 

I agree with what you say, that component should be independent. On the other side, it's good to have common feature that are both simple to use and adjust. Do you have any suggestion what should be improved?

**Comment by BsNoSi** [comment]
I love the options for navigation and sidebar inside config.ini. This file has to be modified anyway. The entries remind me, to set these basics to achieve a nice blog/website very fast. 

I have to agree, that "basic settings" may be unnecessary and can be possibly coded directly anywhere. But this makes it harder for new users. Config.ini contains "notes" to everything, that can/should be set for a valid site. In my eyes, this is KISS. Because all relevant settings are in one place.

Redundancy is not bad per se. I think it is nice to have a entry for sidebar and navigation, if I want to name it different (for whatever reason).

**Comment by peterkelm** [comment]
@markseu: Fully agree to all your statements. I'll try to put a patch together over the week that removes that dependency.

@BsNoSi: Thanks for your thoughts. Little changes to config.ini should be necessary when "just" changing a theme. The theme name and directories are okay to me. And all these parameters are "site global". Yet, "Navigation" and "Sidebar" are not:

Imagine a site that has a Sidebar on e.g. the blog page but none on the home page. What value shall "Sidebar" have? Same goes for "Navigation": none on a landing page but "full" navigation on all others. Again: what value would you assign to the parameter in "config.ini"?

@BsNoSi: Unfortunately I have to disagree on redundancy as my experience is that it is almost always bad. In fact, the only good reason for redundancy I can think of is mission critical "applications" (e.g. the control systems on a plane) where it protects against catastrophic failures.

**Comment by markseu** [comment]
A patch would make it easier to see how this improves Yellow. Have you found a solution?

**Comment by peterkelm** [comment]
Still working on it. Turned out that it is harder to implement than I thought but I am making progress. Will provide a patch/pull request in ASAP.

**Comment by markseu** [comment]
Let's close this issue for the moment, please feel free to reopen with more information. 

Thanks, Mark
