### ISSUE TITLE
HTTPS not detected automatically

### ISSUE THREAD

**Issue by markseu** [datenstrom/yellow#133]
The webinterface should detect if a website uses http or https. Apparently this doesn't work on a https-only website and the user had to configure `WebinterfaceServerScheme: https`. It could be a bug in the webinterface initialisation or function `getServerScheme()`.

**Comment by wunderfeyd** [comment]
Should be fixed with commit e93d1e40cfe2323261feb6e300a7d5cded4d8f3c.
