### ISSUE TITLE
Support for static contact plugin

### ISSUE THREAD

**Issue by CryssDOTnet** [datenstrom/yellow#135]
Are there any plans to implement support for a static contact plugin?

**Comment by markseu** [comment]
To be honest, I don't know how this would possible. Are there any services you're thinking of?

**Comment by CryssDOTnet** [comment]
I just don't want to use php online. I create the content offline and upload it. Maybe the easiest way would be to put some html forms in my index.html

**Comment by markseu** [comment]
I understand what you mean. That's the disadvantage of static websites, that they can't offer dynamic features like a contact page or online search. You would need some kind of web service, as far as I know. Here's what you can do: 

1. Install Yellow only for sending email. 
2. Use as service like [Formspree](http://formspree.io) or [Simple Form](https://getsimpleform.com)

Hope this helps. :smile:

**Comment by CryssDOTnet** [comment]
Yes. Thank you!
