### ISSUE TITLE
some little help in german

### ISSUE THREAD

**Issue by Zauberweib** [datenstrom/yellow#136]
I made some little Yellow-testing-page http://zaubsie.bplaced.net/ and by this I write about installing and using Yellow. It's all in german.

It's still in progress. Maybe someone would find it useful to have a look.

**Comment by markseu** [comment]
Great idea - Gute Idee! :+1:

**Comment by Zauberweib** [comment]
Thanks - anyone more Links? 
Nasendackels Kommentare sounds good, maybe I will try this. but not today... ;) 

Happy New Year everyone and "Guten Rutsch" ;)

**Comment by nasendackel** [comment]
Thanks. The Kommatare (Comments) Plugin is just a quick and dirty hack. I am not capable to write a proper yellow plugin, but maybe someone can. As a workflow, it works perfect for me!

**Comment by wunderfeyd** [comment]
@nasendackel: You could upload your current state of work to Github (maybe with an own repository in your account). Then we could refine it slowly to a proper plugin and we work together on the security, speed and feature set. What do you think?

**Comment by nasendackel** [comment]
@wunderfeyd Dir auch ein frohes neues Jahr!

Here we go:
https://github.com/nasendackel/YellowComments

**Comment by Zauberweib** [comment]
Cool - thanks, Nasendackel!

**Comment by markseu** [comment]
Cool, I am adding a link to issue #55.
