### ISSUE TITLE
How to redirect old locations in Apache?

### ISSUE THREAD

**Issue by markseu** [datenstrom/yellow#138]
If you install Yellow to replace an old website some of your old bookmarks might not work anymore. For example if your RSS feed was previously at `http://website/?feed=rss` and now is available at `http://website/feed/page:feed.xml`. The problem is that query strings, which are things ~~after~~ with a question mark, have to be converted into clean URLs.

**Comment by markseu** [comment]
Here's an example `.htaccess` configuration file for Apache, two lines added:

```apache
<IfModule mod_rewrite.c>
RewriteEngine on

RewriteCond %{QUERY_STRING} feed=rss
RewriteRule ^$ /feed/page:feed.xml [R=301,QSD,L]

DirectoryIndex index.html yellow.php
RewriteRule ^(cache|content|system)/ error [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^ yellow.php [L]
</IfModule>
```

**Comment by nasendackel** [comment]
Thanks for the hint, but when I add the two lines. I get this:

> Internal Server Error
> The server encountered an internal error or misconfiguration and was unable to complete your request.

**Comment by markseu** [comment]
It works fine on the demo server, which runs Apache/2.4 Linux.

**Comment by nasendackel** [comment]
It seems like that my server has an older version than apache 2.4 :( Therefore the flag QSD is not working.

**Comment by markseu** [comment]
Didn't know, I added a second example. Hope it helps. :smile:

**Comment by nasendackel** [comment]
That worked! Thanks!
