### ISSUE TITLE
question gallery shortcode how to change sort order

### ISSUE THREAD

**Issue by learningchannel** [datenstrom/yellow#141]
hi i'd like to know if there is a way to easily change sort order (ex: ascending or descending) within the [gallery] shortcut. please explain what would be the easiest way to be able to do this? great cms.  thanks in advance

**Comment by markseu** [comment]
Sorry, the [gallery plugin](https://github.com/datenstrom/yellow-extensions/tree/master/plugins/gallery) shows pictures as they are shown in the file manager. The easiest way to change the sort order is to rename your image files, for example with a numeric prefix.

**Comment by learningchannel** [comment]
thank you!

**Comment by markseu** [comment]
Just ask if there are more questions. :smile:
