### ISSUE TITLE
blog snippet echo any metadata

### ISSUE THREAD

**Issue by learningchannel** [datenstrom/yellow#146]
could you please guide me to echo metadata from blog?
i am a novice at best with php but i'm able to piece things together.
very stumped right now:
 
i'd like to know the syntax to get blog to echo 
- posts published by "year" only
- all tags from posts (i understand i can do [blogtags] but i want to learn the code). 
so i could put this into a snippet and into a template. 

thank you for your time

**Comment by learningchannel** [comment]
also i tried editing the blog.php
creating a new shortcode inside it 
		if($name=="blogarchiveyears" && $shortcut)

i also changed $months to $years.

i am stumpted here to get the published year. how can i change this to get Year

foreach($pages as $page) if(preg_match("/^(\d+\-\d+)\-/"

Thank you.

**Comment by learningchannel** [comment]
oops i did not mean to close this

**Comment by learningchannel** [comment]
if($name=="blogarchiveyears" && $shortcut)
		{
			list($location) = $this->yellow->toolbox->getTextArgs($text);
			if(empty($location)) $location = $this->yellow->config->get("blogLocation");
			$blog = $this->yellow->pages->find($location);
			$pages = $blog ? $blog->getChildren(!$blog->isVisible()) : $this->yellow->pages->clean();
			$pages->filter("template", "blog");
			$page->setLastModified($pages->getModified());
			$months = array();
			foreach($pages as $page) if(preg_match("/(\d+\-)/", $page->get("published"), $matches)) ++$years[$matches[1]];
			if(count($years))
			{
				uksort($years, strnatcasecmp);
				$years = array_reverse($years);
				$output = "<div class=\"".htmlspecialchars($name)."\">\n";
				$output .= "<ul>\n";
				foreach($years as $key=>$value)
				{
					$output .= "<li><a href=\"".$blog->getLocation().$this->yellow->toolbox->normaliseArgs("published:$key")."\">";
					$output .= htmlspecialchars($this->yellow->text->normaliseDate($key))."</a></li>\n";
				}
				$output .= "</ul>\n";
				$output .= "</div>\n";
			} else {
				$page->error(500, "blogarchiveyears '$location' does not exist!");
			}
		}


---

i did this and im close. 
but my list looks like
YEAR
2015- 2014- 2013-

how can i get rid of those dashes?

**Comment by wunderfeyd** [comment]
Have you tried to remove the `\-` from `preg_match()` already?

**Comment by learningchannel** [comment]
@wunderfeyd thanks for your response. 
- i have 4 postwhen i do ```/(\d+)\-/?``` i get single digit results: ``0  1  2``` of the year but its not displayed ```2016, 2015, 2008```
- the single digits link to ```blog.com/published:0``` and ```blog.com/published:1``` etc...
- when i remove ```\-``` and keep ```"/(\d+\-)/"``` i stlll get single digit results like ```0  1  2``` not ```2016, 2015, 2014```

it is a preg_match thing and maybe a datenormalise thing? 

so close!

**Comment by wunderfeyd** [comment]
How does your "published" tag looks like in the page.txt? Or more exact: How did you write down the date there?

I think `/(\d{4})\-/` should do it but didn't test.

**Comment by learningchannel** [comment]
my published tags for my blog posts
```
Title: birthday
Published: 2011-12-03
Tag: party, cake
```
when ```/(\d{4})\-/``` is in place, i get an output of 2011-, 2012-, 2013- as a list. all link like this: ```domain.com/published:2011-/``` ```domain.com/published:2012-/``` ```domain.com/published:2016-/```

thanks again @wunderfeyd

**Comment by learningchannel** [comment]
@wunderfeyd thank you again! 
i tried ```if(preg_match("/(\d{4})\-/"```

in ```blog.php```
```
		if($name=="blogarchiveyears" && $shortcut)
		{
			list($location) = $this->yellow->toolbox->getTextArgs($text);
			if(empty($location)) $location = $this->yellow->config->get("blogLocation");
			$blog = $this->yellow->pages->find($location);
			$pages = $blog ? $blog->getChildren(!$blog->isVisible()) : $this->yellow->pages->clean();
			$pages->filter("template", "blog");
			$page->setLastModified($pages->getModified());
			$months = array();
			foreach($pages as $page) if(preg_match("/(\d{4})\-/", $page->get("published"), $matches)) ++$years[$matches[1]];

			if(count($years))
			{
				uksort($years, strnatcasecmp);
				$years = array_reverse($years);
				$output = "<div class=\"".htmlspecialchars($name)."\">\n";
				$output .= "<ul>\n";
				foreach($years as $key=>$value)
				{
					$output .= "<li><a href=\"".$blog->getLocation().$this->yellow->toolbox->normaliseArgs("published:$key")."\">";
					$output .= htmlspecialchars($this->yellow->text->normaliseDate($key))."</a></li>\n";
				}
				$output .= "</ul>\n";
				$output .= "</div>\n";
			} else {
				$page->error(500, "blogarchiveyears '$location' does not exist!");
			}
		}
```

when i put ```[blogarchiveyear]``` in my page.txt , i still get single digit results in my list ```0, 1, 2``` which link to ```domain.com/published:0```, ```domain.com/published:1```, ```domain.com/published:2```

when i do 
```
	if($name=="blogarchiveyears" && $shortcut)
		{
			list($location) = $this->yellow->toolbox->getTextArgs($text);
			if(empty($location)) $location = $this->yellow->config->get("blogLocation");
			$blog = $this->yellow->pages->find($location);
			$pages = $blog ? $blog->getChildren(!$blog->isVisible()) : $this->yellow->pages->clean();
			$pages->filter("template", "blog");
			$page->setLastModified($pages->getModified());
			$months = array();
			foreach($pages as $page) if(preg_match("/(\d{4}\-)/", $page->get("published"), $matches)) ++$years[$matches[1]];
			if(count($years))
			{
				uksort($years, strnatcasecmp);
				$years = array_reverse($years);
				$output = "<div class=\"".htmlspecialchars($name)."\">\n";
				$output .= "<ul>\n";
				foreach($years as $key=>$value)
				{
					$output .= "<li><a href=\"".$blog->getLocation().$this->yellow->toolbox->normaliseArgs("published:$key")."\">";
					$output .= htmlspecialchars($this->yellow->text->normaliseDate($key))."</a></li>\n";
				}
				$output .= "</ul>\n";
				$output .= "</div>\n";
			} else {
				$page->error(500, "blogarchiveyears '$location' does not exist!");
			}
		}
```

i get list as  ```2016-```, ```2015-```, ```2011``` which link to ```domain.com/published:2016-/```

thank you so much

**Comment by wunderfeyd** [comment]
Okay, now I'm really interested. :) I'll setup a local test blog, otherwise we talk about different things maybe.

**Comment by learningchannel** [comment]
@wunderfeyd awesome. yea take a look, it is perplexing.
btw loving yellow cms so far.

**Comment by wunderfeyd** [comment]
@learningchannel: The array_reverse destroys our array of years. It needs an additional parameter:
~~~
$years = array_reverse($years, true);
~~~
Otherwise the key (which the year is) is not preserved. This is the case only if our keys are numeric and explains why it worked with the other tags before.

**Comment by learningchannel** [comment]
Incredible! it works!! Thank you @wunderfeyd 
Have an incredible weekend. Cheers.

Below is the code that works:
```
if($name=="blogarchiveyears" && $shortcut)
		{
			list($location) = $this->yellow->toolbox->getTextArgs($text);
			if(empty($location)) $location = $this->yellow->config->get("blogLocation");
			$blog = $this->yellow->pages->find($location);
			$pages = $blog ? $blog->getChildren(!$blog->isVisible()) : $this->yellow->pages->clean();
			$pages->filter("template", "blog");
			$page->setLastModified($pages->getModified());
			$months = array();
			foreach($pages as $page) if(preg_match("/(\d{4})\-/", $page->get("published"), $matches)) ++$years[$matches[1]];
			if(count($years))
			{
				uksort($years, strnatcasecmp);
				$years = array_reverse($years, true);
				$output = "<div class=\"".htmlspecialchars($name)."\">\n";
				$output .= "<ul>\n";
				foreach($years as $key=>$value)
				{
					$output .= "<li><a href=\"".$blog->getLocation().$this->yellow->toolbox->normaliseArgs("published:$key")."\">";
					$output .= htmlspecialchars($this->yellow->text->normaliseDate($key))."</a></li>\n";
				}
				$output .= "</ul>\n";
				$output .= "</div>\n";
			} else {
				$page->error(500, "blogarchiveyears '$location' does not exist!");
			}
		}
```

this is key
``` $years = array_reverse($years, true); ```
``` "/(\d{4})\-/" ``` or ``` "/(\d+)\-/" ``` i tried both they work!

**Comment by wunderfeyd** [comment]
Great to hear it works. Have a nice weekend too.
