### ISSUE TITLE
examples using meta tags for media files

### ISSUE THREAD

**Issue by learningchannel** [datenstrom/yellow#148]
```
The following settings are available for media files:

type = file extension
modified = file modification date, YYYY-MM-DD format
pageFile = file name of corresponding page
```

can anyone explain how this could be used? thanks

**Comment by markseu** [comment]
The first two, file extension and modified date, are taken straight from the file system. They can be useful when you have multiple media files and want to filter them. 

The last one takes the file name and calculates a similar filename of a content page. It can be used to connect media files with corresponding content pages, but so far it's rarely used.

**Comment by markseu** [comment]
Does this answer your question?
