### ISSUE TITLE
$page->isActive is broken in static builds.

### ISSUE THREAD

**Issue by richi** [datenstrom/yellow#151]
A static build breaks the active marker in navigation

    <?php echo $page->isActive() ? " class=\"active\"" : "" ?>

The call

    $this->yellow->page->setRequestInformation($serverScheme, $serverName, $serverBase, "", "");

in 

    /commandline.php:125
    
has an empty string as the location parameter.

this trickles down to 

    isActiveLocation(/blog/, ) [/core.php:410]

and causes the problem (IMO).

This is the stack dump

    #0  YellowLookup->isActiveLocation(/blog/, ) called at [/core.php:410]
    #1  YellowPage->parseData(This page is automatically generated., , 200) called at [/core.php:1226]
    #2  YellowPages->scanLocation(root/) called at [/core.php:1335]
    #3  YellowPages->getChildrenRecursive(root/, 1, -1) called at [/core.php:1342]
    #4  YellowPages->getChildrenRecursive(, 1, 0) called at [/core.php:1252]
    #5  YellowPages->index(1, 1) called at [/commandline.php:396]
    #6  YellowCommandline->getContentLocations() called at [/commandline.php:125]

**Comment by markseu** [comment]
Which version of Yellow and plugins are you using?

**Comment by richi** [comment]
Sorry...

    Yellow 0.6.1, PHP 5.5.30, Apache Darwin
    YellowBlog 0.6.1
    YellowCli 0.1.3
    YellowCommandline 0.6.4
    YellowCore 0.6.1
    YellowDynamicCss 0.1.1
    YellowFaq 0.1.1
    YellowImage 0.6.1
    YellowMarkdown 0.6.1
    YellowPageTxt 0.1.1
    YellowSearch 0.6.1
    YellowWebinterface 0.6.2
    YellowWiki 0.6.1

**Comment by markseu** [comment]
Thank you, I can confirm the bug and work on a solution.

**Comment by markseu** [comment]
Should be working now, the command line is no longer using old objects.

Can you please test the latest [commandline](https://github.com/datenstrom/yellow-extensions/tree/master/plugins/commandline), does it work for you?

**Comment by richi** [comment]
Great, it does work indeed. ¡muchas gracias!
