### ISSUE TITLE
How to link a static page in the blog navigation

### ISSUE THREAD

**Issue by AlexL777** [datenstrom/yellow#155]
Hello Developers,

I discovered your Yellow CMS and think it's good. I almost set my Yellow blog at http://wpzweinull.ch/cms/yellow.

Now I just need a static page for Imprint and privacy and I do not know how I create it in the websites navigation embed or link to.

Is there a viable solution, perhaps?

Thanks in advance.

**Comment by AlexL777** [comment]
Now I have already found out and I had in the FTP account a new directory in the directory /content create and this was then seen in the site navigation.

There I can edit the blank page and add my content. Very cool and not so heavy. I like :)

**Comment by markseu** [comment]
Glad to hear it was that simple. Just open more issues if you have questions. :smile:
