### ISSUE TITLE
Problems with Piwik plugin

### ISSUE THREAD

**Issue by danteoms** [datenstrom/yellow#156]
The installation of my piwik is in this address http://dantesaputalo.com/piwik. My problem is when I add this PiwikServerName: dantesaputalo.com/piwik in the config.ini seems does not work because it will changed to this url //dantesaputalo.com%2fpiwik. Is there any way how to fix this? Sorry I'm not really well verse in php coding.

My solution is to install the piwik in subdomain to avoid using slash "/" coz it will not work. Any ideas?
BTW here's my blog http://dantesaputalo.com powered by Yellow and  I love it

Thank you in advance. 

Greetings from Philippines

**Comment by markseu** [comment]
Sorry about this, thanks for your report. Look like the encoding of JavaScript strings is wrong. 
Want to tweet a link to your website, just mention Yellow. https://twitter.com/datenstromse

Greetings from Sweden

**Comment by markseu** [comment]
Should be working now. Please update your [plugins](https://github.com/datenstrom/yellow-extensions/tree/master/plugins).

**Comment by danteoms** [comment]
Thank you for your response. I've been testing the updated plugin but I got this error

<b>Fatal error</b>:  Call to undefined function strencode() in <b>/home/dantexxx/public_html/system/plugins/piwik.php</b> on line <b>29</b><br /

here's the script inside the updated plugin
<?php
// Copyright (c) 2013-2016 Datenstrom, http://datenstrom.se
// This file may be used and distributed under the terms of the public license.

// Piwik plugin
class YellowPiwik
{
	const Version = "0.6.2";
	var $yellow;			//access to API
	
	// Handle initialisation
	function onLoad($yellow)
	{
		$this->yellow = $yellow;
		$this->yellow->config->setDefault("piwikServerName", $this->yellow->config->get("serverName"));
		$this->yellow->config->setDefault("piwikSiteId", "Yellow");
	}
	
	// Handle page extra HTML data
	function onExtra($name)
	{
		$output = NULL;
		if($name == "footer")
		{
			$serverName = $this->yellow->config->get("piwikServerName");
			$siteId = $this->yellow->config->get("piwikSiteId");
			$output = "<script type=\"text/javascript\">\n";
			$output .= "var _paq = _paq || [];\n";
			$output .= "(function(){ var u=((\"https:\" == document.location.protocol) ? \"https\" : \"http\") + \"://".strencode($serverName)."/\";\n";
			$output .= "_paq.push(['setSiteId', '".strencode($siteId)."']);\n";
			$output .= "_paq.push(['setTrackerUrl', u+'piwik.php']);\n";
			$output .= "_paq.push(['trackPageView']);\n";
			$output .= "_paq.push(['enableLinkTracking']);\n";
			$output .= "var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0]; g.type='text/javascript'; g.defer=true; g.async=true; g.src=u+'piwik.js';\n";
			$output .= "s.parentNode.insertBefore(g,s); })();\n";
			$output .= "</script>\n";
		}
		return $output;
	}
}

$yellow->plugins->register("piwik", "YellowPiwik", YellowPiwik::Version);
?>

I been playing trial and error in the code and finally I got solutions to work. 

here's what I did: I just replace the following script:
<b>$output .= "(function(){ var u=((\"https:\" == document.location.protocol) ? \"https\" : \"http\") + \"://".strencode($serverName)."/\";\n";
			$output .= "_paq.push(['setSiteId', '".strencode($siteId)."']);\n";</b>

with this modified one:

<b>$output .= "(function(){ var u=((\"https:\" == document.location.protocol) ? \"https\" : \"http\") + \"://".htmlspecialchars($serverName)."/\";\n";
			$output .= "_paq.push(['setSiteId', '".htmlspecialchars($siteId)."']);\n";</b>

and it works for me :)

**Comment by markseu** [comment]
Please updated your [core plugin](https://github.com/datenstrom/yellow-extensions/tree/master/plugins/core) too. This should fix it.

**Comment by danteoms** [comment]
Updated the core plugin and it works now. Really appreciate your quick response. Thank you very much and more power @markseu

**Comment by markseu** [comment]
Let us know if there are more problems. Happy coding. :smile:
