### ISSUE TITLE
Fixing different :focus behaviour of Firefox

### ISSUE THREAD

**Issue by BsNoSi** [datenstrom/yellow#158]
**UPDATED!**

I tried a few weeks ( in spare time ) to find out, why Firefox does not zoom images via css as Chrome, IE and Opera does.

I created this style:

~~~

.content a:focus img{
width: auto;
 height : auto;
 max-height: 90%;
 max-width: 90%;
 padding:5px; 
 margin:2px; 
 border: 1px solid #07d;
 background-color:rgba(255, 255, 255, 1);
 position: fixed;
 top:5%;
 left:50%;
 -webkit-transform: translateY(-50%);
 -moz-transform: translateY(-50%);
 -ms-transform: translateY(-50%);
 -o-transform: translateY(-50%);
 transform: translateY(-50%);
 -webkit-transform: translateX(-50%);
 -ms-transform: translateX(-50%);
 -moz-transform: translateX(-50%);
 -o-transform: translateX(-50%);
 transform: translateX(-50%)
 transition: all 0s ease;
cursor:default;
}
~~~

It scales an image with focus big, defocus is done by clicking anywhere except the image.

Activating is simply done by standard markdown (this is my reason for research):

~~~

[![Image Title](link to image)](#)

~~~

But Firefox behaves not as expected, because `:focus` is handled different to other browsers.

After investigation, I found a solution with a small addition in `markdown.php` line 164:

~~~
if($width && $height) $output .= "tabindex=\"-1\" width=\"$width\" height=\"$height\"";
~~~

I added `tabindex=\"-1\"`. Only then Firefox takes the link as focused. 

> Or you add some text before or behind the image, which is not the solution, I was looking for. Because in Firefox you have to click the text, all other browsers accept an image click.

This works fine without javascript on all devices ( I know and tested).

I can not see any disturbance of the standard operation, so I would suggest to add tabindex into markdown.php as a standard, to fix the misbehaviour of Firefox for `:focus` on images.

---

I added this to my blog. If you want to see, how it works, you can [try this link](http://blog.nosi.de/stolpersteine). It is German, but clicking on images works in any ;)

**Comment by markseu** [comment]
Nice to get feedback from you, I like reading your blog. Unfortunately I have to say that this approach doesn't work on touch devices. To quote @dominikwilkowski: "Focus and hover is just convoluted on touch so just assume you ain't got none". Perhaps you can find an alternative that uses JavaScript?

**Comment by dominikwilkowski** [comment]
Hey @markseu, I would advise against adding `tabindex` on images as keyboard users would then have to tab through each and every image. However if the images is part some sort of gallery and you want them to tab through this makes sense. (Just not a blanked rule)
The implementation of @BsNoSi is also adding arbitrary hash links to the image that then scroll the content to the top each time you click it plus it's not very semantic.

I guess you could do something like this (not tested):

```html
<button class="viewer" type="button>
	<image class="viewer-image" src="url" alt="alt text">
</button>
```

and some small less/sass:
```less
.viewer {
	-webkit-appearance: none;
	border: 0;
	background: transparent;
	padding: 0;

	&:focus {
		.viewer-image {
			max-width: 90%;
			max-height: 90%;
			width: auto;
			height : auto;
			transform: translateY(-50%);
			transform: translateX(-50%);
			transition: transform 0.2s ease;
		}
	}
}
```

_Note: You didn't need `transition` on there if you delay it by 0 seconds and having it transition `all` means a lot more redraws_

**Comment by BsNoSi** [comment]
I tried it on several touch devices and it works fine. Only Opera mobile (generates optimized pages, ignoring several css properties) is a challenge, but this is very special.

I modified the sample above from ´tabindex="0"` to `tabindex="-1"`. This ignores images (without link) in tab order. You can test it, I modified my blog accordingly. There images still *zoom* because they are surrounded from a link — which is still a  standard tab-target. If you try [this page](http://blog.nosi.de/edit/hier-gehts-zu-nosi) you will see the effect, I removed the empty link.

**Comment by BsNoSi** [comment]
@dominikwilkowski: My target is a zoom of images without additional html code.

- how do you achieve the *viewer*-class on the image with (pure) markdown?
- how do you achieve a *button* with (pure) markdown?

Any hints welcome.

And yes — the css is a little bit *messy* — it contains testing parts, it can be cleaned up.

**Comment by dominikwilkowski** [comment]
@BsNoSi no worries about the CSS bing messy. I know how it is ;)
You are razing a valid point. I don't think you can have buttons in markdown let alone classes. But that's why markdown is so great: you don't have to use it...
You can completely get away with something like:

```markdown
##Headline

paragraph _text_ ipsum lorem **blah**

<button class="viewer" type="button>
    <image class="viewer-image" src="url" alt="alt text">
</button>
```

No I am not sure about Yellows parsing engine. If you use [CommonMark](http://commonmark.org/) you would be able to. There are just too many "developers" using hash links to do what a button is for. Semantics in HTML is much more important than on the back end as HTML falls back to browser styles and behaviour when things fail and still work.

**Comment by BsNoSi** [comment]
Mixing Markdown with HTML reduces the unified usage heavily. If this code is not recognized as that, you mess up i.e. PDF documents, created from the same markdown document.

You may use html with YELLOW, but my target is no mixed markdown/html document to keep it clean. CommonMark imo is not the way for solving that (at least not in the currently described way), because it mixes two different approaches and leaves the meta level of markdown in it´s pure design. 

Maybe something like `~~~{zoom}` could be a solution. It is currently used (i.e. on GitHub) for highlighting of code, this might be a way for something different, instead of highlighting? — I did not really begin thinking about the consequences of this idea…;)

**Comment by BsNoSi** [comment]
@Mark: Javascript is no solution, because it is the same challenge: how can I achieve that with pure markdown?

I should give some more information: I am looking forward to use Yellow for more than my own sites. Some friends and partners asking me for a *simple and for technical Dummies available solution*. Pure Markdown is very easy to understand, Yellow offers a perfect system for those users (THANK YOU!).

Additional requirement of HTML or Javascript destroys this simple and very clean design.

**Comment by dominikwilkowski** [comment]
no worris @BsNoSi 
I'm all for standards hence me suggesting to stick with them but I see you already made changes to your markdown language so creating something new makes sense then I guess.

**Comment by BsNoSi** [comment]
I am not sure, if it is intuitive for users, to click on the image to zoom and then *click somewhere except the image* to close. In galleries typically clicking the image moves to the next one. To close the gallery, you have to click *somewhere except gallery image*, too typically. Therefore it seems to me to be a practical solution without additional coding inside the markdown file.

On touch devices many users zoom with touch gestures, in this case my attempt is not necessary but it does not disturb this. And because the scaled image has a usable resolution, this use case is supported as well casually.

This workaround may be obsolete as soon as firefox behaves like the other *big ones*. But as far as I can see, it solves a very basic challenge (use markdown only) and no additional scripting, a.s.o. is required (keep it simple).

**Comment by markseu** [comment]
How about using the [gallery plugin](https://github.com/datenstrom/yellow-extensions/tree/master/plugins/gallery)? Here's are examples for showing single images:

```
[gallery photo-coffee-love.jpg]
[gallery photo-coffee-love.jpg - 20%]
[gallery photo-coffee-love.jpg "photoswipe right" 20%]
```

As a developer you can also write your own plugins and insert any HTML, CSS or JavaScript into a page. You can generate HTML with `onParseContentBlock()`, this allows you to extend Markdown and add a block of HTML at a specific position. For an example see [image plugin](https://github.com/datenstrom/yellow-extensions/tree/master/plugins/image) or [youtube plugin](https://github.com/datenstrom/yellow-extensions/tree/master/plugins/youtube). You can add CSS with `onExtra()`, this allows you to insert additional style sheets into the page header. For an example see [fontawesome plugin](https://github.com/datenstrom/yellow-extensions/tree/master/plugins/fontawesome) or [highlight plugin](https://github.com/datenstrom/yellow-extensions/tree/master/plugins/highlight). You can also JavaScript with `onExtra()`, this allows you to create even more advanced features. For an example see the gallery plugin.

**Comment by BsNoSi** [comment]
I solved my challenge with a plugin for Yellow: [imgcale](https://github.com/BsNoSi/imgscale). My first github release ;

**Comment by markseu** [comment]
Good work :+1:
