### ISSUE TITLE
Is Nesting Pages Possible?

### ISSUE THREAD

**Issue by nogginfuel** [datenstrom/yellow#159]
Earlier I was trying to add nested pages, but It didn't seem to be working for me. I was trying to accomplish something like the following:
**- 1-shop**
_--- 1-productA
--- 2-productB
--- 3-productC_

Adding sub folders didn't seem to work very well. The only other way I can think about doing this is setting up the shop area like a blog, but I'm not sure if that would work. Any help or feedback is greatly appreciate

**Comment by BsNoSi** [comment]
Do you want to have a menu with sub folders or is it a challenge of organizing it?

I have realized this for a [shopping street in Frankfurt/Main, Germany](http://www.oederwegffm.de "OederWegFFM.de"). If you click on `Angebote` in menu (top), you are led to a subpage, organizing the groups and this leads to a page with all pages within the group. On each page one shop is presented with a short description.

**Comment by nogginfuel** [comment]
@BsNoSi Thanks for your input. I understand what you are trying to present with that example. It is similar to what I was looking for but I've attached an image to add clarity.

![nested](https://cloud.githubusercontent.com/assets/2807575/12983581/cf21a5ae-d0b7-11e5-9545-31ec7df11817.png)

So, I've been able to successfully add "subpages" under some of the folders as you see under the "Shop" folder. However, I have been unsuccessful in trying to add subpages to the folder that is seen as the "home" directory for the overall YellowCMS install. Meaning, if I add a subfolder under "Home" as seen the picture, the links will not properly navigate to the content. Also hand typing the until URL path into the address bar fires off a "Content Not Found" message instead of the file.

So circling back to my question from yesterday with additional clarity, Is it possible to have underlying pages underneath the home/primary directory for Yellow?

**Comment by markseu** [comment]
Yes, it's possible to have subfolders. 

Let's take a look from the viewpoint of the website URL. The home folder is what's available at `http://website/`. The shop folder is available at `http://website/shop/`. If you want URLs like `http://website/shop/producta/` and `http://website/shop/productb/`, then you create the corresponding subfolders in your [content folder](https://github.com/datenstrom/yellow/wiki/Adding-content). Not in your home folder. Here's an example:

![screen shot 2016-02-11 at 22 51 44](https://cloud.githubusercontent.com/assets/2429165/12992053/7fa59336-d112-11e5-8034-c06836f37c29.png)

You should be able to create the content structure you want. You can make it flat and put multiple files in a folder. You can make it nested and put files into subfolders, as shown in the screenshot above. If you do use multiple subfolders, you might want to add a custom navigation or [breadcrumbs](https://github.com/datenstrom/yellow-extensions/tree/master/plugins/breadcrumbs). 

Does this answers your questions?

**Comment by nogginfuel** [comment]
Yes, thank you for the additional explanation and examples. I guess I wasn't thinking that the first folder would redirect to the regular domain which would make all the underlying pages not point / redirect properly. This has definitely helped. Thanks everyone who added to the discussion.

**Comment by markseu** [comment]
Good luck with your shop! :smile:

**Comment by nogginfuel** [comment]
Thanks, I've got dueling banjos at the moment. Two different installs of Yellow CMS one trying Shoprocket.co e-com API and the other is going to use Snipcart.com hybrid e-com approach. I have to see which will better fit my needs. More to come...

**Comment by markseu** [comment]
Subfolders in the home folder will no longer be silently ignored, instead it will show an error page. When you make a subfolder in your home folder, that folder will be available under it's full name and treated as any other folder. Not sure if this is a better behavior, hopefully it makes life easier for new users.
