### ISSUE TITLE
Strikethrough not showing

### ISSUE THREAD

**Issue by creamyshot** [datenstrom/yellow#161]
Hello !
So I used the `~~ ~~`  as Mardown requires for Strikethrough. It does not render on this page http://ressources-web.com/facturation/comparaison_factu (Chrome or Firefox).

I reinstalled also Fontawesome, and it still does not work. I do not know what is wrong, maybe my host forbids the use of *.woff file ?

Best Regards

**Comment by markseu** [comment]
Unfortunately strikethrough is not a feature of normal Markdown. There are different Markdown flavors and the one we are using is called "Markdown Extra". As soon as features are added there they will become available, see https://github.com/michelf/php-markdown/issues/211. How about using [HTML del tag](http://www.w3schools.com/tags/tag_del.asp) in your content files?

About [Fontawesome](https://github.com/datenstrom/yellow-extensions/tree/master/plugins/fontawesome), did you try the examples? Do you have a test page to show the problem?

**Comment by creamyshot** [comment]
1 - OK ! 
2 - yep check the homepage of the above site : before the footer you have the fontawesome tag as it.

**Comment by creamyshot** [comment]
A double quote was the trouble... resolved !
