### ISSUE TITLE
Tag hyperlink failing when placed Blog in subfolders

### ISSUE THREAD

**Issue by hysonlee** [datenstrom/yellow#162]
Hi,
I met an interesting problem, first introduce my file structure of `content` folder:
```
/
├content
    ├─1-home
    ├─2-note
    │   ├─3-blog
    │
    ├─4-wiki
    ├─5-about
```
The `blog` folder placed in a sub folder under `content`, when click the blog tag ,page not list the related tag of article(s), just go to the parent directory. For my this case, the URL of blog tag(s) should be `website/note/blog/tag:xxx/`, but the showing URL is  `website/note/tag:xxx/` when hover, after click the page display the the content of `website/note/`. Wiki pages also the same problem.

All the verification under the fresh Yellow installation and the version up to date, plugins just added `blog`,`wiki` and `breadcrumbs`.

Where I made a mistake or a possible bug.

**Comment by markseu** [comment]
Hi Hyson, good to hear from you again. 

I looked into the source code, here's what I found out. The blog makes the assumption to be in one of the top folders. When it creates links for tags it uses `$yellow->page->getParentTop()->getLocation()` to figure out where the blog is. Which works when the blog is in a top folder, but is wrong when the blog is placed in a subfolder. The same happens in the wiki plugin. 

Not sure if this is a bug or a feature. Should we give up the assumption that the blog/wiki main page is in one of the top folders? If yes, then we can replace `getParentTop()` with `getParent()` in snippets. What do you think?

**Comment by hysonlee** [comment]
I think no matter where the blog/wiki be located in and all the work fine that would be better. Of course the assumption is good for starter.

Thanks for your explanation， Mark.
________________________________
发件人: Mark Seuffert<mailto:notifications@github.com>
发送时间: ‎2016/‎2/‎14 20:28
收件人: datenstrom/yellow<mailto:yellow@noreply.github.com>
抄送: Hyson Lee<mailto:bali.0735@gmail.com>
主题: Re: [yellow] Tag hyperlink failing when placed Blog in subfolders (#162)

Hi Hyson, good to hear from you again.

I looked into the source code, here's what I found out. The blog makes the assumption to be in one of the top folders. When it creates links for tags it uses `$yellow->page->getParentTop()->getLocation()` to figure out where the blog is. Which works when the blog is in a top folder, but is wrong when the blog is placed in a subfolder. The same happens in the wiki plugin.

Not sure if this is a bug or a feature. Should we give up the assumption that the blog/wiki main page is in one of the top folders? If yes, then we can replace `getParentTop()` with `getParent()` in snippets. What do you think?

---

**Comment by markseu** [comment]
Good point, I updated blog and wiki as you suggested. Does this work for you?

**Comment by markseu** [comment]
Looks like you are busy, Hyson. I close this issue in good belief that it's solved.

**Comment by hysonlee** [comment]
Sorry for delaying response,these days are really busy, I'll have a try later.

发自我的 Windows Phone
________________________________
发件人: Mark Seuffert<mailto:notifications@github.com>
发送时间: ‎2016/‎3/‎3 16:59
收件人: datenstrom/yellow<mailto:yellow@noreply.github.com>
抄送: Hyson Lee<mailto:bali.0735@gmail.com>
主题: Re: [yellow] Tag hyperlink failing when placed Blog in subfolders (#162)

Looks like you are busy, Hyson. I close this issue in good belief that it's solved.

---

**Comment by hysonlee** [comment]
I have tried the updated `blog` and `wiki` plugins, they are work now, premise is to manual define the Meta settings as`Template:blogpages` or`Template: wikipages` at the default `page.txt`.

I remember you have explained it to me that the Yellow program will automatically detect the folder name of `2-blog`/`3-wiki` where they are as their template, if changed their folder name then should manual setting  templates. In this case, `3-blog` under a sub folder same effect as change folder name.

**Comment by markseu** [comment]
Thanks for testing, Hyson.
