### ISSUE TITLE
user account not working

### ISSUE THREAD

**Issue by georgesuba** [datenstrom/yellow#163]
Hi.. I've created user account according to docs in wiki but when I press edit the page with correct email and passwd then page just reload.. and nothing happen. what permissions should be on files and folders?

I got for folders: 755
for files: 644
apache 2.4
congif as provided with downloaded yellow

Thanks.

EDIT: additionally when login window is closed and any page clicked on menu, page is loaded with login window over top of it.. this behaviour occurs in both in latest chrome and ff.

**Comment by markseu** [comment]
Can you login and edit a page in the [Yellow demo](http://demo.datenstrom.se)? Does that work for you?

**Comment by georgesuba** [comment]
on demo page yes.. but not on my server

**Comment by markseu** [comment]
Which [Yellow version](https://github.com/datenstrom/yellow-extensions/tree/master/plugins/core#example) are you using? If you want me to take a closer look, [send me an email](http://datenstrom.se/contact/).

**Comment by georgesuba** [comment]
@markseu 

Okay my bad.. everything works on production server. I think its problem on my dev server which sits on localhost:8080.. have no idea why it is doing that as dev server setup is exactly same as production server. I will try to figure this out so I can develop and test themes for this great cms.

**Comment by markseu** [comment]
:smile:

Good to hear... but strange that it doesn't work on your development server. I have a similar workflow, I develop on my regular computer (Macbook) and then upload it later to the regular web server (Linux). Can I ask something, what web server and operating system you are using on localhost?

**Comment by georgesuba** [comment]
Sure.. its debian 8 - virtualmin installed - local domains and subdomains running in virtualbox.. :) everything works just this cms wont .. I mean cms works fine just login.

**Comment by georgesuba** [comment]
okay I am really thankful for this cms.. I reviewed the files and trying to create new theme based on bootsrap.. however I cannot find where I am getting js and css out from.. in your default theme everything is located in header.. I would like to add comments to my theme and also move js into bottom of the page.. where I can locate those so I can make changes? is there any skeleton theme like empty one?

**Comment by markseu** [comment]
Should be working now, setting cookies was wrong for localhost with portnumber.

Can you please test latest [webinterface plugin](https://github.com/datenstrom/yellow-extensions/tree/master/plugins/webinterface), does it work for you?

**Comment by georgesuba** [comment]
didn't work for me but I see correction :)

As I told you I have virtualmin in virtualbox redirected in my linux os as localhost.. I have local domains like dev.dev (domain.com) so I've changed two lines:

`if(preg_match("/^localhost(:\d+)?$/", $serverName)) $serverName = false;`
to
`if(preg_match("/^dev.dev(:\d+)?$/", $serverName)) $serverName = false;`

and it works - Thanks. I think cookies are now correct.. shall I open new question about theming? or we keep discussing it here?

**Comment by markseu** [comment]
Here's another attempt, setting cookies should now work better with port numbers. Give it a try please.

**Comment by georgesuba** [comment]
this one does not work at all.. I would rather retrieve that file back to older version - the one where was those two lines: `if(preg_match("/^localhost(:\d+)?$/", $serverName)) $serverName = false;` - that was working on custom localhost domains fine when edited towards user needs..

**Comment by markseu** [comment]
@wunderfeyd Can you have a look please?

**Comment by wunderfeyd** [comment]
@georgesuba Could you update the [`system/plugins/webinterface.php`](https://github.com/datenstrom/yellow/blob/master/system/plugins/webinterface.php) to version 0.6.3 please. Please delete your cookies for the website/your installation and test again.

**Comment by georgesuba** [comment]
morning guys.. @wunderfeyd I can confirm that 0.6.3 version worked right a way on localhost:custom-ports and localhost-custom-domain:custom-ports (dev.dev:8080) without any modifications to the file. It also works on normal production server and domain right a way - this is great. Thank you.

**Comment by markseu** [comment]
It also works with different operating systems, we tested it again on iOIS, Linux, Mac, Windows.

Thank you guys for your help, much appreciated. Please open a new issue if there are more questions.
