### ISSUE TITLE
Geshi for highlighter deprecated with PHP 7 

### ISSUE THREAD

**Issue by BsNoSi** [datenstrom/yellow#164]
I tried updating my server to php 7. But this leads to a deprecated message:

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; GeSHi has a deprecated constructor in /[…]/yellow/system/plugins/highlight/geshi.php on line 259

**Comment by markseu** [comment]
Good idea! The patch for PHP 7 is in latest [GeSHi repository](https://github.com/GeSHi/geshi-1.0). Want to send a pull request?

**Comment by BsNoSi** [comment]
I have to admit, that I do not really know how GitHub works („pull request“). I am a *passive user*, missing the time, to investigate and learn this (sorry). Since I have the GitHub account, I want to alter this, … — but this is another story.

Currently I removed Geshi from my plugins directory (not really needed in that installation) and YELLOW works really nice with PHP7, especially much faster, which does not mean, that it was slow before ;)

**Comment by markseu** [comment]
At the heart of open source is the idea that by sharing code, we can make better software together. 

Contribution is much appreciated. Here's how to make a pull request:

- Download [GitHub Desktop software](https://desktop.github.com) and configure your user account
- Open https://github.com/datenstrom/yellow-extensions and click **Fork**
- Clone forked repository to your computer, click save button :arrow_down:  
- Make changes on your computer... until you're happy with it
- In the GitHub software on your computer click **Commit and sync master**
- In the GitHub software (or forked repository on GitHub) click **Pull request**

**Comment by BsNoSi** [comment]
Thank you for description. I will try, but this will take some time. Before that, I try to publish my first YELLO-plugin.

**Comment by markseu** [comment]
Should be working now, verified with automated tests.
