### ISSUE TITLE
New Markdown > Parsedown Plugin

### ISSUE THREAD

**Issue by thozie** [datenstrom/yellow#168]
Hi,
inspired by the [Markdown Parser Benchmark](http://parsedown.org/demo?example=markdown_readme) and the fact that the original Markdown does not support `~~strikethrough~~` I made a Plugin wich replaces the original Markdown Parser with the much faster Parsedown Parser.  
It's working perfect and takes around 25% to 50% less time to process the markdown. If your site has a blogpage with 5 or more blogpost previews you can expect significant lower pageload time, especially if you have autogenerated Navigation and Sidebar.

However, there's one downside to it. The needed `[--more--]`, wich is needed to force a pagebreak for the preview of blogposts, is not working at present. I simply can't find the reason why and would appreciate a lot if someone could give me a hand here.

To activate the plugin simply load the [parsedown.php](https://github.com/thozie/yellow-parsedown) into your plugins folder, open your config.ini and change `Parser: markdown` to `Parser: parsedown`.

Thanks for your valued input ;-)

**Comment by markseu** [comment]
Sounds great, a faster and smaller Markdown parser.

I think the `class YellowMarkdownParser` needs to be rewritten for Parsedown. For example  `function _doImages_inline_callback()` has the equivalent `function inlineImage()` in Parsedown. Have a look if you find a way to integrate `[shortcuts]` and `[--comments--]` then a lot of plugins will start working.

For testing you can use the [developers kit](https://github.com/datenstrom/yellow-developers) and see if pages come out as expected. Happy coding! :smile:

**Comment by markseu** [comment]
Sorry clicked the wrong button.

Here's a tutorial for [Parsedown extensions](https://github.com/erusev/parsedown/wiki/Tutorial:-Create-Extensions).

**Comment by thozie** [comment]
Dang... pictures are not working as of now. That's the outcome when testing with no pictures added to the text ;-) I'll look over it when i have more time. Thanks for letting me know.

**Comment by markseu** [comment]
On the first glance I like the way Parsedown works, clean and simple design. It just took a few minutes to get the images working again, that's how I found the function above. When it comes to the rest, I couldn't find it right away, probably needs some more digging. I am curious what you find out.

**Comment by markseu** [comment]
Did you find something out?

**Comment by markseu** [comment]
If others would like to see this feature, please add +1 to this issue.

**Comment by BsNoSi** [comment]
I tried a few weeks ago and was surprised about speed an much lower server load of parsedown. But currently I have no time for reliable testing.

**Comment by markseu** [comment]
It looks like nobody is woking on this anymore, so I am closing the issue.

**Comment by markseu** [comment]
I made an experimental plugin based on Parsedown Extra. See #354
