### ISSUE TITLE
How to modify Search for hidden/non-menu files

### ISSUE THREAD

**Issue by nogginfuel** [datenstrom/yellow#170]
I would like a way to modify the search plugin to look at files that are not within the menu structure. This is specifically important because I'm using Yellow for e-com and would like the specific product pages to be identified not just the highest level category page.

Any help or ideas greatly appreciated.

**Example:**
Changing the result for "product x" from this:
.com/shop/
lorem ipsum **product x** ipsum lorem

**to this:**
.com/shop/thing/productx
lorem ipsum **product x** ipsum lorem

**Comment by markseu** [comment]
How about making pages visible? If that would work, make sure every folder has a numeric prefix. For example file `content/1-shop/1-thing/productx.txt` = `http://website/shop/thing/productx`. As a rule of thumb, folders with prefix are for visible pages, folders without prefix are for invisible pages.

To answer your question, here's how to modify the search plugin to include any page. Replace `$this->yellow->pages->index(false, false)` with `$this->yellow->pages->index(true, false)`. The first argument defines whether or not to include invisible pages.

Hope this helps. :smile:

**Comment by nogginfuel** [comment]
That worked really well! Thanks for the help @markseu - exactly what I was hoping for.
