### ISSUE TITLE
Home page for Blog

### ISSUE THREAD

**Issue by nibreh** [datenstrom/yellow#173]
Hello

I would like to have a home page for the blog, not the posts

**Example:**

My blog is installed in `1-blog` folder and my url `mydomain.com` display the posts

I would like to see the content of `page.txt` (automatically generated) in `1-home` and not the posts !

Of course, `mydomain.com/tag:example` and `mydomain.com/published:date` must displayed the posts, but not the content of `page.txt` !

THX

**Comment by schulle4u** [comment]
Isn't the `[blogrecent]` shortcode what you're looking for? This however only shows a list of post titles, but should be no huge problem to extend this to display also post excerpts.

**Comment by markseu** [comment]
I am wondering what you what you are looking for. Can you describe a little bit more, for example what's the result you would like to have or how it should look like?

**Comment by nibreh** [comment]
HAHA, sorry, my english is not so good

In fact It's not really important, it's just an interrogation

I do not want the blog in folder `2-blog` because of URLS `mydomain.com/blog/post-example`. I want something like `mydomain.com/post-example`. So I installed the blog plugin in folder `1-blog`

Now `mydomain.com` display the posts, that's normal.

But what I want to display is the content of `page.txt` in `1-blog` for `mydomain.com`, and not the posts. The sidebar already display recent posts and tags with `blogrecent` and `blogtags`.

So in `content-blogpages.php`, I must add something like `<?php echo $yellow->page->getContent() ?>` etc

Now Urls like `mydomain.com/tag:example` must display the posts, and not the content of `page.txt`

I hope It is more clearer ;)

**Comment by markseu** [comment]
Yes that's possible. 

If you don't want an extra `1-home` folder you can customize your blog. Please use latest [blog plugin](https://github.com/datenstrom/yellow-plugins/tree/master/blog) and change file `system/themes/templates/blogpages.html`. Here's an example to show a home page:

```
<?php $yellow->snippet("header") ?>
<?php $yellow->snippet("content-sidebar") ?>
<?php $yellow->snippet($yellow->toolbox->isLocationArgs() ? "content-blogpages" : "content-blog") ?>
<?php $yellow->snippet("footer") ?>
```

Second example shows a home page, without a published date and tags:

```
<?php $yellow->snippet("header") ?>
<?php $yellow->snippet("content-sidebar") ?>
<?php $yellow->snippet($yellow->toolbox->isLocationArgs() ? "content-blogpages" : "content-main") ?>
<?php $yellow->snippet("footer") ?>
```

Does that work for you?

**Comment by nibreh** [comment]
Perfect ! That is very useful. Works fine with yellow-master. Thanks @markseu
