### ISSUE TITLE
Looking for a German translator

### ISSUE THREAD

**Issue by markseu** [datenstrom/yellow#174]
Hi, I am looking for help. Does someone speak German and want to help with the Yellow documentation? There are two text files left to translate, then we're done. Would be great to get some help, thanks!

**Comment by CryssDOTnet** [comment]
I can do that.

**Comment by CryssDOTnet** [comment]
What files exactly?

**Comment by markseu** [comment]
Cool @CryssDOTnet, here are the files:

https://github.com/datenstrom/yellow-developers/blob/master/content/4-help/how-to-make-a-blog-de.txt
https://github.com/datenstrom/yellow-developers/blob/master/content/4-help/how-to-make-a-wiki-de.txt

**Comment by markseu** [comment]
Thank you @CryssDOTnet for the German translation! :+1:
