### ISSUE TITLE
Some images doesn't show

### ISSUE THREAD

**Issue by nibreh** [datenstrom/yellow#175]
I'v got an image named adlib.jpg

`[image adlib.jpg adlib]` doesn't show the image

Tested with image named `ad.jpg` and doesn't work

but strangely, `adc.jpg` is working

Perhaps an explanation ?

Tested on a fresh install with yellow-master

**Comment by markseu** [comment]
It's probably blocked in the web browser by AdBlock, AdBlock Plus or similar.

**Comment by nibreh** [comment]
That's right !

I'm using Ublock Origin and Privacy Badger with Firefox.
I Always forget to deactivate them on certains sites.
Hope this issue can be helpful for some users.

Thanks
