### ISSUE TITLE
API -> Is there a ID

### ISSUE THREAD

**Issue by nasendackel** [datenstrom/yellow#177]
Is there a kind of ID for every post / page? Wordpress, for an example, has <? the_id();?>, which outputs the unique number? Do we have something equal in Yellow? A unique string? 

I am just asking, because then I could give div a unique id. Like.

`<div id="<?php ID ?>"></div>`

**Comment by markseu** [comment]
Sorry, there's no numerical ID. Every page has a unique file name, that's what Yellow uses internally. 

You can use the location instead, for example `<?php echo $page->getLocation() ?>`. 
You can also create your own setting `Post:1234` and use `<?php echo $page->getHtml("post") ?>`.

**Comment by nasendackel** [comment]
Thanks a lot. That will work!
