### ISSUE TITLE
No cURL on Ubuntu Linux

### ISSUE THREAD

**Issue by markseu** [datenstrom/yellow#178]
When you check software version on Ubuntu Linux, it might not work and you get the following error message: Plugin 'commandline' requires cURL library! This means that the cURL package is missing on your Linux installation. You can install it with `sudo apt-get install php5-curl`

**Comment by schulle4u** [comment]
This also applies to Debian and probably other Debian-based distros. Missing Curl extension however isn't a bug actually. It just have to be installed like every other optional php module which is not a part of the core, even though it should be in my opinion.

**Comment by markseu** [comment]
Yes you're right, more of a problem than a bug. It's working after installing the cURL package.
