### ISSUE TITLE
Googlemaps plugin lazyload?

### ISSUE THREAD

**Issue by MrMacStripe** [datenstrom/yellow#182]
Hi,

I want to use the googlemaps plugin for some dates with location information. The map is hidden behin a click-to-expand button. Is there a way to implement a lazy load/only load if displayed option, because the iframes slow the site down and cause heavy traffic.

The reason for public asking is mainly because this could be interesting for some other people as well and I didn´t have the time to work on a solution myself so far. Maybe someone already did it :)

**Comment by markseu** [comment]
Sorry, there's no lazy load in the [Googlemaps plugin](https://github.com/datenstrom/yellow-plugins/tree/master/googlemaps). It's a simple plugin which embeds an Iframe.

You could write a plugin which uses the Google maps API, which should allow you to lazy load a map. Maybe someone wants to write a new plugin, any help would be much appreciated. 😄

**Comment by BsNoSi** [comment]
Maybe you can solve that with a simple trick: Create a copy of the page with click-to-expand botton. Click to expand leads to the dublicated hidden(!) page, with the google plug in added. By loading the map the few bytes more for the double page may not matter. The back button … I think, there is no mor explanation required. :)
