### ISSUE TITLE
Need Sidebar to display on small screens

### ISSUE THREAD

**Issue by nogginfuel** [datenstrom/yellow#183]
Currently the default sidebar disappears completely on small screen sizes. This makes sense as having a sidebar on those formats would cause issues.

However, I would still like the data / information within the sidebar to display in different position. I would like the "sidebar" to  display directly below the Main Content area when displaying page on small screens.

Has anyone else looked into this? I still need links / navigation in sidebar to be available in some fashion on smaller screens. All help is greatly appreciated.

**Comment by BsNoSi** [comment]
I think this is only a challenge of the used stylesheet and a small modification of the page structure. "Only" will take time — I admit, that I need something similar, but currently I do not have enough time for doing it. I will keep you informed, if I have a solution.

**Comment by BsNoSi** [comment]
You may have a [look at my blog](http://blog.nosi.de).

I added a `div class="flow"` to my templates (one example, required in each used template):

~~~php
<?php $yellow->snippet("header") ?>
<div class="flow">
<?php $yellow->snippet("content-main") ?>
<?php $yellow->snippet("content-sidebar") ?>
</div>
<?php $yellow->snippet("footer") ?>
~~~

and modified the css:

~~~css
.flow{display:-webkit-flex; display:flex;-webkit-flex-wrap:wrap;flex-wrap:wrap;-webkit-justify-content:space-between;justify-content:space-between;}
.main{-webkit-flex-basis:70%;flex-basis:70%;}
.sidebar{-webkit-flex-basis:20%;flex-basis:20%; min-width:12em;}
~~~

The `flex` part is switched

~~~css
@media screen and (max-width:44em){.flow{-webkit-flex-direction:column;flex-direction:column;}
}
~~~

on smaler displays.

Maybe this helps.

**Comment by BsNoSi** [comment]
I reworked my blog completely. Now it has a "burger navigation", that behaves responsive in any circumstances. Appending zip contains a working demo, based on Yellow 0.6.5. Demo should be self explaining. Comments welcome.
[burger-demo.zip](https://github.com/datenstrom/yellow/files/392418/burger-demo.zip)

**Comment by markseu** [comment]
You can adjust the sidebar with CSS. Open a theme and at the bottom you see something like this:

```css
.with-sidebar .sidebar { display:none; }
```

Replace it with the following:

```css
.with-sidebar .sidebar { float:none; width:auto; margin:1em 0; }
```

Check out flexbox, if you want to change the order of divs with CSS.

https://css-tricks.com/snippets/css/a-guide-to-flexbox/

**Comment by markseu** [comment]
There's also a super simple alternative. You could make a page for your extra information and add a link to the top or bottom of the page. When the sidebar disappears on a small screen, the user can click the link and still find all the extra information.

I have seen this idea on blogs recently. Instead of a sidebar or a hamburger menu, there's a link "Archive" or "Links" which brings you to a dedicated page with blog tags and months.

Let me know if this helps?

**Comment by nogginfuel** [comment]
I'll try your approach Mark. When I tried previously it keeps it visible, but it is at the top, which wasn't super convenient. Hopefully I can try that fix out today. Things have been super busy.
