### ISSUE TITLE
Bootstrap/Bootswatch plugin/theme

### ISSUE THREAD

**Issue by redtide** [datenstrom/yellow#190]
If it could be of any interest/use, I created [this plugin/theme](https://github.com/redtide/yellow-bootstrap).
It's still a work in progress with some issues (incomplete css, modified default header etc.), but I hope someone will find it useful and will suggest improvements.
As usual any feedback is welcome.

**Comment by markseu** [comment]
Thank you. 👍 

Bootstrap/Bootswatch offers many themes, great for people who  want a beautiful website and don't have the time to make an own theme. Is it possible to use different Bootstrap themes with your plugin? Do you want to add a short documentation how to install them?

**Comment by redtide** [comment]
The short installation guide is the typical readme on the github plugin page and there is also a cereulan theme example at the end.
IDK about bootstrap but only about bootswatch to have different themes to choose and it is done by set the bootstrapCdnCSS source as explained in the readme.
Other themes are listed on the bootswatch website or at https://www.bootstrapcdn.com/bootswatch/
