### ISSUE TITLE
HTML5 audio plugin

### ISSUE THREAD

**Issue by schulle4u** [datenstrom/yellow#192]
I've written a basic [Audio plugin](https://github.com/schulle4u/yellow-plugin-audio) for my personal needs. 
There is already the medialist plugin, however I needed a plugin which is able to play not just local media files and also can embed audio streams. So I did this quick and dirty HTML5 `<audio>` implementation. The plugin provides a `[audio]` shortcut to embed an audio player with play/pause, mute, volume and seeking controls. A flash fallback is not available, and I'm not going to support this feature. Instead you can enable a direct download of the file for older browsers (off by default). 

Feel free to make suggestions/corrections. I'm just a coppy/paste programmer, so mistakes can happen. :)

Steffen

**Comment by nibreh** [comment]
Hi. NICE ! Thank you.

Maybe you can precise the audio file must not contain space.

**artiste song.mp3** must be **artiste-song.mp3**

**Comment by schulle4u** [comment]
Perhaps `%20` will work as space replacement? I usually don't use space characters in web environments. 
But thanks for reporting, I'll do some testing and give hints in the readme accordingly. 

Steffen

**Comment by nibreh** [comment]
HI

I made a plugin to create a playlist: https://github.com/nibreh/yellow-plugin-audio-playlist

Inspired by http://devblog.lastrose.com/html5-audio-video-playlist/ and your audio plugin

Reports are welcome.

**Comment by schulle4u** [comment]
Well done, I'm glad that my work has been an inspiration for you. Currently I don't need a playlist player, but surely will test your code if I ever should need one. 

Currently I'm thinking of adding another player variant to my single-player-shortcode which displays the audio player as popup in a new window. This is useful especialy for webradio streams, when the user wants to browse the site while listening. Ideas welcome :)

Steffen

**Comment by markseu** [comment]
Nice work, thank you! Here are my favourite radio streams for this summer:

- http://streams.frequence3.net/mp3-192.m3u "Frequence 3"
- http://streaming.hotmixradio.fm/hotmixradio-hits-128.mp3 "Hotmix Radio Hits"
- http://wr17-icecast.mtg-r.net/wr17_mp3 "Summerburst Radio"

Any suggestions/recommendations? ☀️ 🎶
