### ISSUE TITLE
Mixcloud and Splice plugins

### ISSUE THREAD

**Issue by SAMY2K** [datenstrom/yellow#193]
I created a [Mixloud plugin](https://github.com/SAMY2K/yellow-plugin-mixcloud) and a [Splice plugin](https://github.com/SAMY2K/yellow-plugin-splice). They let you embed their audio widgets. 

Mixcloud is a popular online platform where DJs host their mixes and on Splice you can upload and download full audio projects. The site is getting popular especially among electronic music producers, already used by David Guetta, Tiësto, KSHMR and more.

**Comment by markseu** [comment]
Thank you. 👍
