### ISSUE TITLE
Leaflet Plugin (map and markers)

### ISSUE THREAD

**Issue by nibreh** [datenstrom/yellow#195]
Hi! I written a plugin this week, based on [leaflet](http://leafletjs.com/) & openstreetmap

I wanted a collaborative map, where users can add markers with description and link to a page. For events, or anything else !

Take a look: https://github.com/nibreh/yellow-plugin-leaflet

Suggestions/corrections are welcome

Cheers - JUH

**Note:** You must have the recent yellow update to use `plugin.zip`

![](https://raw.githubusercontent.com/nibreh/yellow-plugin-leaflet/master/screenshot-leaflet.png)

**Comment by markseu** [comment]
Looks great. Want to add your plugin to the [Yellow plugins README](https://github.com/datenstrom/yellow-plugins/blob/master/README.md)?

**Comment by markseu** [comment]
Thanks 👍
