### ISSUE TITLE
Plugin: SkipTo

### ISSUE THREAD

**Issue by schulle4u** [datenstrom/yellow#197]
Skipto is an accessibility plugin to enhance keyboard navigation on pages with lager outline. It is a javascript replacement for the classic skipto links andcomes with some more features. The plugin uses [SkipTo.js v2.0.0 by PayPal Accessibility Team and University of Illinois](https://paypal.github.io/skipto/). 

Basically this plugin adds a `Skip to` button to your pages which by default only is visible for keyboard and screen reader users. Clicking this button will open up a menu showing a list of headings, sections or landmarks, depending on how the page has been designed. You can configure what the menu should display. 

Link to plugin: (https://github.com/schulle4u/yellow-plugin-skipto)

Thanks to @Markseu for his valuable input.

**Comment by markseu** [comment]
Thank you for making a new plugin. Want to add your plugin to the [Yellow plugins README](https://github.com/datenstrom/yellow-plugins/blob/master/README.md)?
