### ISSUE TITLE
gallery shortcut not same?

### ISSUE THREAD

**Issue by learningchannel** [datenstrom/yellow#201]
i did a new install of yellow and moved over my content and media. I also have installed image, gallery plugins. My files are in PNG an sometimes JPG... i used to be able to get both file types by doing this:

```
[gallery folder_A/filenameprefix.* - 180px]
```
now with new yellow version I get an error: Something went wrong. Image 'media/thumbnails/filenameprefix-whatever-180x180.jpeg' can't be saved 

this way seems to work nicely:
```
[gallery folder_A/filenameprefix.*png - 180px]
```
but I still want to get both file types. thanks in advance.

**Comment by learningchannel** [comment]
i think i had a corrupted jpg file

**Comment by markseu** [comment]
The error message could also mean that write access wasn't enabled. After a new Yellow installation make sure that the web server can overwrite files, for example with command `chmod -R a+rw *`. 

https://developers.datenstrom.se/help/web-server-configuration
 
Hope this helps. 😄
