### ISSUE TITLE
HTML5 video plugin

### ISSUE THREAD

**Issue by nibreh** [datenstrom/yellow#204]
Hi!

This is a HTML5 video player for Yellow. This plugin embeds a basic video player using the HTML5 <video> tag, the standard way to show video on the web.

https://github.com/nibreh/yellow-plugin-video

Based on [HTML5 audio plugin](https://github.com/schulle4u/yellow-plugin-audio) by @schulle4u 

See you - Juh

**Comment by markseu** [comment]
Thank you 👍
