### ISSUE TITLE
onParseContentBlock check if page is "sidebar"

### ISSUE THREAD

**Issue by richi** [datenstrom/yellow#209]
Hi,

I have done a small extended version of the toc plugin (https://github.com/richi/yellow-plugin-etoc) that can show the toc of the main page inside the sidebar.

To detect whether the `onParseContentBlock()` call is indeed parsing a sidebar I use `$page->get("title") == "Sidebar"`. That does feel a little awkward since it does depend on the title... Is there a better way?

Cheers, richi

**Comment by markseu** [comment]
You can use `$page==$yellow->page->getPage("sidebar")` to check a page.

Btw, the [TOC plugin](https://github.com/datenstrom/yellow-plugins/tree/master/toc) can show the table of contents inside the sidebar, too. 

If you're interested in more details, here's how the TOC plugin works. There's the Yellow API function `$yellow->page->getPage($key)`,  which was introduced especially for this plugin. You can set up relations between pages, for example what's sidebar and what's main page. The TOC plugin uses `$yellow->page->getPage("main")` and therefore will always access the content of the main page. 

Happy coding. 😄

**Comment by markseu** [comment]
Have you found a solution that works for you?

**Comment by richi** [comment]
Actually mainly because of `navigation_sidebar` the solution with 

`$page==$yellow->page->getPage("sidebar")` 

does not work reliable. For example, the line 

`if($yellow->page->get("navigation")=="navigation-sidebar") $yellow->page->setPage("sidebar", $yellow->page);` 

in the default `header.php` can get in the way..

But for my current problem I was able to skip `onParseContentBlock`completely thanks to your information :)

**Comment by markseu** [comment]
Yes, you're right. 

I think part of the problem is that it wasn't clear what should happen when a custom navigation and the custom sidebar are used at the same time. I uploaded a slightly improved [sidebar snippet](https://github.com/datenstrom/yellow/blob/master/system/themes/snippets/sidebar.php), please have a look. Now the custom sidebar is dominant, even if you define `Navigation: navigation-sidebar`.

What do you think, does this work better?

**Comment by richi** [comment]
That does indeed work better! 

But still if `navigation-sidebar` is used  (for example) ,  the main page itself get set as its own sidebar in `header.php`. Therefore if I want to know, if a page is a "real" sidebar I have to use something like:

    if ( $page==$yellow->page->getPage("sidebar") && $page!=$yellow->page->getPage("main") )
    { /* then it is a real sidebar */ }

This feels somewhat odd,  but just little :)

**Comment by markseu** [comment]
I know what you mean, it's the most easy code to read. If we can find a better solution I am all for it! 😄
