### ISSUE TITLE
"Hamburger Menu" plugin

### ISSUE THREAD

**Issue by richi** [datenstrom/yellow#213]
Since I need the sidebar on mobile devices as well, I have put together a small plugin that implements a "hamburger menu" for mobile navigation. It does work together with the default themes and can easily be adapted to more "foreign" themes.

Have a look at:

https://github.com/richi/yellow-plugin-burger-menu

On a custom theme this is of course not an issue, but because of the html structure of the default themes, right now the menu etc. has to be generated twice. Any ideas how this could be overcome?

Cheers, richi

**Comment by markseu** [comment]
Good work. About your question, do you have to generate the HTML code twice for the navigation? I checked what a couple of websites do. Here's what I found out: 

1. Some websites generate the navigation once, one "main" navigation. They change CSS visibility/style/position to transform the navigation on a mobile screen.  
For example http://alistapart.com
2. Some websites generate the navigation twice, one "main" navigation plus one "mobile/overlay" navigation. They change CSS visibility to switch between those navigations on a mobile screen.  
For example http://www.withings.com
3. A few websites generate the navigation twice, like above but the hamburger button stays always visible. They change CSS visibility to hide the main navigation on a mobile screen.

It looks like one navigation is enough for most web designs, two navigations give more flexibility.

**Comment by BsNoSi** [comment]
For saving bandwidth it is always better, to create as less data as possible.

**Comment by markseu** [comment]
Feel free to add your plugin to the [Yellow plugins README](https://github.com/datenstrom/yellow-plugins/blob/master/README.md).
