### ISSUE TITLE
After upgrading to version 0.6.6 errors in the frontend

### ISSUE THREAD

**Issue by AlexL777** [datenstrom/yellow#214]
Hello developer,

I have at http://wpzweinull.ch/cms/yellow my Yellow website and after the upgrade to the version 0.6.6 per command line I have a bug in the front end.

`Server error
Something went wrong. Language 'de' does not exist!`

The language "de" is not found. How can I solve the problem or what do I have to do for it?

Thanks in advance.

**Comment by markseu** [comment]
Hi Alex,

looks like the German language file is missing. You can download it from here:
https://github.com/datenstrom/yellow-plugins/tree/master/language

The language files are now stored in your `system/plugins` folder.
If you find old language files in `system/config` you can delete them.

Hope this helps

**Comment by markseu** [comment]
Looks like the language is working now. Have you found more problems?

**Comment by AlexL777** [comment]
I like to do that. The theme change also works well and so I have no problems with the Yellow CMS :smile:
