### ISSUE TITLE
After upgrade, the blog navigation does not work

### ISSUE THREAD

**Issue by AlexL777** [datenstrom/yellow#215]
Hello developer,

It was first with the language file at Yellow with me. Now I realize that the page navigation is no longer working. I have my Yellow website at http://wpzweinull.ch/cms/yellow .

However, the navigation points in the header navigation lead to the root directory at http://wpzweinull.ch . Do I need to change something in the config.ini?

Thanks in advance.

**Comment by markseu** [comment]
Hi Alex, 

when I have have troubles after updating I usually do the following steps:

This describes a manual update for administrators, for example when updating an older version of Yellow. While doing a manual update, content and media files will not be changed. The only things that will be changed are the Yellow software and customizations.

- go to your Yellow installation
- rename the `system` folder to`system-old`, this is basically your backup
- download [latest Yellow](https://github.com/datenstrom/yellow/archive/master.zip) and unzip it, copy the `system` folder to your installation
- download [plugins and themes](https://github.com/datenstrom), copy relevant ZIP files into  your `system` folder
- compare file `yellow.php` [with new file](https://github.com/datenstrom/yellow/blob/master/yellow.php), make sure that you use the new file
- edit file `system/config.ini`, you can copy the first 5 lines from the backup
- edit file `system/user.ini`, you can copy the lines from the backup
- open website and check that everything works again

@BsNoSi, @schulle4u  do you have some tips for manual update?

**Comment by schulle4u** [comment]
@markseu @AlexL777: Nothing else to say I think. In most parts I usually perform the update as you described, regardless if the version is older or just a step behind. Dealing with CLI-based updates is sometimes a little painful (user ownership, access rights etc), I feel more safe by doing this manually via my good old FTP. Re-applying necessary changes in configs and themes has to be done in both use cases anyway. 

Steffen

**Comment by AlexL777** [comment]
Thanks to both of you! I have just made a manual update and it worked as described above. The auto update via SSH worked well before days, but the blog was not working properly.

Now also the navigation seems to work again. All good!

**Comment by markseu** [comment]
Good that you could make it work and sorry for sending you trough the trouble.
