### ISSUE TITLE
How to prevent spam on the contact page

### ISSUE THREAD

**Issue by AlexL777** [datenstrom/yellow#216]
Hello Developer,

How can I prevent spam on the contact page? What do I need to register in config.ini?

Is the contact form safe against spam? That would be very important to know.

Thanks in advance.

**Comment by schulle4u** [comment]
I think the contact plugin needs some improvements for spam filtering. Currently it only supports a word-based filter which you can customize using the `contactSpamFilter` variable in config.ini. By default, all occurrences of `href=` and `url=` are treated as spam, which imho is way to less for effective spam blocking.

**Comment by AlexL777** [comment]
That sounds good. 

But the contact form can not be misused so that spam is sent to others? That asked one of my blog readers of Internetblogger.de. 

He wanted to know if the security of the contact page was guaranteed.

**Comment by markseu** [comment]
I think the [contact plugin](https://github.com/datenstrom/yellow-plugins/tree/master/contact) is safe to use. It takes care that email is sent only to a configured email address and that it can not be misused to send spam to others. Generally, we spent time on designing and testing this software. Not just that it works as intended, but also that it's safe to use. 

If someone reads this and wants to investigate Yellow's security, please go ahead. Software is never perfect and the more active we become as a community, the better Yellow will be for everyone. 

https://developers.datenstrom.se/help/security-configuration

**Comment by AlexL777** [comment]
Yes, you may ask yourself, but such critical readers I have in the blog :-(

I am not questioning the security of Yellow and I rely on you developers who publish here on GitHub their software. The reader who asked this does not use Yellow and just because he once had bad experiences with a contact page. Can ever happen.

I am satisfied with Yellow. Otherwise, I would not make a fork. But I have done :smile:

**Comment by markseu** [comment]
Thank you. Questions and bug reports are always welcome. :smile:

@schulle4u Do you get many spam emails via your contact page?

**Comment by schulle4u** [comment]
@markseu I haven't tried out the contact plugin to be honest, so my comments regarding (possible) insufficient spam protection raather results from experiences with other email forms. A word-based filter only can be part of a few protection methods. At least IP blacklists or integration of blacklists services such as [the spamhaus project](https://www.spamhaus.org/) or the well-known Akismet would be a nice thing to have for yellow. But... please don't use captchas. They are easy to implement, but they are not as secure as webmasters would like them to be. Not to mention blind people like me who will be locked out from such forms. :)

And another idea: What about a general anti-spam class for the Yellow core? In this case plugin developers wouldn't have to write such code twice if they want to write user feedback plugins (contact, comments, guestbook etc). 

Steffen

**Comment by nibreh** [comment]
Hi. Maybe this can be useful for developers: http://stopforumspam.com - there is an API.

**Comment by markseu** [comment]
Sorry, that there's no advanced spam filter in the contact plugin. It's just a small plugin to send emails. 

I talked with @wunderfeyd about how much spam email we get. In our experience there's not much spam via plugins right now. I think we shouldn't add a better spam filter, unless it becomes a problem. With every feature you add to software, you make it more complex. With every filter you add, you make it harder to use for legitimate people. My suggestions is the following: Please install the current contact plugin, give it a try and see out how it works on your website. 

If spam becomes a problem, [please let us know](https://developers.datenstrom.se/help/support).

**Comment by BsNoSi** [comment]
I use the contact plugin on a few websites I release with Yellow (one of it is a information site with > 12k acess/month). My current experience: less spam there in compare to web sites with „are you human“ (and so on) checks.
