### ISSUE TITLE
Plugin Inline Attachment - Drag and Drop Image Upload

### ISSUE THREAD

**Issue by nibreh** [datenstrom/yellow#218]
Hi. I made a plugin for Yellow to upload images by drag and drop into textarea.

Take a look: https://github.com/nibreh/yellow-plugin-inline-attachment

This plugin use [Inline Attachment by Rovak](http://git.razko.nl/InlineAttachment/). 

You can discuss about Simple File Upload in Admin [here](https://github.com/datenstrom/yellow/issues/130)

**Comment by BsNoSi** [comment]
Did you test different browser? I Tried (quick and dirty…) with Firefox and it did not work.

**Comment by nibreh** [comment]
Hello. It's not clearly a user friendly plugin.

Did you replace `localhost` [line 6 from upload-attachment](https://github.com/nibreh/yellow-plugin-inline-attachment/blob/master/upload_attachment.php#L6) in `/media/images` with your own domain ? 

Also, if your yellow CMS is installed in a subfolder, I think you must do somes changes [line 118 in inline-attachment.js](https://github.com/nibreh/yellow-plugin-inline-attachment/blob/master/inline-attachment.js#L118)

I tried only with Firefox 50, Linux working fine for me.

**Comment by nibreh** [comment]
**Edit:** After tested, it's not necessary to change the line [line 118 in inline-attachment.js](https://github.com/nibreh/yellow-plugin-inline-attachment/blob/master/inline-attachment.js#L118) when your Yellow is in a subfolder. Just only if you decide to change the path of `upload_attachment.php` who is `/media/images`.

Also, maybe there is a trick in php to automaticcly check the domain / subdomain for

`$onlinePath = 'http://localhost/media/images/';`

If someone can help me to make this more friendly, and test the plugin in different browsers.

**Comment by nibreh** [comment]
I made some changes. Now you don't have to config your domain in `/media/images/upload_attachment.php`. Thanks to `$_SERVER['SERVER_NAME']`.

Installation is now user friendly.
