### ISSUE TITLE
problem with the plugin markdown editor

### ISSUE THREAD

**Issue by BogusCurry** [datenstrom/yellow#220]
Hello ;D
Since the last update, I see on my site the editor (plugin markbar), but on another site not. Becomes no error messages, but I must random log in, when I will edit my site.

I hope you understand me ;D

Have a nice Day ;D

**Comment by markseu** [comment]
Hello Bogus and thank you for the Nikolaus surprise. 😄 

Try to install latest version of @nibreh's [markbar plugin](https://github.com/nibreh/yellow-plugin-markbar), maybe you have an old one.
Which [version of Yellow](https://github.com/datenstrom/yellow-plugins/tree/master/core#how-to-use-the-core) and plugins are your using?

**Comment by BogusCurry** [comment]
Hi Mark ;D
The Version of Yellow is the actual 0.6.6, ok I will test the plugin and will then feedback ;D

Have a nice Day ;D

**Comment by BogusCurry** [comment]
Thanks for Fix ;D Thats had fixed my problem ;D

Have a nice Day ;D

**Comment by markseu** [comment]
Good to hear. Feel free to close this issue when it works for you.
