### ISSUE TITLE
How do I set nginx "server_name" at local host

### ISSUE THREAD

**Issue by hysonlee** [datenstrom/yellow#225]
My local nginx conf set as below:
```server {
listen 80;
server_name localhost;
...
```
the site running normal fine, but when I visit via IP and click "Edit" the page will goto `http://localhost/edte/` . How do i set the `host_name` value?

Yellow already update to v.0.6.7, PHP version is 7.0.14

many thanks!

**Comment by markseu** [comment]
I am afraid to say that I am not a big help with Nginx. Can you test it with Yellow 0.6.8?
