### ISSUE TITLE
Can I the blogsite set as startsite ?

### ISSUE THREAD

**Issue by BogusCurry** [datenstrom/yellow#226]
Hello ;D

Can I the blogsite as startsite or how I can embed the feed of the blogsite in my startsite ?

Have a nice Day ;D

Bogus

**Comment by nibreh** [comment]
Hello

1. Did you mean you want `mysite.com/blog` to be your home page at `mysite.com` ? Take a look [at the README](https://github.com/datenstrom/yellow-plugins/tree/master/blog#how-to-use-a-blog). Just delete the `1-home` folder.

2. Or if you want to embed the feed from `mysite.com/feed` generated with the [Feed plugin](https://github.com/datenstrom/yellow-plugins/tree/master/feed), just add `Template:feed` to your page.

```
---
Title: MyPage
Template: feed
---
```

I hope this can help you.

**Comment by BogusCurry** [comment]
I would test it ;D

Thanks you ;D

Have a nice Day;D
