### ISSUE TITLE
How I can sort the blogposts, so that the last post is on the top ?

### ISSUE THREAD

**Issue by BogusCurry** [datenstrom/yellow#227]
Hello there ;D

I have make a blogpost, but the post is not on the top. How I can this make, so that the last post is on the top ?
Here my blogsite ;D
http://www.pinguinsreisen.de/edit/blog/

Have a nice Day ;D
Bogus

**Comment by schulle4u** [comment]
Looks like the date of the post is wrong. The first entry I can see is from august 1th, 2017. Check the head section in your blog pages, usually dates are formated as `yyyy-mm-dd`, e.g. january 22th 2017 would be `2017-01-22`

HTH
Steffen
