### ISSUE TITLE
Clarification: possible to access images inside a page folder?

### ISSUE THREAD

**Issue by geoffyuen** [datenstrom/yellow#229]
Example: `/content/sample_page/` contains a `page.txt` and a bunch of images. Is it possible to display these images or do they have to be in the `/media/images/` folder?

Reason: I would like to have my pages more self-contained like Kirby or Stacey.

**Comment by BsNoSi** [comment]
It is possible, to create a structure `/media/images/page1/…` for all images of `page1.txt`. A folder for each page will lead to the requirement of redesigning the menu concept, because folder are the main element of menu organisation of *yellow*.  (Mark may correct me,…)

**Comment by markseu** [comment]
I am sorry, images inside a `/content/` folder are currently not supported.
