### ISSUE TITLE
How to change the font in Yellow

### ISSUE THREAD

**Issue by AlexL777** [datenstrom/yellow#233]
Hello Developers,

I would like to make the font in my yellow blog at http://wpzweinull.ch/cms/yellow a bit stronger and thicker. How can I change the font?

Thanks in advance.

**Comment by AlexL777** [comment]
Thanks, have just implemented. So is much more readable and better 👍

**Comment by nibreh** [comment]
Hi @AlexL777 

This is really simple, it's just about some adjustment in your CSS file in `/system/themes/assets` (Yellow 0.6.8). Change the `font-weight`.

Take a look at this tutorial: https://developer.mozilla.org/en/docs/Web/CSS/font-weight

Cheers

**Comment by AlexL777** [comment]
Thanks!

**Comment by markseu** [comment]
Feel free to close this issue when it works for you.
