### ISSUE TITLE
Made with Datenstrom Yellow

### ISSUE THREAD

**Issue by richi** [datenstrom/yellow#236]
Maybe it is time for a "Made with Yellow" page. Not everybody is watching twitter :)

I will start with three pages I did using Yellow and that have left "beta status".

http://www.emuseum-tettnang.de
http://www.ulrike-kurz.de
http://www.shortware.eu

**Comment by BogusCurry** [comment]
Hello ;D
Nice site ;D Is good to see what I can make with yellow ;D Yellow is a young project, with nice features ;D
-----------------------------------
Hallo ;D
Schön zu sehen, was man so alles machen kann mit Yellow. Habs auch erst versucht, aber dann doch abgebrochen. Hab aber vor es nochmals zu versuchen ;D Finde Yellow hat gute Features ;D

Bye

Bogus | Pinguinsreisen.de

**Comment by martinconzelmann** [comment]
Hallo zusammen, 

keine schlechte Idee, so eine Ideensammlung - ich mache dann mal mit ;) #madewithyellow

[TA17.DE](https://www.ta17.de)
[Röser & Bönsch sind keine Band](https://www.roeserboensch.de)
[Taja Metzen Immobilienvertrieb](https://www.metzen-immo.de)

Zur Info: bei Strato gibt es Probleme mit dem Kontakt-Formular, weil man SMTP-Login-Daten übergeben muss. Ich arbeite im Moment an einer Implementierung des [PHPMailers](https://github.com/PHPMailer/PHPMailer) als Yellow-Plugin. Wir hier veröffentlicht, wenns fertig ist... ;)

Schöne grüße, Martin

**Comment by BsNoSi** [comment]
Hi,

The TWITTER tag is not that meaningful for me (s.o. „not everybody is watching twitter“), but I can add some German pages to the list here:

- [oederwegffm.de](http://www.oederwegffm.de) - A portal for shops in a street in Frankfurt/Main/Germany.
- [blog.nosi.de](http://blog.nosi.de) - My blogging site
- [BUOA.DE](http://buoa.de) - A "swiss army knife toolbox" of mine
- [arzt-simon.de](http://arzt-simon.de) - A simple homepage for a doctor's office (my brother, content in progress)

There are some more "in queue", but because of lack of time, there is no time table for release.

Currently, I have a feed plugin for Yellow on my stack – since … i don´t know :( –, to upgrade my homepage to Yellow.

Have a nice day!

**Comment by martinconzelmann** [comment]
Well done! I like the Hamburger Menu on your blog! :)

**Comment by BsNoSi** [comment]
@Martin: I have a „raw package“, lack of time prevents the setup for a „true Yellow theme“. If interested, I can send it to you.

**Comment by M8inC** [comment]
@BsNoSi: Das wäre super! Wärst Du so nett und schickst es mir an mc _at_ conzi _dot_ com? Danke, Martin

**Comment by BsNoSi** [comment]
Hi Martin,

I'll forgetful, I uploaded it month ago to github: https://github.com/BsNoSi/yellow-burger-menue

As far as I can see, it can be updated without error to the current version. The Burger Menu does not recognize the „edit“ state – I had no time to fix this.

**Comment by nasendackel** [comment]
Hi, nice Idea...

My Blog is made with yellow:

[https://www.nasendackel.de](https://www.nasendackel.de)

**Comment by JanYellow** [comment]
@nasendackel: Meanwhile, there is probably WP ;-)

It would be nice if more users would introduce their pages here. I just discovered Yellow for myself and I'm still testing something on my local webserver (XAMPP). I like yellow Thanks to all who work on it!

**Comment by richi** [comment]
Local Artists

http://startup-tettnang.de

:)

**Comment by Rustapo** [comment]
Hello, I like this YELLOW CMS!

I need help creating a template for site on this CMS.

**Who will be able to create the template as per site-sample?**

(Ready to pay)

![photo5197414129495812406](https://user-images.githubusercontent.com/27696036/40480779-ed108c3c-5f68-11e8-9b97-50d543d4c3ed.jpg)
![photo5197414129495812404](https://user-images.githubusercontent.com/27696036/40480780-ed6d37ac-5f68-11e8-88a0-3fca565a1c84.jpg)
![photo5197414129495812405](https://user-images.githubusercontent.com/27696036/40480781-edc977d8-5f68-11e8-9081-2699d6484b52.jpg)

**Comment by hurzelchen** [comment]
www.pfingswallfahrt.de

**Comment by BsNoSi** [comment]
> [www.pfingstwallfahrt.de](http://www.pfingstwallfahrt.de)

Ich würde noch einen Datenschutz-Hinweis ergänzen.

Die Galerien würde ich nochmal sorgfältig durcharbeiten. Zwar gibt es da durchaus [Lösungen und Freiheiten](https://www.cr-online.de/blog/2018/05/12/beispiel-veranstaltungsfotos-warum-es-nach-der-dsgvo-oft-sinnvoll-ist-auf-einwilligungen-zu-verzichten/) bei der Bildwiedergabe. Doch es herrscht keineswegs ein alles erlaubendes „öffentliches Interesse“ bei Bildern von Veranstaltungen. Kinder im Vordergrund, Alkohol-Konsumierende, Bilder Einzelner ohne zwingenden Kontext zur Veranstaltung oder als Portrait würde *ich* aus (öffentlichen) Galerien aussortieren.

**Comment by schulle4u** [comment]
@BsNoSi 
> • The contacts ("Kontaktdaten") of details pages are created with a plugin that combines available information to a formatted output, including link to (external) google map and legal notice for external links generated with it. [...]

I'd be interested to have a closer look at this plugin. Could it be used to create a kind of team members pages?

**Comment by BsNoSi** [comment]
The "adr" plugin (→ contacts) simply formats given text in a standard way:

     [adr who street city phone website e-mail-adress slogan fax] 

creates

```
Kontaktdaten
who
slogan
🖉street
 city
⚑In GoogleMaps anzeigen
℡phone
℻fax
➦website
✉e-mail-adress
Das Nutzen externer Links erfolgt auf eigene Gefahr.
Sie sind kein Bestandteil dieser Webseite(n).
```

Depending to my css it may look like this

![adr](https://user-images.githubusercontent.com/2784683/49864462-ce570800-fe02-11e8-8186-2cb1cdd476f5.png)

There is no check if the e-mail adress or website is valid or the adress leads to a suitable display in Google Maps. The input order follows the *mostly used* data.

Currently it is "German only". For general usage it has to be improved in a few places and an installer whould be nice.

**Comment by sukmabudi** [comment]
https://prikitiew-adventure.com/blog/

Powered by ~~CMS~~ FunMS Yellow with Stockholm theme and responsive menu based on simple-nav by @obscuredetour just copy this file into plugins folder: [respnav.zip](https://github.com/datenstrom/yellow/files/2824775/respnav.zip)

To activate just insert `<?php $yellow->snippet("respnav-snippet") ?>` somewhere after `<BODY>`
To change the **custom link** just edit `resnav-snippet.php` in snippets folder
The logo.png (50x50px) place in `system/themes/assets/`

**Comment by thumos333** [comment]
[www.presence.msk.ru](http://www.presence.msk.ru)

My homepage, almost entirely in Russian. It mostly features translated texts on Buddhist meditation. Works entirely on Yellow.
