### ISSUE TITLE
Support for variable page slugs? 

### ISSUE THREAD

**Issue by eli-oat** [datenstrom/yellow#239]
By default yellow seems to use a pages title as its url slug, e.g. `title = about` generates the url website.com/about

Is there anyway to change a page's slug? 

I'm particularly interested in the context of blog pages. I'm looking to include the post's date in the url, e.g. website.com/2017/03/22/title

**Comment by BsNoSi** [comment]
What is the reason for this? I can not see any advantage over the current technique.

**Comment by eli-oat** [comment]
This is a standard url pattern for blog posts. See Jekyll, Wordpress, Cactus, etc. 

The primary reason I see for it being useful is that it helps prevent potential url collisions in larger blogs, especially those with multiple contributors.

**Comment by BsNoSi** [comment]
The fact that older systems use a similar approach for url addressing does not automatically make this method a better one.

Yellow adds by itself the date to the filename. If accidentally "same time, same title" happens, Yellow handles this by adding 2,3,4,… . This notifies to the author, that someone else has the same title on the same day – possibly a reason, to rethink it?

I consider it as a huge advantage that yellow *does not behave* as the enumerated systems.

**Comment by eli-oat** [comment]
To clarify — I'm not advocating for a wholesale change to yellow, just wondering if there is a way to support this different behavior.

**Comment by BsNoSi** [comment]
I didn't want to attack you with my comment – if that's what happened: Excuse me. 

I love the stringent addressing of Yellow. For me as a person, an address without many subdirectories is more readable and therefore more concise. The sub-directories have no (relevant) information value for me, an address tweeting with many subdirectories may then cut off the "exciting part", namely the title in the address.

Technically, there is (meanwhile) no need for a bunch of subdirectories. and if the technical limit is reached, it should be the job of the system, to handle that.

**Comment by markseu** [comment]
I think Yellow should offer this kind of flexibility. A system that can be adjusted to people's needs.

At the moment there are technical limitations that prevents you from using the date in the URL. The blog plugin only supports files in a single folder. If people wants to include more information in the URL, such as the publishing date, then plugins have to work across multiple folders and this means some redesign in Yellow's content handling. I can't promise anything, but will have a look what I can do.

**Comment by eli-oat** [comment]
Thanks @markseu and @BsNoSi! 

I agree that the subdirectories are a clumsy solution to handling this. I am not 100% certain, but I think wordpress handles this sort of thing using a rewrite (granted, that use case is different to Yellow, since the content is being pulled from a database, rather than flat files). 

Rather than add subdirectories, e.g. `website.com/2017/03/29/content/` what about optionally appending the date to the content title for blog posts, e.g. `website.com/2017-03-29-content-title/`?

**Comment by markseu** [comment]
I don't mind if machines do more work, so that humans don't have to. 

Let's investigate the possibilities? I can think of postfixes, prefixes, subfolders and identifiers. Postfixes and prefixes are pretty common. Subfolders have both advantages and disadvantages, but they could come handy for all sorts of categorisations. With identifiers I mean that the CMS automatically adds a short unique ID, should the same title be used more than once.

From the following URL formats, which ones would you use?

1. website.com/article-date		: `website.com/made-for-people-2017-03-01`
2. website.com/date-article		: `website.com/2017-03-01-made-for-people`
3. website.com/date/article		: `website.com/2017-03-01/made-for-people`
4. website.com/year/article		: `website.com/2017/made-for-people`
5. website.com/article		&nbsp; &nbsp; &nbsp; &nbsp; &nbsp;: `website.com/made-for-people`
6. website.com/article-id	&nbsp; &nbsp; : `website.com/made-for-people-2`

**Comment by eli-oat** [comment]
For my use cases (I currently use Yellow for my [personal website](https://eli.li/), but I'm interested in starting to use it for client work, too), I think that 5 should remain the default, but I would certainly use options 4 or 3 if they were available. 

I think this could also be a great way to handle tags, `website.com/tag/article`

**Comment by BsNoSi** [comment]
`website.com/tag/article/` is not unique. How do you handle pages with more than one tag (what is quite usual)?

Something like `website.com/yyyy/mm/article` may be interesting for diaries.

Grouping, as currently done (`website.com/folder/article`) is close to `tag` grouping, possibly there is some subgrouping required (did not test this, I think, it should/would work).

**Comment by eli-oat** [comment]
@BsNoSi that is a good point about multiple tags. 

I've seen it work 2 ways in different places

1. A folder for each tag, with duplicate content across multiple folders
2. Each tag is nested in the previous, usually alphabetically. 

Neither option is perfect, though. Each has its issues.

**Comment by BsNoSi** [comment]
Duplicate content is critical: 

- How do you handle partial modifications – worst case scenario – of two editors at the same time? This requires a rights management overhead, that isn´t currently part of Yellow (and hopefully never ever will be implemented). 
- How do you handle the knowledge about duplicated content (equally same challenge as with two editors).

I think, it is cleaner and you can do it right away with Yellow, if you create folder („main tag“) with the content that matches there best and add your second, third,… tag, that will match on tag search (tag:xxx). This creates your „main tag folder adress“ without any requirement of copy and paste.

**Comment by markseu** [comment]
I am playing with different ways of improving the content handling. I think there are currently just two plugins that operate in a single content folder, the wiki and the blog. If we can find something that offers more flexibility to users, while keeping the simplicity, then this should benefit both plugins.

**Comment by markseu** [comment]
Just in time before Midsommar...

Now Yellow offers more flexibility for websites. The default behaviour is creating new pages in the same folder, as it has always been. But you can change this in your own blog. It's no problem if you would like to include publishing date in the URL. Tested with Yellow 0.7.1.

**URL with full date**, for something like website.com/2017-03-01/made-for-people

Open file `system/config/config.ini` and add:
```
BlogLocation: /
BlogNewLocation: /@date/@title
```

Here's an example `content` folder:

![screenshot-1](https://user-images.githubusercontent.com/2429165/27443244-b6802942-5772-11e7-9f33-05a1a4063300.png)

**URL with subfolder for each year**, for something like website.com/2017/made-for-people

Open file `system/config/config.ini` and add:
```
BlogLocation: /
BlogNewLocation: /@year/@title
```

Here's an example `content` folder:

![screenshot-2](https://user-images.githubusercontent.com/2429165/27443257-c135b244-5772-11e7-864e-068f832d038b.png)

Hope this is what you are looking for.
