### ISSUE TITLE
Ticker RSS parser

### ISSUE THREAD

**Issue by schulle4u** [datenstrom/yellow#240]
[Ticker](https://github.com/schulle4u/yellow-plugin-ticker) is a RSS parser plugin for yellow. It uses the `simplexml_load_file` function of php, so there's no need for 3rd party classes.  
Inspired by code from [Webdesign Weisshart](https://webdesign.weisshart.de/rss2html.php)

Feel free to test and comment, I'll add it to the plugin list if nothing critical happens outside my playground.

**Comment by nibreh** [comment]
Nice, working fine with xml.

Do you think there is a way to use with atom files ? Like Diaspora feeds. 

Thanks

**Comment by schulle4u** [comment]
Currently atom feeds are not supported, but shouldn't be to difficult to implement. I'll try to add support for such feeds.

**Comment by schulle4u** [comment]
*headdesk* It seems that simplexml is not very comfortable in handling namespaces, so atom feeds in deed are a little tricky to implement. I'll have an eye on this, but currently I just added basic error handling to avoid parser errors when an unsupported feed is given.

**Comment by schulle4u** [comment]
@nibreh: I've added support for the [SimplePie parser](http://simplepie.org) wich can handle atom feeds and also has caching capabilities. Currently SimplePie is not bundled and the plugin still uses simplexml by default, I might change this at a later time depending on user feedback. Here's howto download and install SimplePie for yellow (shell access with php and git required, not necessarily on the same machine wich yellow is running): 

1. Create an empty directory. 
2. `git clone https://github.com/simplepie/simplepie.git`
3. `cd ./simplepie`
4. `php build/compile.php`
5. This will create the file `SimplePie.compiled.php` in the source root directory. 
6. Copy/upload `SimplePie.compiled.php` into yellow's `system/plugins` folder.
7. In the same folder, create an empty folder called `cache` and make it writable. 
8. Add `tickerAdvancedParser: 1` to your `system/config/config.ini` and update `ticker.php` to the latest version. 

Hope this helps.

**Comment by BsNoSi** [comment]
Hey Steffen, 

well done. While I was thinking about, how to, you did it. Thanks.

„feature request“: it would be nice to have an optional transfer of a css class to the ticker, compareable to image plugin:

```
[ticker http://example.com/feed.xml 5 theclass]
```
This should lead to

```
<div  class="theclass">
<ul>
<li>…</li>
…
</ul>
</div>
```

This allows individual handling of different ticker entries.

Instead of adding this myself, it seems to me as a better solution, that you have the full control over your plugin.

**Comment by schulle4u** [comment]
Thanks for the valuable feedback @BsNoSi, I'll have a look into your request after my radio show this evening. Sometimes I'm neglecting design features in my work. I'm a blind user and therefore my websites and plugins are text-oriented and probably never will win a price for the best design. :)

**Comment by schulle4u** [comment]
@BsNoSi, please try the latest plugin update, ticker sections now should be able to style individually. Just add a class name as 3rd parameter to your ticker shortcode.

**Comment by BsNoSi** [comment]
I tried [in my blog](http://blog.nosi.de/edit/weitere/) – you are too fast ;)  I must adjust the classes tonight … .

**Comment by schulle4u** [comment]
Added to [the list of plugins](https://github.com/datenstrom/yellow-plugins/blob/master/README.md).
