### ISSUE TITLE
Simple Area Log in?

### ISSUE THREAD

**Issue by BsNoSi** [datenstrom/yellow#241]
What is the best way to achieve something like this with Yellow:

```
landing page (open)
subpage (open)
subpage2 (protected-a)
subpage3(protected-b)
```

where "protected" means, that there is an embedded log in "on page" for autorized users.

I think, a simple .htaccess is sufficient in most cases, I did not think about creating logins for areas or changing passwords, but this will be neccessary, I know.

**Comment by schulle4u** [comment]
Have a look at #132, the 3rd comment looks interesting.

**Comment by BsNoSi** [comment]
Thanks for this hint. Is not directly, what I am thinking of, but it points in the right direction.

I must improve my PHP skills really urgent...

**Comment by markseu** [comment]
I currently use the [draft plugin](https://github.com/datenstrom/yellow-plugins/tree/master/draft) as a quick & dirty solution. For example pages that should be available only to the internal team will be marked `Status: draft`. Team members have to log in to read them. Web master can make these pages read-only by restricting user accounts, see security configuration. 

Just an idea. 😄
