### ISSUE TITLE
Responsive Yellow Blog Style {Demo}

### ISSUE THREAD

**Issue by bloggerwebmaster** [datenstrom/yellow#244]
Thanks to yellow cms, I've done some modifications on this script.It's a very good cms. Very appropriate that will be used as another option to the of wordpress cms alternative.

![responsive-yellow-cms](https://cloud.githubusercontent.com/assets/27368312/24973131/e6c32c84-1fe7-11e7-9bd9-0a5d67838f82.png)

See my yellow mod cms here: [Click Link](http://bloggerwebmaster.com)

**Comment by AlexL777** [comment]
Looks very well from this new theme. Can you use it for free in the future or do you want to offer it for a fee?

**Comment by bloggerwebmaster** [comment]
Yes, with a little donation least I will feel that my efforts are appreciated by others.

**Comment by AlexL777** [comment]
OK thanks. Yes, you are also right and I come back to this theme. This could very well fit into my Yellow blog.

Is the theme compatible with Yellow 0.6.9 and can you offer this theme now or is it still further developed?

**Comment by bloggerwebmaster** [comment]
Yes this compatible with Yellow 0.6.9. You will use it in a old yellow cms or install a new one?
You should know that some of the functions on the old post will not work on this theme, eg. image post thumbnail.

**Comment by AlexL777** [comment]
Hi,

Something a pity, but I have to see if I delete or keep my old Yellow installation. Maybe a new Yellow CMS blog floats on a subdomain. Then I ask you again about the theme and can then donate some money to you. The theme looks cool and worth seeing, and main feature, it works with the yellow plugins. Then that would suit me.

**Comment by bloggerwebmaster** [comment]
It works with all Yellow plugin. If you want to see how this works, you can send a donation to me whatever you like. I will send this to you and will give full support if you run into problems.

**Comment by AlexL777** [comment]
OK, to which Paypal address should I donate? I wait just a bit until one of my customers paid by PayPal. Then I can donate to you and look forward to the premium theme.

**Comment by JanYellow** [comment]
The link in the creator's post is dead!
