### ISSUE TITLE
Change title "Blog"

### ISSUE THREAD

**Issue by masfur** [datenstrom/yellow#247]
Is it possible to change title "Blog" on my site?

**Comment by BsNoSi** [comment]
Without knowing details of your setup: try changing entry „Sitename“ in `config.ini`

**Comment by masfur** [comment]
Thank you for your reply. No did not change.
I try this: I duplicated directory called "Blog" and I renamed it with "New".
if I do this, the system allert me with"File Not Found".
It seems that the name of directory should be 9-blog (or 4-blog, etc), and the title of page.txt file should be "Title: Blog".
Sorry for my english!
Thank you

**Comment by BsNoSi** [comment]
Please, be a little bit more precise: which title do you mean:

- The main title on each page? 
- The title in menu entry?
- …?

**Comment by masfur** [comment]
The title in the menu entry.
![kapt](https://cloud.githubusercontent.com/assets/8803971/26499773/0cf6efa8-4234-11e7-92f6-b5d47f920546.PNG)

**Comment by BsNoSi** [comment]
I see. Create a file `page.txt` in blog folder with this entry:

```
---
title: Whatever you want for your title
---
```
This should solve this challenge.

**Comment by masfur** [comment]
Very good.
Thank you.
