### ISSUE TITLE
Site with two blog pages

### ISSUE THREAD

**Issue by masfur** [datenstrom/yellow#248]
Is there a possibility to have two pages with the blog template?
I tried duplicating the directory but it does not work.
It can be done?
Thank you.

**Comment by nibreh** [comment]
Do you want to have multiple blogs on your website ?
Take a look here: https://github.com/datenstrom/yellow/issues/108#issuecomment-145797637

**Comment by masfur** [comment]
Perfect! Thank you a lot!
And... If I want to put some description at the beginning of first blog page?

**Comment by markseu** [comment]
I am sorry, this is currently not possible. The blog plugin is rather simple and doesn't support descriptions. If you are a developer you can customise your templates and snippets. You have full control over the HTML code. Have a look at [customising templates](https://developers.datenstrom.se/help/customising-templates).
