### ISSUE TITLE
Static build fails

### ISSUE THREAD

**Issue by zetalevel** [datenstrom/yellow#249]
host:/opt/lampp/htdocs/test/yellow-master$ php yellow.php build /opt/lampp/htdocs/test/yellow-master/static
PHP Fatal error:  Uncaught Error: Call to undefined function mb_internal_encoding() in /opt/lampp/htdocs/test/yellow-master/system/plugins/core.php:3366
Stack trace:
#0 /opt/lampp/htdocs/test/yellow-master/yellow.php(8): require_once()
#1 {main}
  thrown in /opt/lampp/htdocs/test/yellow-master/system/plugins/core.php on line 3366
host:/opt/lampp/htdocs/test/yellow-master$

**Comment by markseu** [comment]
Thanks for the bug report.

Which operating system do you use?
Which PHP version do you use?

**Comment by zetalevel** [comment]
PHP 7.0.18
Ubuntu 17.04

**Comment by markseu** [comment]
It looks like the `mbstring` extension is missing or not enabled. Here's how can install it:

`sudo apt-get install php-mbstring php7.0-mbstring`

If it's still not working, you might need to enable it manually:

`sudo phpenmod mbstring`

Hope this helps. 😄

**Comment by zetalevel** [comment]
Yes install of mbstring resolved the problem. Tack så mycket!

**Comment by markseu** [comment]
Good to hear. I added a better error message to Yellow, to help people with the installation.

Let us know if you find more bugs.
