### ISSUE TITLE
Search in specific folder

### ISSUE THREAD

**Issue by nibreh** [datenstrom/yellow#253]
Hi.

Is there a way to search in a specific folder, and not on the entire site with [search plugin](https://github.com/datenstrom/yellow-plugins/tree/master/search) ?

**Comment by BsNoSi** [comment]
See description of plugin:

```
The following settings can be configured in file system/config/config.ini:

SearchLocation = search location
SearchPaginationLimit = number of entries to show per page
SearchPageLength = maximum page length to show
```

Simply set `search location` as desired.

**Comment by markseu** [comment]
The search plugin does search through the entire website.

To give you an alternative, you can make a custom plugin and then tell it to search a specific folder. Replace `$this->yellow->pages->index($showInvisible, false)` with `$this->yellow->pages->find("/foldername/")->getChildren(showInvisible)`. For more information see [API](http://local.datenstrom.se/user/mark/help/api#yellow-pages).

Hope this helps. :smile:
