### ISSUE TITLE
wrong location of theme folder after installation

### ISSUE THREAD

**Issue by oliworx** [datenstrom/yellow#257]
After installing on a webserver, the css was not found.
This is because it is requestet at `media/themes` but alle the assets are in `system/themes`

So I had to copy the themes folder to the `media` folder to fix it.

**Comment by markseu** [comment]
That's on purpose, direct access to the system folders is never allowed.
Files needed for plugins and themes are mapped via `media` locations.

My guess is that something else is not working.

Which operating system do you use?
Which web server do you use?

**Comment by oliworx** [comment]
It is a shared webhosting at the German provider 1&1 running on Linux, Apache and php 5.6.
I can send you the output of `phpinfo()` if it helps.
And all the links are broken here: http://demo-a.usc-muenchen.de

The `.htaccess` file mentions a `cache` folder, but there is no such folder in the repo, would I have to create one?

**Comment by markseu** [comment]
Thanks for the information, I checked your links.

At the moment your "About" page shows an "Internal Server Error". Well, it looks like the rewrite module for Apache is not properly working on your web server. Once this is configured, your CSS files should work. Can you check with your webhosting provider?

About the `cache` folder, it's an optional feature, you don't have to create one.

**Comment by oliworx** [comment]
I tried another installation with PHP 7.1 and file permissions 777 but the same result:

http://demo-b.usc-muenchen.de/

**Comment by oliworx** [comment]
OK, thank you for the hint!
I added `RewriteBase /` to the .htaccess file and now it works like a charm :)

**Comment by markseu** [comment]
Good to hear you could make it work.  👍 

I didn't know this was needed for installing Yellow in a subdomain. Finding the right RewriteBase to the configuration file apparently fixes most web server problems. If more people run into this problem, we should update the documentation. 

Thanks Oliver.
