### ISSUE TITLE
Can not display JSON Code with Backticks in Yellow Blogpost - what to do?

### ISSUE THREAD

**Issue by AlexL777** [datenstrom/yellow#259]
Hi Developers,

I have written a tutorial on Shariff Share Buttons for Yellow, how to integrate them manually including PHP backend.

Now I wanted to display the JSON code with Markdown. Unfortunately it does not work with backticks or 4 spaces.

The code is as follows.

    ```<div class="shariff" data-backend-url="/url-zum-backend" data-services="[&quot;facebook&quot;,&quot;googleplus&quot;,&quot;twitter&quot;,&quot;pinterest&quot;,&quot;xing&quot;]" data-theme="standard" data-
    orientation="horizontal"></div>```

How can I do it if I want to display the code in the blog post in Yellow? It's actually "class =" shariff "and Shariff Backend is installed on the blog. Maybe it's because, but usually it has to be possible with the code display.

This was the last time I noticed that this does not work.

Who can help?

Thanks in advance.

**Comment by schulle4u** [comment]
Just add a line break after the opening and before the closing backticks. 

````

```
<div class="shariff" data-backend-url="/url-zum-backend" data-services="[&quot;facebook&quot;,&quot;googleplus&quot;,&quot;twitter&quot;,&quot;pinterest&quot;,&quot;xing&quot;]" data-theme="standard" data-orientation="horizontal"></div>
```

````

Works for me, [here is an example](https://www.robbenradio.de/home/code-test)

HTH
Steffen

**Comment by AlexL777** [comment]
Thanks @schulle4u  ,

I will try it with the second tutorial and I was unfortunately not sure with the backticks.

But you showed me that it works 😄
