### ISSUE TITLE
update error

### ISSUE THREAD

**Issue by oscott** [datenstrom/yellow#262]
Hello, When I add a plugin zip to the plugin folder, I get the following message as soon as I refresh any page. (running latest version, even happens with a fresh install with no content or themes taken from my old install.) After a couple of trys, I did a fresh install and went to settings and clicked to update and got the same:

    Fatal error: Call to undefined function opcache_reset() in /home/koept/public_html/os/system/plugins/update.php on line 297

Any ideas? I've tried some variations on permissions. have I missed a prerequisite of some sort? Thanks Oliver

**Comment by oscott** [comment]
ok - fixed it - manually installed the latest update plugin. Thanks - got info from...

 #256 https://github.com/datenstrom/yellow/issues/256#issuecomment-311893898

**Comment by markseu** [comment]
Out of curiosity, which PHP version did you use?

**Comment by oscott** [comment]
I was on 5.4.x (not sure) earlier today and I updated to 5.6.24 a bit later. It may have taken a while to take effect? That might have been what did it - would you like me to revert my php version or do any tests? Yellow is brilliant and I'm no php expert, but love to help such a good cause. thanks.

**Comment by markseu** [comment]
Thanks, all should be fine now. Let us know if something else isn't working. Bug reporting is much appreciated.
