### ISSUE TITLE
Yellow opens only a blank site after Install

### ISSUE THREAD

**Issue by ChristianK89** [datenstrom/yellow#263]
I have only an blank Site after installing and opening yellow.

I have apache2, mod rewrite enabled and php 5.6. But I cant get yellow running. Whats my fault?
Running it on Debian 8.

**Comment by markseu** [comment]
Not your fault. My guess is that you need to adjust your mod_rewrite configuration.

What's the URL of your website?
So you see any errors in the the web server logfile?

**Comment by ChristianK89** [comment]
The URL is http://christiankuhn.org/ and i dont see any logs or failures... Mod Rewrite is on...
other cms systems which needs mod rewrite too works properly such as kirby or grav or wordpress... Only yellow doesnt...
`root@christiankuhn:/home/christian# a2enmod rewrite
Module rewrite already enabled`

![bildschirmaufnahme vom 2017-07-06 16 56 47](https://user-images.githubusercontent.com/29486808/27917395-25dbffba-626c-11e7-8f2a-53100a3fd87f.png)

![bildschirmaufnahme vom 2017-07-06 16 57 38](https://user-images.githubusercontent.com/29486808/27917428-3f473618-626c-11e7-9578-fd718ebbe4af.png)


What do you suggest?

**Comment by markseu** [comment]
Strange, I don't get any response from your web server.

[Send me an email](https://datenstrom.se/contact/), if you want me to have a closer look.

**Comment by ChristianK89** [comment]
Done

**Comment by markseu** [comment]
Thanks for reporting this bug. 

Apparently PHP doesn't allow it when a class that inherits from another is declared before the parent class. This works without problems on most systems, but not on a Raspberry Pi. Here PHP crashes and the Apache error log file shows `AH00052: child pid 1799 exit signal Segmentation fault (11)`.

I updated the Markdown parser. Should be working now.

**Comment by ChristianK89** [comment]
New fresh Install of Yellow will work :) Thank you for this great Support :)
