### ISSUE TITLE
Feature Request: Advanced User Rights Management

### ISSUE THREAD

**Issue by BsNoSi** [datenstrom/yellow#266]
I would like to return to the rights management of yellow (see #241 ).

Mark has referred to the draft plugin there. This is a good approach, but it does not meet a widely spread requirement: a registered user, allowed to access all pages, but with no rights for editing a.s.o. 

> Not logged in → read only → edit/change/delete/create (currently the only *logged in status)

I believe that a complex area user management is in most cases not needed. But something often required is *hiding dedicated information from the unspecified public*. Showing this including the option to chance it, goes to far.

Therefore, I want to place this as a feature request.

Best Practice would be:

1. Ask for a log in
1. Admin can approve with two links: as admin or as user
1. This is a flag in `user.ini`, that can be modified, if required.

Maybe, this can be achieved with the draft plugin in combination with hiding the edit(…) options?

**Comment by markseu** [comment]
Did you know that you can install multiple Yellow installations? 

This doesn't take up much disk space and gives you a lot of flexibility. You can install a different Yellow into a different subfolder. Now each subfolder has its own reign, its own rules, its own restrictions. If you want to show different customers different information, make a subfolders and create logins for them. 

Here are three different customers:

```
- content
- media
- system
- customers
   - anna
   - bsnosi        
   - wunderfeyd
```

Maybe this would work for you?

**Comment by BsNoSi** [comment]
A regular challenge is a usual website, with a "show only registered user area" with the same content. The Registration process of Yellow is quite simple and perfect for that, only the fact, that these users then have the option for edit/change/delete/… is against the use (currently).

This is a typical scenario i.e. for club sites, where there is a public area an an "internal" area, that shall be available for members only (but not editable).

**Comment by markseu** [comment]
How about writing your own plugin, see `onEditUserRestrictions` from the API?

There you could check if the current user matches a specific pattern. The event system allows you to extend features. For example check if `$users->getHome($email)=="/guests/"` and return `false`. This should in theory prevent the user from creating/editing/deleting pages, but I haven't tested it.

Hope this works better for you.

**Comment by BsNoSi** [comment]
This sounds interesting. As always, it is a challenge of having time – learning PHP first, to understand, what happens there. You may keep this feature request open, to remind myself … ;)

**Comment by markseu** [comment]
Let's change the topic then.

**Comment by markseu** [comment]
Here's an example. With help of the Yellow API you can control user restrictions. As fas as I understand you want a private members area, where normal users can edit pages, but restricted users can not edit pages. Tested with Yellow 0.7.1.

Create a new file `system/plugins/members.php`:

```
<?php

class YellowMembers
{
	const VERSION = "0.7.1";
	var $yellow;			//access to API
	
	// Handle initialisation
	function onLoad($yellow)
	{
		$this->yellow = $yellow;
		$this->yellow->config->setDefault("membersLocation", "/members/");
		$this->yellow->config->setDefault("membersStatusCode", "500");
	}
	
	// Handle page meta data parsing
	function onParseMeta($page)
	{
		$membersLocationLength = strlenu($this->yellow->config->get("membersLocation"));
		if(substru($page->location, 0, $membersLocationLength)==$this->yellow->config->get("membersLocation"))
		{
			$page->set("status", "members");
			$page->visible = false;
		}
	}
	
	// Handle page parsing
	function onParsePage()
	{
		if($this->yellow->page->get("status")=="members" && $this->yellow->getRequestHandler()=="core")
		{
			$this->yellow->page->error($this->yellow->config->get("membersStatusCode"), "For members only!");
		}
	}
	
	// Handle user restrictions
	function onEditUserRestrictions($email, $location, $fileName, $users)
	{
		return $users->getHome($email)==$this->yellow->config->get("membersLocation");
	}
}

$yellow->plugins->register("members", "YellowMembers", YellowMembers::VERSION);
?>
```

Go to your `content` folder and create a private members area: 

![screenshot](https://user-images.githubusercontent.com/2429165/28639896-1d2cb36c-724a-11e7-8b87-1257b78816d3.png)

Open your `system/config/user.ini` file and configure user accounts:

```
anna@demo.com: $2y$encrypted,Anna,en,active,946684800,0,none,/
bsnosi@demo.com: $2y$encrypted,VIP Member,en,active,946684800,0,none,/members/
wunder@demo.com: $2y$encrypted,VIP Member,en,active,946684800,0,none,/members/
```

Hope this is what you are looking for.

**Comment by BsNoSi** [comment]
Thank you for that sample. May solve my challenge. Currently, there is no time for it, but I will come back, when I have tested it.
