### ISSUE TITLE
Image backgound for entire site

### ISSUE THREAD

**Issue by masfur** [datenstrom/yellow#271]
Hi everybody!
I try to put an image-background in all site, put this in my pars-theme CSS:

body {
	background-color:#fff; color:#333;
	font-family: 'Roboto', 'Open Sans',Helvetica,sans-serif; 
	text-align: justify;
	font-size:1em;
	font-weight:300;
	line-height:1.6;
	background-repeat: no-repeat;
	background-image:url(logo4.png);
}
But not work.
Where I'm wrong?
Thank you.

**Comment by nibreh** [comment]
Hi.

Maybe the URL to your `logo4.png` is not correct. If your logo is in the `/media/images/` folder, you must use this `url('/media/images/logo4.png')`

Cheers.

**Comment by masfur** [comment]
Very good!
Thanks a lot!
