### ISSUE TITLE
$page->getDateHtml("published") problem

### ISSUE THREAD

**Issue by zynicum** [datenstrom/yellow#273]
My website location/language is German. I know, when dates are displayed on a page they are converted to a language specific date format.
In the file system/snippets/content-blogpages.php I need the HTML-Tag `<time>.`
My idea:
`<time datetime="<?php echo $page->getDateHtml("published","Y-m-d") ?>"><?php echo $page->getDateHtml("published") ?></time>`
The generated output is:
`<time datetime="[2017-07-25]">25.07.2017</time>`
But I need (**without the brackets**):
`<time datetime="2017-07-25">25.07.2017</time>`
How can I do this?

**Comment by markseu** [comment]
Hi, it looks like the API made this hard... there is no point to deny this. 

I suggest to split date handling into two separate function:

`<?php echo $page->getDateHtml("published") ?>` for a  language specific date (multiple formats).
`<?php echo $page->getDateFormattedHtml("published", "Y-m-d") ?>` for a custom date

If this looks good to you, please try the latest `system/plugins/core.php`.

**Comment by zynicum** [comment]
It works perfectly, thank you
