### ISSUE TITLE
Upgrading Yellow doesnt work

### ISSUE THREAD

**Issue by ChristianK89** [datenstrom/yellow#275]
Hello People,

If i would Upgrade Yellow i get this message:
Aktualisierung verfügbar, bitte an den Webmaster wenden.

**Comment by schulle4u** [comment]
Check your `system/config/config.ini` for the `email` setting. Either The address there is not set or it doesn't match the user's account email from which your trying to start the update. 

Steffen

**Comment by ChristianK89** [comment]
That was the fault 👍 Thank You 🥇
