### ISSUE TITLE
Search-plugin: missing search-button

### ISSUE THREAD

**Issue by zynicum** [datenstrom/yellow#278]
Hello, it's me again :)
Sorry for my English... I use the G..gle-Translator.
Search-Plugin:
If I use the snippet "content-search.php" for a separately site to search, it is ok.
But if I use the shortcut [search] in another site, there is no search-button! It is wanted or missing? I know, I have to use the Return-key to take a search...
I mean, it's still missing in the file "search.php" before line 32:
`$output .= "<input class=\"btn search-btn\" type=\"submit\" value=\"".$yellow->text->getHtml("searchButton")." />\n";`

**Comment by markseu** [comment]
Hello, 

the [search plugin](https://github.com/datenstrom/yellow-plugins/tree/master/search) was designed that way. If more people want to have a search field with button, we can change this. If you want a search field with button right now, you can use HTML and create your own. Here's an example content file:

```
---
Title: Example page
---
Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut 
labore et dolore magna pizza. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris 
nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit 
esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt 
in culpa qui officia deserunt mollit anim id est laborum.

<form class="search-form" action="/search/" method="post">
<input class="form-control" type="text" name="query" placeholder="" />
<input class="btn search-btn" type="submit" value="Search" />
<input type="hidden" name="clean-url" />
</form>
```

Hope this helps. 😄
