### ISSUE TITLE
Message of the day plugin

### ISSUE THREAD

**Issue by schulle4u** [datenstrom/yellow#279]
Motd, as an acronym for "message of the day", is a plugin to display specific text strings on each day of the week. I'm using this on a radio site to display a short teaser for upcoming shows on the current day. To use the plugin, you only need to define each daily message in your page metadata and put the `[motd]` shortcut where the message should be displayed. 

The plugin can be found here: https://github.com/schulle4u/yellow-plugin-motd

As always, Suggestions are welcome. :)

Steffen

**Comment by BsNoSi** [comment]
Hi Steffen,

nice idea. Some questions to think of (if you want ;) )

- Is it convenient, to include the messages in _each_ header, where you want to use them? If you want to use it more than once, it is hard to maintain.
- Is it may be more flexible and more interesting, to read the messages randomly from a file (with more than seven…)?
This avoids fatigue effects for regular visitors who recognize weekly repetitions.

**Comment by schulle4u** [comment]
Hi @BsNoSi, 

> - Is it convenient, to include the messages in _each_ header, where you want to use them? If you want to use it more than once, it is hard to maintain.

Maybe not, but putting the messages in global configuration variables seems not the best solution too. Imho content-related things should be strictly divided from system settings. Storing the messages in page metadata therefore was the easiest solution I came up with to first make things work. 

> - Is it may be more flexible and more interesting, to read the messages randomly from a file (with more than seven…)? 
> This avoids fatigue effects for regular visitors who recognize weekly repetitions.

Yeah, this is something I already was thinking of for future development, but not as a pure random selection. Currently my use case is a small internet radio site where a short text theaser for upcoming shows of each day should be displayed on the home page. The weekly shows are the same, but I surely could edit page.txt from time to time to slightly vary the messages or to integrate new shows. 

to make things a little more dynamic, my idea was to try to put some markdown text files into a folder and name them something like: 

```` 
motd1v1.txt
motd1v2.txt
motd1v3.txt
motd2v1.txt
motd2v2.txt
...
```` 

Whereas motd1 to motd7 represents the day of the week, and v1 to v...something is a randomly selected variation of the message. The advantage of this solution would be that you can use these messages globally and even parse other content such as images and media files. 
Easy task, tricky solution. I'm not the best coder and try to use the Yellow API as much as possible. This here sounds like another round of headdesking with stackoverflow. :)

Thanks for your input, I'll see what can be made of it. To be honest, I first wasn't sure if this plugin actually is worth a release as it currently is written for a rather special case. 

Steffen

**Comment by gdippe** [comment]
I like the simplicity of it! I tested it on my blog and it seems to work fine.  I'm thinking of using it for quotes connected to whatever the post is about.
Allowing `<br />` would be great to be able to write e.g.

“There are always two people in every picture: the photographer and the viewer.”
— Ansel Adams

**Comment by gdippe** [comment]
Yes, I know :) Unfortunately I'm a rather mediocre programmer (maybe I shouldn't even call me that) and cannot be of much help.

**Comment by schulle4u** [comment]
I just released a random page plugin as  addition or probably better solution for this plugin. See #286 for further details.
