### ISSUE TITLE
 Call to undefined method YellowToolbox::getMetaData()

### ISSUE THREAD

**Issue by gdippe** [datenstrom/yellow#284]
I'm stuck here after finally having to upgrade Yellow manually. If I leave the webinterface* files in the plugins folder editing etc works but the links look like [webinterfaceEdit] etc.
I get a blank page when I replace the webinterface* files with the new edit* files. In the Apache log file I get the below message.
Clearly I'm missing something but I cannot figure what! Help would be much appreciated!
PHP Fatal error:  Call to undefined method YellowToolbox::getMetaData() in /usr/local/www/data-dist/webbassocierade/luma/system/plugins/edit.php on line 932

**Comment by markseu** [comment]
The error message means the latest `system/plugins/core.php` is missing.

Download the latest version or run a [normal update](https://github.com/datenstrom/yellow-plugins/tree/master/update#how-to-update-a-website), then it should go away.

**Comment by gdippe** [comment]
I tried to update the usual way but that failed for some reason. Thats why I manually replaced the files with the updated ones. Right now I tried once again to replace core.php but I still get the same error. Is there any other file that is involved in this which might tigger the error?

**Comment by gdippe** [comment]
Thank you! I'll do that.
