### ISSUE TITLE
How to correctly shuffle page selection?

### ISSUE THREAD

**Issue by schulle4u** [datenstrom/yellow#285]
Hello, 

I found an example snippet in the API documentation to show random pages and would like to use it in a plugin as a shortcut to have more flexibility. This is what I tried so far: 

```php
		if($name=="random" && $shortcut)
		{
			list($location, $pagesMax) = $this->yellow->toolbox->getTextArgs($text);
			if(empty($location)) $location = $this->yellow->config->get("randomLocation");
			if(strempty($pagesMax)) $pagesMax = $this->yellow->config->get("randomPagesMax");
			$pages = $this->yellow->pages->find($location);
			$output .= "<div class=\"".$name."\">\n";
			foreach($this->yellow->pages->shuffle()->limit($pagesMax) as $page) {
			// Page list
```

I'll leave the rest of the code aside for the moment. The above lines result in the following error: 

```
Fatal error: Call to undefined method YellowPages::shuffle() in /[...]/system/plugins/random.php on line 31 
``` 

Any idea what's going wrong in my guesswork code and how to use the page shuffle function correctly? What I'm trying to do in result is a random page selection from a specific location, assuming this is possible actually. 

Thanks in advance. 

Steffen

**Comment by markseu** [comment]
Hello Steffen,

Here's an example to access random pages at a specific location:

```php
$parent = $this->yellow->pages->find($location);
$pages = $parent ? $parent->getChildren() : $this->yellow->pages->clean();
foreach($pages->shuffle()->limit($pagesMax) as $page)
{
  // More code here
}
```

A few more words how this works: First line gets the parent page for a location. Second line checks if this page exists and then gets all child pages. Third line randomises these pages and limits the number of them. As you can see  `shuffle()` works with a [page collection](https://developers.datenstrom.se/help/api#yellow-page-collection) not with [Yellow pages](https://developers.datenstrom.se/help/api#yellow-pages).

Hope this helps. 😄

**Comment by schulle4u** [comment]
Thanks Mark, exactly what I was looking for. I'll need to tweak some things, but the plugin already works. :)

Steffen
