### ISSUE TITLE
ACL  and private pages

### ISSUE THREAD

**Issue by tjezz** [datenstrom/yellow#288]
Hi
I find yellow a really useful tool for my class.
I know users can be set to allow edition of pages. 
I need some control of the READ access to certain pages.

Can use pages only visible to admin, or any specific user?

Thanks

**Comment by tjezz** [comment]
f0und this draft plugin  https://github.com/datenstrom/yellow-plugins/tree/master/draft  that could be used
any better solution, thanks?

**Comment by markseu** [comment]
Hi tjezz,

I use the draft plugin too... does that work for you or do you need more detailed access control?

**Comment by markseu** [comment]
Once you're in edit mode you can search for `status:draft`, this allows you to see draft pages.
For example log in and search for `status:draft coffee` to see draft pages about coffee.

It's a quick and dirty solution for private pages. Hope this helps.

**Comment by BsNoSi** [comment]
I think, this is a comparable requirement as in #266. Before you may ask: I did not test this yet, because of lack of time I used DokuWiki for the solving the concrete demand.

Not the desired solution, but it works. Regrettably without Yellow.

**Comment by markseu** [comment]
Thanks for the suggestions. I am afraid to say that we don't add detailed access control. We can't promise if we may add something like this, however we definitely appreciate the feedback.

**Comment by BsNoSi** [comment]
With some distance to the requirement I have to say:  Nothing to bother about, nothing to do­. 

I love the very clean usage of Yellow – that works in very much cases very smooth and nice. If there are some additional requirements, there are enough tools out there in this case. I take it like a hammer for a nail (and you can nail a lot of things... and a screwdriver vor a screw.  And nails are totally sufficient for very much requisitions… ;)

This means: Keep on going this (your) way!.Everythig fine.

**Comment by nzyeehaa** [comment]
search for status:draft returns nothing without plugin...
status:hidden returns nothing regardless
