### ISSUE TITLE
Global content plugin

### ISSUE THREAD

**Issue by schulle4u** [datenstrom/yellow#292]
This plugin allows to include page content into another page - either the full content or as a teaser. Using the full content option, you can e.g. create global sidebars very easily. An example `sidebar.txt` will be installed in /content/global which you can parse in each sidebar.txt using the `[global]` shortcut. Once configured, you then only have to edit one sidebar file to let changes appear globally. 

https://github.com/schulle4u/yellow-plugin-global

Steffen

**Comment by schulle4u** [comment]
Plugin added to [the plugins list](https://github.com/datenstrom/yellow-plugins/blob/master/README.md).

**Comment by BsNoSi** [comment]
Sounds interesting. Does `$mode:1` mean, that the `[--more--]` tag is respected? 

How are included commands, i.e. `[image …]` parsed – before or after insert?

**Comment by schulle4u** [comment]
Yes, `$mode = 1` considers a pagebreak tag in the included page content, therefore everything after the page break will be ignored. In theory this should work like the blogpages snippet, but I haven't tested every usecase to be honest. Feel free to file an issue if you encounter any problems with this behaviour. 

Steffen
