### ISSUE TITLE
Apache web server and file not found

### ISSUE THREAD

**Issue by BogusCurry** [datenstrom/yellow#295]
Hello ;D
I have download the actual source from git-repo and would install this, but when I log in comes be site edit a site not found. So my question, is the actual source from repo broken ?

Greetings
Bogus

**Comment by BsNoSi** [comment]
Hello Bogus,

I downloaded the files a few minutes ago – everything works fine.

Can you give some more information, please?

- technical background
- PHP version
- error message
- …

**Comment by BogusCurry** [comment]
Hello BsNoSi ;D
Hmm .. I think that was my fault, then I know me to remember, that yellow brought mod-rewrite and I have not set the path in the htaccess. I will test it ;D
Thanks for you answer ;D

Greetings
Bogus

**Comment by BogusCurry** [comment]
Ok, I have test on another shared hosting webspace by uberspace, there is yellow ok ;D
http://gselgtde.sabic.uberspace.de/yellow
So I think, I have make wrong. This I will found this weekend, they I have a long weekend of holidays  ;D

**Comment by markseu** [comment]
Hello Bogus, 

you probably have to adjust your mod_rewrite [server configuration](https://developers.datenstrom.se/help/server-configuration). Please check if you added `RewriteBase` to the configuration file and contact [Domainfactory support](https://www.df.eu/de/support/kontakt/) if it still doesn't work.
