### ISSUE TITLE
GDPR compliant websites (EU Regulation)

### ISSUE THREAD

**Issue by BsNoSi** [datenstrom/yellow#298]
Because of the „[REGULATION (EU) 2016/679](http://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32016R0679&from=DE) OF THE EUROPEAN PARLIAMENT AND OF THE COUNCIL
on the protection of natural persons with regard to the processing of personal data and on the free movement of such data“ contact forms have to have a check-box to make shure, that the user knwows, that his informations will be processed. The receiver of this message has to document this.
 
The way of processing  has to be described before the message can be sent. 

I hope, that I will find some time at end of year, to implement a solution on that in the contact form of YELLOW. Beyond that, every YELLOW user should inform himself about this ordinance. Violations may be punished with severe fines by the respective state authorities.

**Comment by markseu** [comment]
Thanks for the heads up. 

As an alternative, you could add a text that informs users that there is no need to reveal personal information and informs what's happening with the contact message. Basically a contact form does not require identification, see article 11 in the linked document. I am not a lawyer, would be good to ask one.

**Comment by markseu** [comment]
The GDPR gives EU citizens more control of their digital data. For example to know when personal data is being collected, what data is being collected, how to access to that data and how to request deleting that data. GDPR stands for General Data Protection Regulation, which comes into force in May 2018.

There are multiple areas where a website may be affected:

* user registrations
* comments
* contact forms
* traffic logging

Until there's more information, website owners should do the following:

* enable login restrictions, so no new user accounts can be created
* disable contact form, so no personal information can be collected
* disable comment system, so no personal information can be collected
* please help us with making [yellow-plugins](https://github.com/datenstrom/yellow-plugins) GDPR-compliant

Additional links:

* https://en.wikipedia.org/wiki/General_Data_Protection_Regulation
* https://www.itgovernance.eu/blog/en/how-to-create-gdpr-compliant-consent-forms/
* https://formidableforms.com/gdpr-compliant-formidable-forms/

**Comment by BsNoSi** [comment]
I have removed the contact form from my sites, because it requires crypted transfer (in Germany, not shure, if required generally in the EU) of the data from website to website owner, to be in compliance with GDPR. I open an e-mail with the available e-mail client. In this case the sender is in charge, how he sends the mail. If he has no encryption, it is his descicion. This is not under control of the recepient.

I never used the comment plugin, because this was already an offence against (German) rules before GRPR was released . 

The login restriction is in my opinion not necessary, if there is a compliance information available on the website. As it has to be, to be compliant. There you have to describe, that transfer of information is a personal desicion of the transmitter – this covers the login registration attempt.

The traffic logging is part of my compliance explainations. It is necessary to store some data in the logs to obey (German) laws or to persue abuse. The comply to GDPR is fullfilled, if the logs are not used for other needs than that and are not stored with or become part of personal data. Log data are deleted after 14 days, if there is no offense which grants a legitimate interest in storage. In Germany this is covered by "Art. 6 Abs. 1 lit. f DSGVO" (don't know, if numbering is identical in whole EU).

As far as I know Yellow does not gather or publish personal data expept the one written on the web pages. If there is no PIWIK or something like this used, there are no reasons to worry. Yellow complies to the GDPR rules (exept the mentioned things).

**RELEVANT NOTICE:** This is **my personal opinion**. I am not a lawyer or GDPR legal expert. Together with a few friends we examed the (GERMAN) rules and draw our *own* decisions out of that. Every web site operator should know the GDPR rules and check the measures and rules applicable or required to it, because the web site is only a small piece of the whole thing.

**Comment by BogusCurry** [comment]
Hello ;D
I see that here not give a plugin for this GDPR, that is very short. But I have enough problems with my forum and the DSGVO. And now here too ;(

**Comment by BsNoSi** [comment]
Hi BogusCurry,

there can not be a "GDPR plugin". Yellow as it is complies to the rules. The GDPR point out  *your behaviour* in handling personal data. *You* have to say, how you deal with it, *you* have to describe your processes with personal data. It's all about *your* habits with it. 

A forum is a very special challenge because personal data is there (typically) part of the user profile. Perhaps is enough prevent users of looking for details of other users. And all users have to accept, that their profile data as stored as they are stored. If not, they have to leave the forum and their personal data is deleted.

I think it is not that hard, if you think about it. Otherwise, I wonder how Facebook, Amazon and other forum operator can go on.
