### ISSUE TITLE
Title modifications

### ISSUE THREAD

**Issue by BsNoSi** [datenstrom/yellow#300]
I am a little bit wobbly, wheter it is a bug or a feature: if I change the title of an existing web page, the file name changes, too.

In general, this is nice and follows the concept. But in regard to valid links it is a problem. Because all links to this file now point into nowhere.

Changing the title of a quite new file without links to it makes the current method very handy, changing the – maybe simply mispelled – title of an older page, makes this procedure adverse.

Currently, I see as only posibility of correcting mispelled titles external editing. Obviously,  title is transferred always. This means, if I do not remember an external change and edit with inline editor, the change is made even then.

Maybe there should be an aditional keyword, e.g. `filetitle`, to override the (changed) title in these circumstances. Or the system should resepct previous given titles – but then a maybe wrong typed title of a new page will be kept. Maybe a less problem, but even not nice.

No huge problem, but possibly there is a solution for that, I do not recognize currently.

As you can savly imagine, this notice based on a personal experience. ;)

**Comment by markseu** [comment]
It's a feature. 😄 

I understand that one size does not fit all. There are two things you can do when the default behaviour does not fit into your work flow. First you can add a redirect page from the old location to the new location. Shout if you want an example. Second, you can edit the file manually in the file system.

In the future we could write a plugin that checks the entire website for dead links. Over time links will change and external pages will disappear. The half-life of a random webpage is about two years. For now have a look at the statistics plugin. It can show you which pages were requested and not found.

Hope this helps.

**Comment by BsNoSi** [comment]
As I wrote: the standard behaviour matches *typically and in most cases* the needs. 

Is there a better way for a redirection instead of a cleaned page with `Content has moved. See …` with a link to the new page? This is the only posibility, I spontanuous have in mind, that can be done with the web editor.

The challenge are external links, that can not be modified.

**Comment by markseu** [comment]
No problem, here's an example:

```
---
Title: old-location-here
Redirect: new-location-here
Status: hidden
---
[Content has moved](new-location-here).
```

This will automatically redirect the visitor to the new location. You can still edit the page in the web browser, that's why there is a content with some text. The page will not show up in the sitemap/search/etc, that's why there is a hidden status.

**Comment by BsNoSi** [comment]
O.k. – perhaps I should read the documentation again. I have to admit, that I did not have the `redirection` feature on my list.

With this option there is no problem any more.
