### ISSUE TITLE
draft plugin = bad practice

### ISSUE THREAD

**Issue by nzyeehaa** [datenstrom/yellow#304]
following thread #241 recommending draft status for files...
draft plugin should be merged with core ...
case status: draft
case status: hidden

using two methods is misleading and prone to errors eg:status: draft - without plugin installed - menu still shows -  file still shows

Many people are looking for restricted areas and this would be easy to implement with basic ACL...
status: draft
status: restricted
status: hidden

and add more
status: restrictedManager
status: restrictedUser

and in config: 
restrictedManager = view, edit, delete
restrictedUser = view

it then gives search function a place to look for permissions before displaying pages
login checks status and returns menu/pages according to login

**Comment by nzyeehaa** [comment]
further... search for 
`status: hidden `
returns nothing when logged in.
but it is reported a search for 
`status: draft`
returns draft pages when logged in - no plugin installed - not confirmed.
` status: hidden` 
page can be viewed by a webmaster, using external access methods, but not the end user
likewise a page inside a non menu-linked folder cant be viewed by end user unless it has a menu link or hyperlink somewhere

the search function needs to be modified for the status:...

`var yellow
var user`
should instantiate API, and user rights... my theory would be 
`var yellow `
on any addon or plugin should automatically call API and automatically include user rights

**Comment by markseu** [comment]
Thanks for the suggestions. I am afraid to say that we don't add detailed access control to the core. We can't promise if we may add something like this, however we definitely appreciate the feedback.
