### ISSUE TITLE
markdown cheatsheet error

### ISSUE THREAD

**Issue by nzyeehaa** [datenstrom/yellow#305]
> Status = status for workflow, for example draft, hidden

draft is not a status unless a plugin is installed

**Comment by markseu** [comment]
Yes, it's meant as an overview for common functionality including plugins.

I removed the misleading example from the [Markdown cheat sheet](https://developers.datenstrom.se/help/markdown-cheat-sheet).

Hope this is better for new users?

**Comment by nzyeehaa** [comment]
better for new users?
... or better for correct methods of technical documentation
surely the plugin should edit the files to add descriptions if it requires them?
...or at a minimum, a note added (not supported in base configuration - extra plugin required)

**Comment by nzyeehaa** [comment]
... likewise with any other plugins... 
[youtube fhs55HEl-Gc] = embed Youtube video
[vimeo 13387502] = embed Vimeo video
[soundcloud 101175715] = embed Soundcloud audio
[twitter datenstromse] = embed Twitter messages
[instagram BISN9ngjV2-] = embed Instagram photo
[googlecalendar en.swedish#holiday] = embed Google calendar
[googlemaps Stockholm] = embed Google maps
[blogrecent /blog/] = show recent blog pages
[wikirecent /wiki/] = show recent wiki pages
[fa fa-envelope-o] = show icons and symbols
[ea ea-smile] = show emoji and colorful images

**Comment by markseu** [comment]
Thanks for the feedback.
