### ISSUE TITLE
Tags from all sides

### ISSUE THREAD

**Issue by JanYellow** [datenstrom/yellow#306]
Hi,

Currently I am testing Yellow local as a website. I can show the tags of a page on the current page. Can I also display all assigned tags within the web pages on eg a special page? On a blog or wiki you can do ala [blogtags ...] or [wikitags ...]. But as with a website with subdirectories in which then the individual pages are?

I understand Yellow already ... but the API rather less ;-) More examples would be helpful.

**Comment by schulle4u** [comment]
This afaik is not possible out of the box, but you could try to extract the blogtags shortcode function from the plugin, modify it to your needs and create a separate tags plugin from it. Blog pages actually are like normal pages with slightly different template, so the tags function also should work with other pages too. Haven't tested this however. 

HTH
Steffen

**Comment by markseu** [comment]
By the way, Datenstrom Yellow supports wiki with subdirectories. You can enable it by configuring the wiki location, that's where your wiki start page is. For example open file `system/config/config.ini` and change `WikiLocation: /wiki/`. Now you can to use tags on any page.

Hope this helps. 😄

**Comment by JanYellow** [comment]
@markseu Thanks for your hint, I had already tried that. However, I'm still not quite clear why I should use a wiki, which benefits this has to a website = 8) I have previously created websites exclusively by hand and the individual pages on a folder structure. And the folder structure was then already on several levels. I like Yellow and I'm trying to find my way ;-)

The tip from @ schulle4u seems to me obvious, but I currently understand the API too little. Since I have to test even a bit to gain more understanding of it :-)

**Comment by markseu** [comment]
Here's a bit explanation how Datenstrom Yellow works. It provides the basic functionality for small websites and you can add more features with plugins. When you want to use tags on a website, you probably need three features. First something that parses meta data and displays tags on a page. Second something that parses arguments in the URL and shows pages with a specific tag. Third something that offers a shortcut so you can create a page that shows all tags. 

The wiki plugin does provide all of that, out of the box. So you could extract the code and write your own plugin as Steffen suggested, definitely a good idea to learn more about the API, or you could configure your website as one big wiki. Just ask if you need more information. We're here to help.
