### ISSUE TITLE
Directory name

### ISSUE THREAD

**Issue by JanYellow** [datenstrom/yellow#307]
Hi,

I can create a directory with numbers, for example 2014. The directory can also be accessed via the URL. If I now rename the directory, for example 1-2014, it is no longer accessible at the URL.

As I understand it, a number followed by a hyphen is used for sorting and displaying in navigation?

So can not I use numbers for a directory if I want to have it displayed in the navigation?

**Comment by markseu** [comment]
Yes you can use folder names with numbers and hyphens, for example `2014-01`. There could be a different problem, because [the first folder folder is responsible for the home page](https://developers.datenstrom.se/help/adding-content). If you rename rename `1-home` to `0-home`, that should put the home page first and solve the naming problem. 

Let me know if that works for you?

**Comment by JanYellow** [comment]
Hi Mark,

In the case described is my directory structure:

1-home
2-test
and in 2 a subfolder
5-blah
and in 5 a subfolder
1-2014

If the subfolder is created only as 2014, the call is not a problem.

**Comment by markseu** [comment]
Hi Jan,

in this case the folder `content/2-test/5-blah/1-2014` becomes `http://website/test/blah/1-2014/`. The rule for a folder name is that a prefix consisting of numbers and hyphens will be removed from the URL, unless the folder name consists only of numbers and hyphens. 

Not sure if I could explain this right. Here's something you can do. Log into your website, append the folders to the end of the URL, e.g. `https://developers.datenstrom.se/edit/hello/world/2014/`, click "create this page". Now the necessary folder structure will be created.

**Comment by markseu** [comment]
Hope this answered your questions?

**Comment by JanYellow** [comment]
Hi Mark,

Thank you for your explanation. I do not use the possibility of the edit function, I work with my text editor ;-)

But ... I now create a new folder in the content folder, for example 9-2014, then this is also displayed in the navigation - because he just a number separated from a hyphen - contains. What if I but this folder, which is indeed numeric (2014), not want to have displayed in the navigation? ;-) There, the folder appears anyway, after he was renamed from 9-2014 in 2014.

I noticed this only by accident experimenting and only because of my demand. So are numeric folders, if you need them, always displayed in a navigation?

Greetings - Jan

**Comment by markseu** [comment]
Numeric folders are usually displayed in the navigation, but the API checks if a page is available.  Remove the file `page.txt` from a folder and it shouldn't be displayed in the navigation anymore. By the way, the developer kit has a test page where you can experiment with content.... and see what happens.

https://developers.datenstrom.se/tests/api-content

Hope this helps.
