### ISSUE TITLE
Sample code for use of "text.ini"

### ISSUE THREAD

**Issue by BsNoSi** [datenstrom/yellow#308]
I am going my first steps to develop Yellow plugins. As [described in the documentation](https://developers.datenstrom.se/help/adjusting-system#text-settings) it is possible, to add translations to `text.ini` to replace there system strings. 

Is there a sample available, how I have to prepare "my" strings, that there is a default replaced by entries of `text.ini`, if there are any?

**Comment by markseu** [comment]
Hi Norbert,

plugins with own text strings have two possibilities at the moment. First if it's an official plugin, the text strings will became part of the official language files. Second if it's a new plugin the text strings will go into new language files. Have a look at https://github.com/nasendackel/yellow-comments

Just for clarification, the file `system/config/text.ini` is for the end user. There the webmaster's can override the language files. As a plugin developer the recommended way is to distribute all resources together with your plugin.

Hope this helps. 😄
