### ISSUE TITLE
Setup improvment

### ISSUE THREAD

**Issue by BsNoSi** [datenstrom/yellow#309]
Creating a demo site with Yellow, I wonder, why the „Name“ is used as site name as well as user name.

Maybe the setup could be a little bit more oriented to the primary result:

- I think, a field „site name“ is missing in setup dialog. 
- As copyright entry I would prefer the autor, that should be the creator of the site. 

The first page may look like this:

![25-01-_2018_08-53-19](https://user-images.githubusercontent.com/2784683/35376918-6c3e6af2-01ad-11e8-9574-a2698443774c.png)

Especially for beginners it would lead to a better starting expierience, together with themes this would result in a better „ready to go“ setup. 

> This is no "must have" improvement. It would simplify the use of Yellow that may spread the use of it. I left out the option in my image, to select a theme for download ,… ;)

**Comment by markseu** [comment]
Hi Norbert,

you are right that the experience for users should be improved. If you don't develop for people, who do you develop for? At the moment the installation comes with English, German, French language files. In the future the installation could detect the user's language and offer the best matching languages.

The initial design idea was that an installation doesn't force people to read pages of instructions and doesn't install software packages with the size of Jupiter. Instead it takes you a few seconds and a small website is available. The user name is used as site name to welcome new users with their own name, it's meant as a nice touch.

I suggest that any further setup goes into "settings". A place where the webmaster can adjust the website at any time. At the moment you can change website settings in the file system, [all settings are located in the system folder](https://developers.datenstrom.se/help/adjusting-system). In the future we could add the ability to change settings to the web browser, for example to change settings with the [edit plugin](https://github.com/datenstrom/yellow-plugins/tree/master/edit).

What do you think?

**Comment by BsNoSi** [comment]
My thoughts are not so much about me as about looking beyond my own nose. The broader the user base, the higher the chances are that more "activists" will find themselves providing themes, etc.

If people install Yellow that works without further hands on, this is good – for a few days. After a few days, they will fall in love with Yellow, and they recognize the need, to improve the own installation. This is the time for the webmaster who can refine the installation. 

But as I can see around me, people have (or take) less time for a real test. Therefore the first impression is very relevant for the future success. 

The idea behind my image is quite simple: the effort for these small improvements should be not so high, but the result for starters is a strongly better impression, because some details are done instantly (that require reading the documentation, currently).

At least is a question for you, to whom you want to adress your work and if this additions may help to improve the reachability of your goal.

This does not mean, that the current setup is complicated or schould be changed – this is *my* reason for loving Yellow. It is very practical, to set up a good looking site with modifications in a few files with an editor. The is an outstanding feature, that hopefully is never given up.

And this is the reason, why I am starting to built themes, a.s.o. So read this as a reflection of my own way into it. I simply remenber, how long it took for me, to understand the required modifications of header and footer to go public with my first Yellow site. 

Not everyone has this patience and therefore these people will never know which ingenious website tool they miss because they give up prematurely.

**Comment by markseu** [comment]
Good idea to make Yellow better. Any help would be much appreciated. 😄
