### ISSUE TITLE
Yellow Theme Buoa

### ISSUE THREAD

**Issue by JanYellow** [datenstrom/yellow#310]
Hi,

Unfortunately, I can not install it as described ([Buoa Theme](https://github.com/BsNoSi/yellow-theme-Buoa)). After that I get the error message:

Fatal error: Class 'YellowThemeBerlin' not found in E:\xampp\htdocs\test\system\plugins\core.php on line 1779

A problem on my side?

**Comment by schulle4u** [comment]
This seems to be a bug in the file `system/themes/assets/buoa.php`. Open the file and search for the line: 

```
$yellow->themes->register("buoa", "YellowThemeBerlin", YellowThemeBuoa::VERSION);
```
Change this to: 

```
$yellow->themes->register("buoa", "YellowThemeBuoa", YellowThemeBuoa::VERSION);
```

As this is a 3rd-party theme, you should [file an issue](https://github.com/BsNoSi/yellow-theme-Buoa/issues) directly on the developer's project site. 

Steffen

**Comment by BsNoSi** [comment]
Sorry for this error – as you can see, I took a template for my template. I fixed it → Thanks to schulle4u for perfect error descrition!

**Comment by schulle4u** [comment]
> as you can see, I took a template for my template. 

That's how I'm still developing my stuff. :)

Steffen

**Comment by BsNoSi** [comment]
Today I found some time to fix the bugs. I added missing files (header/footer snippet). The README has a (very) short installation guide for beginners. Any hints are welcome. 

I appologize for any inconvenience because of the superficial tested previous version.

Norbert

**Comment by JanYellow** [comment]
Hi Norbert,

Somehow my comment from yesterday disappeared ... probably my mistake ;-)

Thanks for your adjustments! The installation is running! Almost everything perfect ...

The sidebar.txt I have created myself ... maybe you could create this with the installation? Would possibly be helpful for completely new users of the plugin?

As you also refer to the Contact Plugin of Yellow in the Theme ... you should probably mention in the description that this Yellow Plugin should be present or should still be installed.

With your [imgpop](https://github.com/BsNoSi/yellow-plugin-imgpop) plugin I had problems ... or misunderstood the handling. For this I have left you an information. But it works for me after my own adjustment.
