### ISSUE TITLE
Spoiler plugin

### ISSUE THREAD

**Issue by schulle4u** [datenstrom/yellow#320]
The [Spoiler](https://github.com/schulle4u/yellow-plugin-spoiler) plugin allows to show/hide certain page elements such as text parts, links, images or embedded media. The elements are not removed from the page output, so the plugin is **not** intended to protect secret information. By default hidden elements are styled using `display: none`, which won't leave blank space between sorounding page elements. You can customize the element ID (useful for more than one spoilers on the same page), a custom label for the toggle link, and whether to hide the element by default or not. 

The plugin doesn't require any special libraries such as Jquery, just a simple line of javascript is added to the page. Please see README for full documentation. Feedback is always welcome. 

Steffen

**Comment by gdippe** [comment]
Thanks!
Good for my photo site. Some people just want to click through the pictures while others also want to read the text.
