### ISSUE TITLE
"only the blog content"

### ISSUE THREAD

**Issue by ztffn** [datenstrom/yellow#323]
I've been looking at different flatpage cms systems for a while now - and they all have too many features, template systems and are installed through ssh and consoles with package dependencies. 

All I need, and all I want is to be able to add new dynamic content to a div in an existing design.
But not even yellow seems to make this simple plan any easier.. I've messed around with it now for a day and I can't seem to figure out how to get rid of the title of the blog page or the footer.
![yellw](https://user-images.githubusercontent.com/6593205/39699177-55061b50-51f8-11e8-9351-cc42ab2d13bd.png)

I'm also having issues deleting the yellow folder through ftp in order to start fresh.

**Comment by nibreh** [comment]
Hello. 

If you want to hide the header and the footer, open your css theme (by default is `/system/themes/assets/flatsite.css`) and add this line:

`.header, .footer {display:none;}`

**Comment by nibreh** [comment]
You can change structure of your site or blog by opening snippets files in `/system/themes/snippets`. There is content-blog.php and content-blogpages.php.

**Comment by ztffn** [comment]
This is my current content of _content-default.php_
`
<?php echo $yellow->page->getContent() ?>
`

What I was hoping to be able to do was to pull the $variables that make up this generated html 
`
<div class="entry tag-example">
<div class="entry-title"><h1><a href="/mechworld/blog/made-for-people">Made for people</a></h1></div>
<div class="entry-meta"><p>2018-04-22 by <a href="/mechworld/blog/author:datenstrom/">Datenstrom</a></p></div>
<div class="entry-content"><p>Datenstrom Yellow is for people who make websites. Create small web pages, blogs and wikis. The focus is on people and that it's useful for you. No database, no admin panel, no distraction that gets in your way. You make your website, we take care of the rest.</p></div>
</div>`

And use them where-ever I wanted in an existing design. I'll try the css hack to get rid of the header and footer.. Though it feels like the opppsite of what I really want - eg. hide the stuff i dont want vs. fetching just the stuff I do want.

**Comment by nibreh** [comment]
You must install BLOG plugin to have `content-blog.php` and `content-blogpages.php`

You can do it by selecting BLOG on a fresh install or [download the plugin](https://github.com/datenstrom/yellow-plugins/tree/master/blog)

If you want a more minimalist and simple blog, take a look at this cms:

https://github.com/hitecherik/BlankBlog
https://github.com/zichy/vicco  
https://github.com/oelna/microblog
https://github.com/VijeMiller/Miter

**Comment by ztffn** [comment]
Thanks for those links, they might come in handy. I'll try making yellow play my game, a bit longer, as I really do want the image slideshow plugin it offers.
