### ISSUE TITLE
Blog: show only post title

### ISSUE THREAD

**Issue by masfur** [datenstrom/yellow#324]
Good morning.
Is it possible to dispaly only post title, without content?
Thanks!

**Comment by schulle4u** [comment]
A simple solution could be to create a `[blogchanges]` shortcut in your page content for a list of blog posts without content or excerpt. You can also edit `/system/themes/snippets/content-blogpages.php` and delete the lines you don't need.

**Comment by masfur** [comment]
Ok thank you. Now I try!
