### ISSUE TITLE
Location-based feed

### ISSUE THREAD

**Issue by schulle4u** [datenstrom/yellow#327]
Because the blog and wiki plugins already support multiple template locations, it would make sense to also reflect this behaviour in the feed plugin. Currently you can only filter feed entries by template, but not by location. Filtering feeds by location is useful for e.g. blog sites with multiple categories where visitors should have the possibility to choose their prefered topic, beside subscribing  to all blog posts. Also some topic-related blogging "planets" require you to submit a special feed if your blog contains more topics than the desired one. 

As a personal example: I have a podcast site with two different series and would like to give my visitors the possibility to subscribe to either all episodes from all series or just the podcast they are interested in. 

Is this possible without rewriting the whole feed plugin? I wasn't successful modifying it and gave up for now. 

Steffen

**Comment by markseu** [comment]
Hi Steffen. 

I looked into the code. You can use the API to filter for meta data, for example for `Tag` or `Author`. Here's a small example `if($_REQUEST["tag"]) $pages->filter("tag", $_REQUEST["tag"]);`. Now your special feed should be available as `http://website/feed/tag:aetherklaenge/page:feed.xml`. 

Hope this helps... and perhaps we can add this feature to the official feed plugin.

**Comment by schulle4u** [comment]
OK, got it to work as you described. I still have to find out how to modify the alternate rss subscription in site metadata, but at least I now have a more flexible feed plugin. :)

**Comment by markseu** [comment]
Done... added to feed plugin.

**Comment by schulle4u** [comment]
Thanks, works even better than my implementation. Think I'll rework my podcast fork as soon as world cup permits. :)

Steffen
