### ISSUE TITLE
EDIT plugin code review

### ISSUE THREAD

**Issue by nzyeehaa** [datenstrom/yellow#330]
The edit plugin has hardcoded formatting which could/should be removed - it plays havoc with other css and requires extra work to modify edit.css - which will be overwritten on update // or make overrides in sites css - which may still be invalidated on updates.
following MVC - or better coding practises - some general suggestions follow....

html snippet from edit.js...
`"<div id=\"yellow-pane-login-fields\">"+
"<input type=\"hidden\" name=\"action\" value=\"login\" />"+
"<p><label for=\"yellow-pane-login-email\">"+this.getText("LoginEmail")+"</label><br /><input class=\"yellow-form-control\" name=\"email\" id=\"yellow-pane-login-email\" maxlength=\"64\" value=\""+yellow.toolbox.encodeHtml(yellow.config.editLoginEmail)+"\" /></p>`

-- which is enclosed in 
`<div id="yellow-pane-login-fields"> then has <p> <label> <br /> and <input class="yellow-form-control">`
all come with their associated styling...

**suggestions...**

```
-remove all hardcoded <br /> 
-remove all <p> {which may be affected by sites css} 
-remove classes, or at least minimise them... 
  - e.g: instead of class="yellow-edit-pane-in-the-ass-login-field-classes"
  - could be simplified to simple groups... class="yel" which would stand for "Yellow Edit(plugin) Language(group)" example below... 
-group radio buttons in a div eg:
```

```
<div class="yel">
<input type="radio" name ="language" id="language-en" value="english">
<label for="language-en">English</label>
</div>
<div class="yel">
<input type="radio" name ="language" id="language-de" value="deutsch">
<label for="language-de">Deutsch</label>
</div>
```

div is normally generic and generally has no associated styling and puts items into a block.
h1, p, form, label, input - should all get their styling/directions from the websites template css, so - 
- generic styling for yellow edit could look like... (writen in .less)

```

.yellow.edit { 
  &.bar { ...}
  &.pane { max-width: 400px; margin: 0 auto;  } // which constrains width/centers text
  & a,
  & input{ display:block; } // puts on separate line
  & input[type="radio"]{ display: inline; } // puts radio buttons inline
}

```

which would probably knock another 20+kb off the total size, give styling back to the websites .css style, and not require overrides to fix yellow styling

**Comment by BsNoSi** [comment]
I think an extra css for the editor is better than styling it in every template. This extracts a "standard" from the "individual" style an makes it easier, to derivate templates to individual needs. 

I agree with you, that it would be useful to make the "editor.css" more independent to website templates. Therefore, a careful look over / improvement of the current editor styles would be useful.

It seems, as if you are experienced in optimizing things like that. You are welcome to improve the editor by clean up the code. We would appreachiate, if you could share this.

**Comment by nzyeehaa** [comment]
hi BsNoSi 
- thought i did just share it... ?
I appreciate your response and realise mine is just one point of view in the multitude, and I am not one of the yellow hats... as it were.

to clarify my post...

- there should be a yellow.css
- it should be a **LOT** smaller for all that it does
- it shouldn't have any styling - except to give shape, or constrict dimensions where required to generic entities e.g: `<div>`
- the editor.css shouldnt be more independant [this makes yellow job harder + web template harder] 
- the editor.css should be more integrative / cooperative / adaptive
- The plugin js code needs the greatest tidy up e.g: edit.js `<br> <p>`

the key points I have made for consideration....

1 - css for the editor adds 5.34 kb - yellow is around 530kb = editor CSS is 10% of the whole website
    - just did an entire web site with 11kb css 
    - the yellow editor.css only partially covers some forms and a yellow.bar at 5.34kb
2 - hardcoding line breaks is never a good coding move and removing them would reduce footprint - this is exactly what should be taken care of by the css
3 - any template will have styling for HTML items...
    ` <a> <form> <label> <input> <button> <p>`
    - and there are browser defaults for some items, like `<a>, <button>`etc -  (although a bit boring)
    - therefore -> it doesn't require anything additional to be coded for a sites css - and the editor would take the look of being an extension of the site.
[what I am saying here - yellow should avoid using standard HTML entities (normally reserved for text) for layout purposes - and avoid applying styles to standard HTML entities  (normally reserved for text). use `<div>`'s as blocks, and only apply base layout as suggested in the last post]
4 - yellow css could be simplified MUCH further 

On the *flip side* - for granular control of the look and layout for yellow editor fields, you would need to either **style**, or **compensate** for **ALL** html entities used... e.g `<p>`

1- you have to either apply styling **OR** redact styling for the `<p>` on the forms. If someone has a padding applied to their site CSS `<p> / <input> / <label> `- then so does the yellow form... on top of yellow hardcoded line breaks - therefore it looks ugly, especially on a phone.
If you choose to hardcode` <br>` and then go to the extent to enclose `<input><label> in <p>` , then you would have to target that also in your CSS - either with your own styling - or redact the sites styling and browser defaults.
currently -

>  .yellow-pane p { margin:0.5em; } but nothing for padding

My suggestion leads to not using `<p>` at all, but if yellow choose to....

> .yellow-form-control p { 
>   margin: 0.5em; 
>   padding: 0; 
>   line-height: normal;
>   -webkit-margin-before: 0; // optional for compliance -  but chrome adds its own margins
>   -webkit-margin-after: 0; 
> }

or else you end up looking something like this...
![yell1](https://user-images.githubusercontent.com/16368709/41754544-deda3e18-7626-11e8-99e9-acc7f5cb49a7.png)

Everything I am suggesting is with the aim of making yellow even better/lighter/faster than it already is...

**Comment by markseu** [comment]
I would like to understand what you want to do. What problem do you want to solve? Having a consistent editor across multiple websites is not a good solution? Customising the editor with CSS is not possible in your own theme?

**Comment by BsNoSi** [comment]
I have a general question: what are we talking about? The installed Yellow base system is below 700k. The edit.css takes about ~ 12k (~1,7% of whole). 

As I said, you are welcome to improve it eg with shorter class names. But: is it worth the time or should this be used for some more relevant improvements?

*Moreover*, I do ***not agree*** in the idea, that edit.css should not contain styling. The general appearance of Yellow is given with this style sheet. You need a common design in a system in which you maybe want/need to help or to explain something to someone.

Because of this reason, the small code overhead is in my eyes something extremly unimportant. The general look and feel not,  which requires this file *with* individual system styling.

Another reason to take it as it is: Maybe there is space for optimisation in several files, that possibly reduces the whole load about 50k (no estimation – simply to say a number). **BUT** (to answer Marks second question) the current technical implementation makes it possible even for non-experts to create an attractive, very flexible and easy to use website in a reasonable time. I'm pretty sure this was one of the most important aspects in creating Yellow.

And you should be aware of those, who simply want to "take and use". In this case you need a system, that offers a goog look and feel *out of the box*. All system given CSS can be overridden by own styles if required (to answer Marks third question). Personally, I do not see this necessity at all, but rather I see the clear advantage that regardless of the design of the website, the processing conditions are always the same.

**Comment by nzyeehaa** [comment]
@mark - 
...understanding...
from edit plugin html -
-remove all hardcoded `<br /> `
-remove all `<p> `

...problem to solve...
No one should need to write additional css to repair yellow editor

...consistent...
YES! - the editor should be consistent - **either**...
--> consistent with the websites theme
--> or consistent using its own yellow theme -  currently it is not. 

add this to your css and you will see it gets ugly real fast...

```
p::first-letter { font-size: 200%; color: #8A2BE2; font-weight: bold; }
p::first-line { background-color: yellow; }
p:first-of-type { font-size: 2em; text-indent: 100px; background: olive; }
P:last-child { background: orange; }
P:nth-child(odd){background-color: pink; }

P, form, input { width: 100%; padding: 20px; border: 3px solid #111; border-radius: 1rem;}
p::after{ content: '----------------'; }
form { background: teal; }
input, label{ line-height: 2; display: inline-block; }
input[type='submit'] { background-color: red; }
```

**Comment by markseu** [comment]
Everything you see in this repository is open source. I believe that listening to people's ideas, problems and complains is an important part of product design. Then it needs volunteers and a lot of work to turn good ideas into good products. It's obvious that good software doesn't happen over night. 

Active contribution is the most effective tool you have to make things happen. If you like to see good software, please consider contributing. If you have problem with something (e.g. making themes), please consider publishing your code. If you think something can be improved, please consider giving us feedback. But again - nothing will happen without volunteers to do the work.

**Comment by nzyeehaa** [comment]
thanks for your opinion... @bsnosi 

this was intended to be a simple solution from the beginning...
instead it has been blown up into a war of opinions... 
which is not inviting...

I am provided some feedback - some examples and a solution for consideration.

**@ later readers**
for versions 0.7.3 / 0.7.4 (other versions untested)

yellow Forms (signup, login, forgot, recover, settings, version, etc) contain fixed HTML line-breaks and `<p>` tags as a method of layout. Therefore the visual look of the forms may be affected when you apply your theme as it may include layout/styling for paragraph and form fields.
you may need to add the following (or something similar) to your website theme for a consistent look of the yellow forms...

> .yellow-pane p {
>   margin: 0;
>   padding: 0;
>   line-height: normal;
>   -webkit-margin-before: 0; 
>   -webkit-margin-after: 0; 
> }
> .yellow-pane br {
>   line-height: 0;
> }

Alternatively, you can add edit the edit.css in the plugins folder - however these changes may be wiped when a Yellow update is done.

**Comment by nzyeehaa** [comment]
@markseu 
thanks for your consideration.

I dont have a problem making themes - the ugly css snippet I gave was provided to highlight some errors.

Even though i made a contribution with my original post... I will consider contributing through github as  Yellow is the only reason I am here.
