### ISSUE TITLE
Redirects to subdomains of website

### ISSUE THREAD

**Issue by Rustapo** [datenstrom/yellow#334]
Good day!

Finally I installed Yellow CMS on my Virtual Hosting. However, I encountered a problem.

I have a domain (domain.com) and subdomain (account.domain.com).

Domain already redirects to the root of the site by Yellow rewrite rules in `.htaccess`.
````
<IfModule mod_rewrite.c>
RewriteEngine on

DirectoryIndex index.html yellow.php 
RewriteRule ^(cache|content|system)/ error [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^ yellow.php [L]
</IfModule>
````
Subdomains should redirect to the subfolders of the site by "old" rewrite rules in `.htaccess`.
````
RewriteEngine on 
RewriteBase / 
RewriteCond %{HTTP_HOST} ^(www\.)?account\.domain\.com$ [NC]
RewriteCond %{REQUEST_URI} !^/users/
RewriteRule ^(.*)$ users/$1 [L]
````
But it make error 403 "_Forbidden. You don't have permission to access /users/ on this server._"
And path domain.com/accounts/ also make error 403.

I don't know well rules of htaccess and hope to your help.

**Comment by schulle4u** [comment]
Just try adding the appropriate directory index files for the directories `/users/` and `/accounts/` to the yellow rewrite rules, this should solve the problem. Assuming your subdomain folders contain a index.php as starting point, change the yellow htaccess code to: 

```
<IfModule mod_rewrite.c>
RewriteEngine on

DirectoryIndex index.html index.php yellow.php 
RewriteRule ^(cache|content|system)/ error [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^ yellow.php [L]
</IfModule>
```


HTH
Steffen

**Comment by Rustapo** [comment]
@schulle4u Make your suggest but it make error 
```
Not Found
The requested URL /user/yellow.php was not found on this server.
```
```
Not Found
The requested URL /account/yellow.php was not found on this server.
```
Any other idea?

**Comment by schulle4u** [comment]
Not without further investigation to be honest. :)
I personally prefer to use dedicated virtual hosts instead of subdirectories in Apache for every subdomain, so different yellow installations and other webapps won't clash with each other. You can also try to put your main yellow installation into a subdirectory and use a php header redirect from your domain's root directory. Put the following as index.php in your website root (edit the path to your needs): 

```
<?php
header("location: ./site");
?>
```

**Comment by Rustapo** [comment]
@schulle4u 
- I have added index.php to the root. Added `<?php header("location: ./site");?>`
- Changed the htaccess 
```
<IfModule mod_rewrite.c>
RewriteEngine on

DirectoryIndex index.html index.php yellow.php 
RewriteRule ^(cache|content|system)/ error [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^ yellow.php [L]
</IfModule>
```
Now all pages (domain.com, any.domain,com - redirects to subfolder. Yellow CMS in root not open.
Think solution in htaccess

**Comment by Rustapo** [comment]
@schulle4u 
Yes this is correct site content
```
* accounts/
* site/ (here goes all yellow stuff)
-- content/
-- media/
-- system/
-- .htaccess (rules of Yellow)
-- yellow.php
* users/
* .htaccess (old roules without rules of Yellow)
index.php (header redirect to /site folder)
```
I have make as your suggest. Now sudomains redirects as required.
But site with Yellow CMS redirect to subfolder and indicate `domain.com/site` in the address bar (not `domain.com`).
Maybe need check htaccess

**Comment by schulle4u** [comment]
Yes, this is of course the expected behaviour. I couldn't find a way to redirect all requests for `example.com/site` to `example.com/`. 
Maybe [this gist](https://gist.github.com/ScottPhillips/1721489) can help you out, it has some commonly used redirect examples.

**Comment by Rustapo** [comment]
I also want clarify that this redirect `<?php header("location: ./site");?>` does not display graphical content. Only the first page of the site is opened and for correct work need to rename all links inside (except for the menu)
Maybe the developer knows the easy way

**Comment by Rustapo** [comment]
I have try to make blank subfolder with index.html - it work.
But index.php is make Error 403
Any idea to resolve this issue?

**Comment by markseu** [comment]
Try to  combine your "old" and "new" rules into one `.htaccess` file:

```
<IfModule mod_rewrite.c>
RewriteEngine on

# Rules for custom URL redirects:

RewriteBase / 
RewriteCond %{HTTP_HOST} ^(www\.)?account\.domain\.com$ [NC]
RewriteCond %{REQUEST_URI} !^/users/
RewriteRule ^(.*)$ users/$1 [L]

# Rules for Datenstrom Yellow:

DirectoryIndex index.html yellow.php 
RewriteRule ^(cache|content|system)/ error [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^ yellow.php [L]
</IfModule>
````

As an alternative, I recommend to put custom URL redirects in your virtual hosts configuration. 

Hope this helps.

**Comment by Rustapo** [comment]
Finally i found simple solution!
You can close this issue!

**Comment by BsNoSi** [comment]
Simple solutions are always welcome. I am sure that anyone with similar requirements will be happy to have a try on your findings.
