### ISSUE TITLE
Multilingual error-pages.

### ISSUE THREAD

**Issue by StephanWeinhold** [datenstrom/yellow#335]
I like the idea how error pages are handled. But they are in English only. Has anyone multilingual 400 error pages in use? Is it easier to hook into the core.php and wrap all $yellow->page->error into ifs? Or is editing the page-error files the better way?

**Comment by markseu** [comment]
I am sorry, this is not possible. The current software doesn't support multi-language error page. Not sure what alternatives you have for dynamically created websites, I haven't seen anyone looking into this. Let us know what you find out.

**Comment by StephanWeinhold** [comment]
Thanks for the answer! I've been looking into this the last couple of days. It feels like implementing multilang into the error handling leads from one new construction to the other. So I guess I'd go with the minimum viable solution and display the text inside system/config/page-error-404.txt in English and German.

**Comment by BsNoSi** [comment]
Have you tried using templates? The structure of error pages seems to support this. If yes, you can work with snippets and snippets can work with text-vars. (Not tested – just an idea).
