### ISSUE TITLE
Sitemap for each language

### ISSUE THREAD

**Issue by le1erdimanche** [datenstrom/yellow#344]
In a website with two languages I would like to set a link from the snippet footer.php to the specific sitemap of each language:
- is this possible?
- since the example given in the manual doesn't work, how would you define the path?

### This is the directory tree 
  - foo_html/
    + cgi-bin/
    - content/
      - 1-de/
        + 1-start/
        + 2-portfolio/
        + 3-store/
        + 4-resources/
        + 5-language/
        + feed/
        + impressum/
        + sitemap/
      - 2-en/
        + 1-start/
        + 2-portfolio/
        + 3-store/
        + 4-resources/
        + 5-language/
        + feed/
        + impressum/
        + sitemap/
      + default/
    + media/
    + system/
    yellow.php

### This is the code snippet in the footer.php
`<a href="<?php echo $yellow->page->base."/sitemap/" ?>">Sitemap</a>
`

**Comment by BsNoSi** [comment]
The easiest way is to create a `footer-de.php` and a `footer-en.php` that is accessed by the themes, that has to be language aware, too. 

If you want to use only a single footer, you may use the language setting of the page, eg

~~~
<?php echo $yellow->page->getHtml("language") ?>
~~~
This requires the use of the `language` tag in the heading of *each* page. 
Your code may look like

~~~
<a href="<?php echo $yellow->page->base."/". $yellow->page->getHtml("language")."/sitemap/" ?>">Sitemap</a>
~~~
assuming that you have the pages `/en/sitemap` and `/de/sitemap/`

(not tested)

**Comment by le1erdimanche** [comment]
Just had to complete the code line in the `footer.php` with `("language")`. The links to the sitemap are working now perfectly in both languages, even without `language` tag in the headlines.

Thank you @BsNoSi for your help.

**Comment by markseu** [comment]
Alternatively, you can change `page->base` to `page->getBase(true)` where needed. Works too. 😄

**Comment by le1erdimanche** [comment]
Hello Mark

Tried it; but I’m too dumb to implement this solution.

Overall; Yellow is such a nice piece of software. Thank you, and I do recommend it to my friends and neighbors!

Best regards

Paul Zoller

Goldbachweg 8
4058 Basel

061 515 67 74
079 673 72 71

www.paulzoller.net
www.farbica.com
p.zoller@farbica.com
