### ISSUE TITLE
Single editor?

### ISSUE THREAD

**Issue by BsNoSi** [datenstrom/yellow#345]
the current ini files offers two (for me new) options:

~~~
EditLoginEmail:
EditLoginPassword:
~~~

Does this offer the option to restrict edit to a single person?

**Comment by schulle4u** [comment]
They are not new, but these options appear to have been removed from recent plugin versions. In my config file they got commented after one of the last updates and also are no longer available as default config in the plugin.

**Comment by schulle4u** [comment]
See also #6#issuecomment-59483646

**Comment by BsNoSi** [comment]
Thanks for your hints. I checked it again – it *has been removed* from the current (new) setup. 

I obviously mixed some files during an experiment and could not remember these. Probably, because I never have used them.
