### ISSUE TITLE
Feed-Plugin doesn't work

### ISSUE THREAD

**Issue by Henryyellow** [datenstrom/yellow#347]
Hello, I like it very much to use Datenstrom Yellow. But today I realized, that the Feed-plugin doesn't work. 
I installed the plugin like suggested, changed system/config/config.ini to "FeedFilter: blog" and put

`<a href="<?php echo $yellow->page->base."/feed/page:feed.xml" ?>">Feed</a>.`

into the footer snippet. The plugin worked without problems since I installed it one month ago, that means, when clicking "Feed." in the footer a feed page was created. Today I tried to do so again but it didn't worked. I get an File-not-found-Error.

Could somebody test if it is a new problem of the plugin or give me a hint, what I could do to get the feed functionality back?

Thanks a lot, Henry

**Comment by schulle4u** [comment]
Haven't found the time to test yet, but try using the latest [master snapshot](https://codeload.github.com/datenstrom/yellow/zip/master) for a new installation and then try to install the feed plugin. As it seems the `update.ini` file structure has changed recently. You also should be able to update your existing installation to get latest updater plugin. 

HTH
Steffen

**Comment by markseu** [comment]
I tested the feed plugin, works on my server. Perhaps you deleted one of the necessary plugin files?
