### ISSUE TITLE
Example plugin template

### ISSUE THREAD

**Issue by schulle4u** [datenstrom/yellow#356]
A lot of work has been done recently to unify coding and documentation standards across Datenstrom Yellow and it's plugins. To have an always up-to-date coding/documentation template for new plugins and omit copying old styles and mistakes over and over from my other plugins, I've created an [example plugin](https://github.com/schulle4u/yellow-plugin-example/). 

The repository contains an example shortcut plugin that does nothing. Shortcuts probably are the most used case when creating new plugins and they are easy to understand for new users. This project however should not be considered as a replacement for the API documentation. The repository also contains a documentation template which you can use to write down all relevant information about your plugin. Following this template you also should be able to use the [release command](https://github.com/datenstrom/yellow-plugins/tree/master/release). I'll try to keep this up-to-date with latest coding and documentation standards used in [the official plugins](https://github.com/datenstrom/yellow-plugins). 

Is something missing in this template you would like to see? Just let me know. I've primarily created this for my own purposes, but maybe this can be useful for other developers too. 

Steffen

**Comment by markseu** [comment]
Thank you Steffen, it's a great idea to have an example plugin.

About Datenstrom coding standards, we started as embedded developers/designers and pretended that every programming language is like C. It's amazing how far you can get with an optimistic tunnel view. As for the current standard, we threw the old one overboard and started searching for a new one. One that's common among web developers. Ideally we would have taken something "established from the industry", but [many programming languages do their own stylistic thing](https://en.wikipedia.org/wiki/Indentation_style). So not without doubts and hesitation, I defined a consistent middle ground and applied it to all programming languages. The new standard is a mix of K&R, JS, CSS and Python. There are only four spaces, double quotes, Unix line endings and braces that open on the same line. To sum it up, which coding standard you use is not that important, using one coding standard is. If in doubt, just use the coding style of existing files.

About converting your files to the new standard. I am afraid to say that I couldn't find a good tool. The existing tools do not work very well, if you apply them to multiple programming languages. There are some good approaches to automatically reformat files when saving or submitting. So the code looks always the same, no matter where the file comes from or what style someone follows. Right now there are no tools that I can recommend. [You can email me](https://datenstrom.se/contact/) and I'll run your plugins through my regex.

**Comment by schulle4u** [comment]
Task automation is great to have. On the other hand it is good to make a code review every now and then, perhaps this can reveal small mistakes. Common tasks such as converting tabstops to spaces in all plugins easily can be done using simple search/replace functions e.g. in text editors such as Notepad++ or even using the command line. In more complex plugins I personally like to have an eye on every individual file.
