### ISSUE TITLE
Minishare plugin

### ISSUE THREAD

**Issue by GiovanniSalmeri** [datenstrom/yellow#364]
Here is a [Minishare plugin](https://github.com/GiovanniSalmeri/yellow-minishare): nothing fancy, just a little alternative to the excellent Shariff plugin for those who prefer an even lighter solution. Probably it is a bit more accessible, since it embeds only standard links. No JS and no Fontawesome. Three predefined graphical styles, it is easy to add new ones.

**Comment by schulle4u** [comment]
Well done! Just installed it on [my podcasting site](https://podcast.robbenradio.de), and now I almost don't like my own plugin anymore. :D

It would be cool to have a `via @username` in the twitter share URL. You can for example check if `socialtagsTwitterUser` is existing.

**Comment by markseu** [comment]
Thank you for making a new plugin. Want to add your plugin to the [list of plugins](https://github.com/datenstrom/yellow-plugins/blob/master/README.md)?
