### ISSUE TITLE
Gallery plugin doesn't work

### ISSUE THREAD

**Issue by iuliuseq** [datenstrom/yellow#375]
Gallery plugin doesn't work in my web :( I use [gallery boris-smokrovic-203380-unsp.jpg] and obtain nothing :( (only the text [gallery boris-smokrovic-203380-unsp.jpg] in my post)
Slider plugin does the same thing (nothing).

**Comment by iuliuseq** [comment]
When I insert a [gallery] in a post I only obtain this:

![blogiulius2](https://user-images.githubusercontent.com/3447900/47148679-98e5e080-d2d1-11e8-8f38-34c7e113c816.jpg)

**Comment by iuliuseq** [comment]
I have deleted my setup.php and reinstalled the plugins and all is working fine now. Thanks a lot for your support 👍

**Comment by datenstromse** [comment]
Fixed with #376
