### ISSUE TITLE
Can't update to 0.7.8

### ISSUE THREAD

**Issue by iuliuseq** [datenstrom/yellow#376]
I can't update from 0.7.6 to 0.7.8 :( The Update plugin does not work in my web :( I cannot see the Update option in my Configurations

![blogiulius](https://user-images.githubusercontent.com/3447900/47138792-a17eec80-d2ba-11e8-892b-696c2ed8fca8.jpg)

**Comment by markseu** [comment]
Please click "About this website"... what do you see?

**Comment by iuliuseq** [comment]
I see this. Pressing Ok just do nothing.
![image](https://user-images.githubusercontent.com/3447900/47139128-5fa27600-d2bb-11e8-85f9-908b9a968ab0.png)

**Comment by markseu** [comment]
Looks like your website has some old plugins that don't work with the automatic software update. Sorry about that. Here's how to fix it. Please delete file `system/plugins/setup.php`, then copy new plugins from a fresh installation into your `system/plugins` folder.

Let me know it this works?

**Comment by iuliuseq** [comment]
Thanks a lot. All seems to work fine right now. I have updated without problems :) I will update the gallery and slider plugins again and try them too
