### ISSUE TITLE
Copy folder in root to static folder root

### ISSUE THREAD

**Issue by tyeeman** [datenstrom/yellow#380]
Where should I place a folder (with files in it) if I want it to be located in the static generated root folder?

**Comment by tyeeman** [comment]
I added a folder to the media folder and it got copied over when the static site was built but I would like it to be in the root if possible. It's for an admin folder btw.

**Comment by markseu** [comment]
I think the [media folder](https://developers.datenstrom.se/help/adding-media) is the best place for additional folders. Datenstrom Yellow creates a static website from your content + media + system folders, other folders are not included at the moment. 

I am curious, what do you use the admin folder for?

**Comment by tyeeman** [comment]
Haha, Netlify again! They have their Netlify CMS which is sort of cool, very small size files but seems to work fine. I have 3 files totalling 1kbyte, config.yml, index.html, netlify.toml and that's it.

**Comment by markseu** [comment]
Thanks for the explanation. I am sorry, the current software doesn't support this feature.

**Comment by markseu** [comment]
Fixed it. Now your `admin` folder should be copied over to the statically generated website. 

Please update your website and let me know if this works for you.

**Comment by markseu** [comment]
Give me a shout if this isn't working as expected. Feedback is always welcome.
