### ISSUE TITLE
Updating Yellow manually

### ISSUE THREAD

**Issue by tyeeman** [datenstrom/yellow#385]
I have Yellow only running in my localhost and for some strange reason apache crashes now and then randomly. Don't know if it's related to Yellow or not. Anyway I want to try ungrading but doing it manually. I read I can do it from command line after installing the update plugin but I prefer manually if possible. I read just the system folder is updated, true? If I copy the new system folder overwriting my current one will I lose any changes in the config.ini file, like website url, template, plugins already installed?

**Comment by schulle4u** [comment]
In most cases you should be safe by just overwriting your `system/plugins` folder. However from time to time there are also updates to plugin options, content files and themes which you'll have to apply manually. Depending on how many content files you have, this can be a time-consuming process.

**Comment by markseu** [comment]
@tyeeman Did this fix the problem? Do you want me to look into Apache crashes?
