### ISSUE TITLE
New Template - How to hide link?

### ISSUE THREAD

**Issue by bialy03** [datenstrom/yellow#391]
I create a template for yellow based on the [Hugo Hermit](https://themes.gohugo.io//theme/hermit/) template. I already have almost everything ready. The problem is that I do not know how to remove the link to the main page from the menu.
`<a<?php echo $page->isActive() ? " class=\"active\" aria-current=\"page\"" : "" ?> href="<?php echo $page->getLocation(true) ?>"><?php echo $page->getHtml("titleNavigation") ?></a>`
When I enter this, the entire menu pops up for me and I need it without a link to the main page.
**How to hide the link to the main page in the menu?**
I am asking for help and greetings.

**Comment by schulle4u** [comment]
Why is it a problem in this particular template? You could try to use a sidebar snippet instead of one of the navigation snippets. Using a sidebar you can create individual menus in your markdown files. 

```
<?php $yellow->snippet("sidebar") ?>
```

It is already part of all `content-*.php` snippets.

**Comment by bialy03** [comment]
Please, give me a example of this

**Comment by bialy03** [comment]
When I removed "1" in the folder name "1-home", the link to the home page disappeared. I dealt with the problem myself. I close. Thank you for all the help.

**Comment by ro1gr** [comment]
It looks like the current version doesn't support a simple deletion of the number from the folder name. At least for me, it didn't work. Is there any other solution to hide an item from the navigation?

**Comment by markseu** [comment]
Yes, this has changed in the meantime. Instead of a prefix you can now use a setting:
https://github.com/datenstrom/yellow-extensions/tree/master/features/core#how-to-hide-a-page

**Comment by BsNoSi** [comment]
... but the folder prefix is still supported? This is a very practical and easy to use feature that I would miss extraordinarily. 

A short test gives the impression that this is the case. Otherwise I would be forced to restructure practically all of my web pages very elaborately - that would be a clear "nogo" for the current version on my part.

**Comment by markseu** [comment]
You can use a numerical prefix for sorting, but a folder prefix has no special meaning anymore.

**Comment by BsNoSi** [comment]
But I can hide a folder by setting its `page.md` file to `unlisted` ?

There should be a simple workaround for that: What about folders like `search` (search extension) or `ontime` (ontime extension), … – there is a need for folders in `content` that are without hassle no part of generated navigation.

**Comment by BsNoSi** [comment]
Meanwhile I updated to most current state (including core) but `Status` still does not operate – any ideas?
![image](https://user-images.githubusercontent.com/2784683/76158782-ddb62580-6119-11ea-882e-3af3064d8cbe.png)

**Comment by markseu** [comment]
A Shift-Reload or cleaning the browser cache should help. If not, please open a new issue.
