### ISSUE TITLE
How to show tags on the blog main page

### ISSUE THREAD

**Issue by bialy03** [datenstrom/yellow#393]
On the post page, the tags are under the post and link to /blog/tag:np.example. I would like to get the same on the site with posts. I made a drawing to make it easier to understand.

![img_20190106_220416](https://user-images.githubusercontent.com/14218799/50797917-ae6a1580-12d6-11e9-80cb-30c1c0b82ac2.jpg)

**Comment by markseu** [comment]
You can customise the layout of your blog here:

`system/themes/snippets/content-blog.php` = source code for blog page  
`system/themes/snippets/content-blogpages.php` = source code for main page  

I would recommend to look at these files. I am sure it takes only a few days until a developer can make his/her own templates. Feel free to post your code, if you have a specific technical problem. As a starting point download the developer kit and have a look at [customising templates](https://developers.datenstrom.se/help/customising-templates).

You can also contact the [commercial support](https://developers.datenstrom.se/help/support), if you want to hire someone to make a template.

**Comment by bialy03** [comment]
I did not mean it, but thanks.

07.01.2019 2:50 PM "Mark Seuffert" <notifications@github.com> napisał(a):

**Comment by markseu** [comment]
Sorry if I misunderstood you. Can you elaborate what is the problem you want to solve?

**Comment by bialy03** [comment]
You do not need to apologize. I just can not explain it. If you have a link
with the name of the author of the blog in the meta tag template, then if
you click it, you will see a page with all the posts from this author. I
would like to get the same with tags. You probably still do not understand
=)

07.01.2019 4:08 PM "Mark Seuffert" <notifications@github.com> napisał(a):

**Comment by markseu** [comment]
Hmm. Let me describe what I understood so far. Please correct me if I am wrong. The blog should be available on your website as `http://website/blog/`. This is the blog main page and shows your "blog pages". They are also called "posts" in other content management systems. It looks something like this:

```
Bialy03's website

Made for people                                   ◀---- Here's the title of a blog page

2018-04-22 by Krystian | Example                  ◀---- Here's date, author and tags

Datenstrom Yellow is for people who make websites. Create small web pages, blogs and 
wikis. The focus is on people and that it's useful for you. No database, no admin panel, 
no distraction that gets in your way. You make your website, we take care of the rest.

[...]                                             ◀---- More blog pages here

© 2019 Bialy03. Made with Datenstrom Yellow.
```

If you click on the title `Made for people`, then one blog page is shown. 
If you click on the author `Krystian `, then all blog pages by this author are shown. 
If you click on the tag `Example`, then all blog pages for this tag are shown.

Is this correct?

**Comment by bialy03** [comment]
Yes. That's exactly what it's all about. I do not know what the tag
reference look like, which is the problem. The rest works.

07.01.2019 11:41 PM "Mark Seuffert" <notifications@github.com> napisał(a):

**Comment by markseu** [comment]
Nice. As I wrote previously, please have a look at files `content-blog.php` and `content-blogpages.php`. The second file is responsible for the blog main page. This is the file you need to change. As a starting point download the developer kit and have a look at [customising templates](https://developers.datenstrom.se/help/customising-templates).

Hope it helps. 😄
