### ISSUE TITLE
Integration of ActivityPub for social networks

### ISSUE THREAD

**Issue by BogusCurry** [datenstrom/yellow#398]
Hello ;D
At first, sorry for my bad englisch ;D OK, I have a little request, activitypub is a API to send content from a cms or social network to the fediverse. The fediverse is Mastodon, Diaspora etc. so alternatives to facebook and co. 
Now when activitypub intraged in yellow, the user can send his content to a fediverse content ;D Here is Wikipedia article to the API, https://en.wikipedia.org/wiki/ActivityPub

I hope you understand, what I mean ;D

Greetings
Bogus

**Comment by nibreh** [comment]
Hello. I think that's a good idea! It could be a plugin but technically I wonder if it's possible and so easy to integrate. I don't know anything about it. 

More and more people are leaving Twitter and Facebook for different reasons (privacy, ethics, advertising) and Yellow can be on the move.

**Comment by schulle4u** [comment]
Interesting idea, however I'm not sure how this could be integrated. Maybe a plugin that hooks into the edit plugin and sends the pages to your feediverse account  upon page creation. 

As an intermediate selfhosted solution you can install the [feed plugin](https://github.com/datenstrom/yellow-extensions/tree/master/features/feed) and use e.g. [Feed2Toot](https://feed2toot.readthedocs.io/en/latest/) to post your pages into the feediverse. 

Steffen

**Comment by BogusCurry** [comment]
Yes, but feed2toot is a bot and so I can not self send the content to fediverse, is not so mine.

**Comment by schulle4u** [comment]
Just did a quick research regarding ActivityPub. As it seems there are only a few php implementations available, and none of them really fit well into Yellow. Incomplete code, composer madness and so on. So the only way to implement this is to write our own ActivityPub implementation or to use an external server application. 

However an interesting tool that probably could be adapted for Yellow is [FediBlog by David Libeau](https://framagit.org/DavidLibeau/FediBlog). It is a markdown-based blog engine that uses the ActivityPub protocol. Except for the headers used by Yellow, the content files should be interchangeable between both applications.

**Comment by BogusCurry** [comment]
Ok, I understand ;D Thanks for the link to Fediblog ;D

Maybe, comes the ActivityPub as Plugin ?

**Comment by datenstromse** [comment]
Good idea, new extensions are always welcome. [Check out the API for developers](https://developers.datenstrom.se/help/api).
