### ISSUE TITLE
Get blogchanges with tags

### ISSUE THREAD

**Issue by bialy03** [datenstrom/yellow#399]
As the following command calls the last posts...
[blogchanges /blog/ 5]
...I would like to make a command that calls posts with tags.

**Comment by datenstromse** [comment]
You need to customise the layout of your blog, see #393

**Comment by bialy03** [comment]
It's different here. It's about this blogchanges shortcut

niedz., 17.02.2019, 10:30: Datenstrom Sweden <notifications@github.com>
napisał(a):

**Comment by schulle4u** [comment]
If you want to display `blogchanges` for a particular tag, you can simply add it to your shortcut arguments. 

`[blogchanges /blog/ 5 - exampleTag]`

Or do you generally want to check if latest blog pages have tags, and exclude those from the list that don't have one? 

Steffen

**Comment by bialy03** [comment]
Just like [blogchanges] returns the last post titles, I want a different
shortcut to return the titles of recent posts with all tags.

niedz., 17.02.2019, 16:25: Steffen Schultz <notifications@github.com>
napisał(a):
