### ISSUE TITLE
change pictures

### ISSUE THREAD

**Issue by cup** [datenstrom/yellow#400]
here:

https://github.com/datenstrom/yellow

here:

https://datenstrom.se/yellow

and here:

https://developers.datenstrom.se

i just see giant pictures of MacBooks and iPhones. Respectfully, I dont use those
devices and dont care to see them. Perhaps the images could be changed to just
the program itself?

**Comment by datenstromse** [comment]
That's what we use at Datenstrom to make software, a Macbook Air, runs and looks great.
