### ISSUE TITLE
What do you think about the new API?

### ISSUE THREAD

**Issue by markseu** [datenstrom/yellow#401]
Hi! We made a new API for develeopers and it would be great to collect more ideas. What would you like to see? Anything not working or missing that you need?

**Comment by schulle4u** [comment]
The update went smoothly. If you're getting "file not found" errors after applying the new folder structure, run another update check to fetch remaining extensions. This should solve all errors. 

The file `system/settings/system.ini` gets a little messy after this type of API changes. New options are appended at the end, and old ones are commented out. Could this be improved somehow to make configuration a little bit cleaner? Maybe a sorting algorythm that rejoins configuration lines on their proper place after update.

**Comment by markseu** [comment]
Good idea. I updated everything with your feedback. 

When the website is updated to the new API, it shows a message to "update your website one more time". It takes two steps to update folder structure and download remaining files. After the website is updated, system settings are ordered/grouped together and old ones are moved to the end.

**Comment by i-do** [comment]
I have some general suggestion.

### 1. Settings menu
I think it would be great to show core version right under Settings header with no click. And rename link "About this website" to "Check updates" or something right the same. It will be more informative for users. 

Maybe add inside "Check updates" window installed plugin info. Or maybe link or button to show this information. If you want I can show my idea on mockup picture.

### 2. Draft plugin
Now I can work on many blog post at one time. And all of them looks the same in the list of posts. 

But I do the trick:
```
Blog post about my company
Wrong door post
✒ Lovely fast Yellow
General errors in web design
```
Is it possible to add [black nib](https://emojipedia.org/black-nib/) for draft status? It's very simple to find such draft post on list.

**Comment by markseu** [comment]
Thanks for your suggestions. I think this can be done with the existing API.

You can adjust [text settings](https://developers.datenstrom.se/help/adjusting-system#text-settings) in file `system/settings/text.ini`. Here's an example:

```
EditVersionTitle: Check updates
EditVersionStatusCheck: Checking for updates…
EditVersionStatusDone: Your website is up to date.
EditVersionStatusWarning: Updates available, contact the webmaster.
EditVersionStatusUpdates: Updates available, update now.
```

You can adjust [html files](https://developers.datenstrom.se/help/html-files) in folder `system/layouts`. Here's an example for showing draft pages:

``` html
<?php $this->yellow->layout("header") ?>
<div class="content">
<div class="main" role="main">
<h1><?php echo $this->yellow->page->getHtml("titleContent") ?></h1>
<?php $pages = $this->yellow->content->index(true, true)->filter("status", "draft") ?>
<?php $this->yellow->page->setLastModified($pages->getModified()) ?>
<ul>
<?php foreach ($pages as $page): ?>
<li><?php echo $page->getHtml("title") ?></li>
<?php endforeach ?>
</ul>
</div>
</div>
<?php $this->yellow->layout("footer") ?>
```

**Comment by i-do** [comment]
Sometimes I need to make a link open on new tab: <a href=".." target="_blank">. 
Is It possible to make it by Markdown plugin?

**Comment by markseu** [comment]
Yes, that's possible. You can use [Markdown Extra features](
https://michelf.ca/projects/php-markdown/extra/):

`[Open link in new tab](https://example.com){target=_blank}`

alternatively you can use HTML:

`<a href="https://example.com" target="_blank">Link in new tab</a>`

**Comment by i-do** [comment]
# Blog plugin
@markseu, you see blog plugin as a coder, I see it from the user's side. So, as an user, I don't want to use any code at all, I want just use it. Trust me: any of this small things is important to new user. I work as UI/UX-designer more than 6 years, so I think you can listen my advise.

So I just ask again: is it possible to add symbol before the blog title if status set as "draft"?
![](https://ws2.sinaimg.cn/large/006tKfTcgy1g0oioelfbmj3069029q33.jpg)
Look how beautiful it looks!

And, yes, it's absolutely understandable to hear No answer.
You're the one of the fastest answerer for the open source free products as for me.

**Comment by markseu** [comment]
I agree that the main focus should be on people. Not on code, web frameworks and technical details.  To answer your question, there are two choices. You can use this product as it is, then what's inside the box is all you get. You can make this product better, then you should become an [contributing user](https://github.com/datenstrom/yellow/blob/master/CONTRIBUTING.md).

**Comment by i-do** [comment]
@markseu I've found an elegant solution for draft status I've asked with no code at all:
I've just added black nib symbol and draft status to the new page template by default. 
Now it works as I want :)

So thanks for your support!

**Comment by markseu** [comment]
Here's a two questions for developers/designers. 

1. You can generate HTML code with layout files. Themes can provide special layout files, to override the default layout. For example the file `system/layouts/default.html` will be used with any theme, the file (a) `system/layouts/default-stockholm.html` will only be used with `Theme: Stockholm`. Or  the file (b) `system/layouts/stockholm-default.html` could be used for Stockholm theme.

2. You can customise HTML meta data in file `system/layouts/header.html`. The core automatically adds HTML code for a website icon, [sometimes called favicon](https://realfavicongenerator.net). Unfortunately here isn't a single icon that works, different platforms expect different icons. Would you mind if I remove the automatic icon handling from the core, in favour of handling it the HTML layout?

Which special file name do you prefer? Which icons do you care about?

**Comment by markseu** [comment]
I changed file name to pattern "theme-layout.html" and moved icon handling to header. See #412

**Comment by markseu** [comment]
Appears to be working, closing issue.
