### ISSUE TITLE
Folders numeration

### ISSUE THREAD

**Issue by i-do** [datenstrom/yellow#402]
Found interesting thing: I love to count my folder list with two digits starting with zero.

So my content looks like this
01-blog
02-projects
03-about
etc

Sometimes blog plugin lost his main page with no practically reason (as for me, of cause). 
Now, this happened after system update from 0.8.1 to 0.8.2. 

Or maybe it's just because old (0.8.1) plugins is installed?

**Comment by schulle4u** [comment]
Please run another update check, this will update the remaining old extensions and the blog page should work again. See also #401

**Comment by markseu** [comment]
Sorry for the trouble, this was my fault. As @schulle4u said, update your website a second time and this should update the remaining files.

**Comment by i-do** [comment]
Yes, it's works like a charm. 
But renamed my 02-blog folter to 2-blog. 

Can author do some changes to prevent this?

**Comment by markseu** [comment]
I improved the software updater and it seams to be working better now. To be honest, I couldn't figure out why a content folder was renamed during system update. Perhaps this is something that happened before. Can you please update your website one more time and check if everything works?

**Comment by i-do** [comment]
I've checked: my first zero is on the place after update with no rename.
Thank you!

**Comment by markseu** [comment]
Thank you. Feedback and bug reports are always welcome. :smile:
