### ISSUE TITLE
Can't Find Generated Static Page

### ISSUE THREAD

**Issue by thumos333** [datenstrom/yellow#405]
Hello,

I am making a static page in Linux and after the `build` command cannot find the actual site. The manual says it is in the `public` folder - but where is that? I looked in home/Public and searched for any newly created folders - to no avail.

Thank you.

**Comment by thumos333** [comment]
The process itself seems to go without a hitch. The output from PHP:

```
~/Downloads/yellow-master $ php yellow.php build
Your website has been updated: Please run command again
```

**Comment by schulle4u** [comment]
Looks like you haven't completed the last Yellow update. Please run `php yellow.php update` and download remaining files, then try to build your website again.

**Comment by thumos333** [comment]
It works!

Now the problem is the website is built without a theme applied. The theme *is* applied, however, when I `serve` the site. I used the master version, with no additional extensions.

Just in case, terminal output:

`igor@m700 ~ $ cd ~/Downloads/yellow-test
igor@m700 ~/Downloads/yellow-test $ php yellow.php update
Your website is up to date
igor@m700 ~/Downloads/yellow-test $ php yellow.php build
ERROR building files: Please configure StaticUrl in file 'system/settings/system.ini'!
Yellow build: 0 files, 1 error
igor@m700 ~/Downloads/yellow-test $ php yellow.php build
Yellow build: 18 files, 0 errors
igor@m700 ~/Downloads/yellow-test $ php yellow.php serve
Starting built-in web server on http://localhost:8000
Press Ctrl-C to quit...`

**Comment by thumos333** [comment]
Tried this on my other machine (both run Solus Linux) - the same result. The site is `built` with no theme applied but `served` with a theme. The Yellow package I used is just the zip file from your site.

![image](https://user-images.githubusercontent.com/29035180/53954304-e929d780-40e6-11e9-98b1-6a2afddcd37f.png)

**Comment by markseu** [comment]
Looks like you're missing one step. Upload the folder to your web server.  [See documentation](
https://developers.datenstrom.se/help/server-configuration#static-website).

**Comment by thumos333** [comment]
Thanks for pointing this out, Mark!

**Comment by datenstromse** [comment]
Feel free to close you own issues when they are solved.

**Comment by thumos333** [comment]
Sure, thanks once again. Yellow is great software making the world better.

**Comment by datenstromse** [comment]
Thank you, feedback and help is much appreciated.

**Comment by thumos333** [comment]
Having another issue with building the site...

After the `build` command, what I have in the `public` folder is:
* media/
* 404.html
* index.html
* robots.txt

That is all - no subfolders and respective content. I had five folders in the `content` folder - and the whole site rendered just fine in the `serve` mode.

I already did `update` before building.

Thanks!

**Comment by datenstromse** [comment]
Please open a new issue.
