### ISSUE TITLE
Theme creation. Base: favicon resources

### ISSUE THREAD

**Issue by i-do** [datenstrom/yellow#406]
Hi! Trying to start new theme fo Yellow. 
First question is: how can I implement favicon resources?

I use [favicongenerator's](https://realfavicongenerator.net/favicon_result?file_id=p1d5cmi2nq1cabp4t5261o6gj7b6#.XIFpLmJMRAZ) result:
````
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/site.webmanifest">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<meta name="msapplication-TileColor" content="#da532c">
<meta name="theme-color" content="#ffffff">
````

I've copy resource files to the /_resourses_ directory and edit header.html template (have added code above as is). 

Refresh the page and see the _flaticon_ code with code I've added:
`<link rel="icon" type="image/png" href="/media/resources/flatsite-icon.png">`

How can I add path to favicon resources? 
Maybe Yellow API have some magic function for the path?

**Comment by schulle4u** [comment]
The file you are looking for is `/system/layouts/header.html`. Just put your code above the closing `</head>`, and adjust the paths to your icons if needed. `/media/ressources` should work in your case.

**Comment by i-do** [comment]
[Steffen](@schulle4u), I did the same, but selected theme icon is still here:
`<link rel="icon" type="image/png" href="/media/resources/flatsite-icon.png">` 

How can I rule this default parameter?

**Comment by schulle4u** [comment]
OK, I had to search a little bit since I'm not much into theming, but as it seems you can simply delete the unwanted icon from your `system/ressources` folder. This will also remove the reference code from your header output. 

HTH
Steffen

**Comment by i-do** [comment]
[Steffen](@schulle4u), thanks a lot! I think it disappeared after png file deletion.
