### ISSUE TITLE
New OpenStreetMap extension

### ISSUE THREAD

**Issue by GiovanniSalmeri** [datenstrom/yellow#408]
All good things come in three's: after the official extension [Googlemaps](https://github.com/datenstrom/yellow-extensions/tree/master/features/googlemaps) and the experimental one [Leaflet](https://github.com/nibreh/yellow-plugin-leaflet) by @nibreh I have written another [little extension for embedding OpenStreetMap maps](https://github.com/GiovanniSalmeri/yellow-openstreetmap). It is different from the latter (which also uses OSM) in that:

1. it has *not* collaborative features
2. it has an interface as similar as possible to the Googlemaps extension
3. it allows to choose between the different layers of OSM
4. it allows to set very easily the marker
5. it doesn't use a third-party JS library (like Leaflet) but only the native interface of OSM (this doesn't mean that it works if JS is disabled!)

I haven't done extensive tests yet, but the basics should be working. Any comment is appreciated!

**Comment by GiovanniSalmeri** [comment]
Now added support for textual addresses, via Nominatim geolocation. With this addition the extension should be a drop-in replacement for Googlemaps.

**Comment by markseu** [comment]
Ciao Giovanni,

all extensions can become part of the regular update mechanism. How does it work? The update mechanism checks if a new version of an extension is available and then download everything. If you are interested, the workflow looks like this:

1. The first time, ask another 3rd party developer to do a code review.
2. [Make sure it works in the developer kit](
https://github.com/datenstrom/yellow-developers), this will help us to catch problems early.
3. [Create a release](https://github.com/datenstrom/yellow-extensions/tree/master/features/release), this will update both your repository and the official repository.
4. Upload changes to GitHub, send a pull request to the official repository.

Maybe you want to give it a try.... and thanks for your contributions.

**Comment by GiovanniSalmeri** [comment]
You read my thoughts, I was just wondering how the update mechanism works... Thank you very much for explaining it, I will give a try as soon as possible!
