### ISSUE TITLE
What's the difference between -Location and -Dir settings?

### ISSUE THREAD

**Issue by GiovanniSalmeri** [datenstrom/yellow#409]
I am afraid my question is silly, but I couldn't find an answer in the docs or in past issues: what's the difference between for example `DownloadLocation` and `DownloadDir`? There are several similar twin settings. In the default settings I see only an additional slash in the first case and also after reading the code I am a bit confused. I ask this because I am writing a new extension and I would like to follow as exactly as possible the patterns used elsewhere. Thank you!

**Comment by schulle4u** [comment]
The `*Location` settings  are used for web-accessible paths, whereas the `*Dir` settings are directories relative to the Yellow directory. As a comprehensible example have a look at `ExtensionLocation` and `ExtensionDir`. The first points to the web-accessible virtual storage for extension files and can be used e.g. for linking CSS ressources (translates to domain + `/media/extensions`), the second is the real system path for the extensions (YellowDir + `system/media/extensions`). 

HTH
Steffen

**Comment by GiovanniSalmeri** [comment]
Alles klar, thank you very much for the quick answer!
