### ISSUE TITLE
Layouts partials other than "sidebar","footer","header"

### ISSUE THREAD

**Issue by inkscar** [datenstrom/yellow#410]
I guess one can produce a modular-style page by listing the content of subpages, but I tried and failed to use layout in an analogous way as that for the sidebar and footer to do that. Can one have other (differently named) layouts with related content file to display the same way?

**Comment by markseu** [comment]
I think the API has everything you need. First access a content file `example.md` in the current folder with e.g. `$page = $this->yellow->content->shared("example")`. Then output the HTML code in your layout with `echo $page->getContent()`.  There's no limit for the number of subpages or layouts. 

I would start with the [developers kit](https://github.com/datenstrom/yellow-developers), it comes with many examples. It should take only a few days until a developer can make own layouts. You can post your code here on GitHub, if you have specific technical questions. You can also contact the [commercial support](https://developers.datenstrom.se/help/support), if you want to hire someone to make a layout.

Happy coding. :smile:

**Comment by inkscar** [comment]
Thanks! I'll install the dev version later and have a look.
