### ISSUE TITLE
How to Create Divs within Footer?

### ISSUE THREAD

**Issue by thumos333** [datenstrom/yellow#415]
Hello,
I can't figure out how to include a left and right parts in the `footer` div. E. g. there are these style groups within the Berlin theme: `.footer .siteinfo-left` and `.footer .siteinfo-right`. And there is a mention of `siteinfo` in the default footer template:
```
<div class="footer" role="contentinfo">
<div class="siteinfo">
```
Where do I actually create these files?

**Comment by markseu** [comment]
Hello, there are two ways to change the website footer:

1. With Markdown in file `content/shared/footer.md`
2. With HTML in file `system/layouts/footer.html`

[Here's an example from the developer kit](https://github.com/datenstrom/yellow-developers/blob/a0993354911f7268123245ee6051efedd00140df/system/layouts/footer.html), with a left and a right part. All HTML files can be adjusted in your `system/layouts` folder. Perhaps the documentation needs to do a better job explaining this. 🤔

**Comment by markseu** [comment]
By the way, [check out the developer kit](https://github.com/datenstrom/yellow-developers). Good place to get started and comes with many examples.

**Comment by thumos333** [comment]
It's more or less what is in a regular master zip.

Is this what you mean? https://developers.datenstrom.se/help/api

**Comment by markseu** [comment]
Installing the developer kit is optional. I can highly recommend it.
