### ISSUE TITLE
Theme Overwritten in Updates?

### ISSUE THREAD

**Issue by thumos333** [datenstrom/yellow#416]
If I make changes to, say, theme Berlin - will they be overwritten during the next update? Does this imply I need to create a separate theme?

Many thanks.

**Comment by schulle4u** [comment]
The updater takes care of modifications to extensions and won't overwrite them, unless you use the "Force update" option. Only API changes are applied, e. g. if a file's location changes.

**Comment by thumos333** [comment]
Okay, thanks!
