### ISSUE TITLE
navigation-tree and navigation-sidebar simultaneously

### ISSUE THREAD

**Issue by auer-kk** [datenstrom/yellow#419]
I would like to have both navigations simultaneously active on (wiki) pages. Any idea how to implement this the right or "yellow" way?

**Comment by markseu** [comment]
I don't know what's the best way. The first option is to implement your own navigation layout. Have a look at the existing navigations in the `system/layouts` folder. The second option is to use Markdown. Create the file `content/shared/sidebar.md`, this gives you [a sidebar shown on all wiki pages](https://developers.datenstrom.se/help/how-to-make-a-wiki#showing-sidebar).

Hope this helps.

**Comment by nzyeehaa** [comment]
link broken https://github.com/datenstrom/yellow/issues/419#issuecomment-482028448

**Comment by datenstromse** [comment]
link fixed
