### ISSUE TITLE
Missing caption declaration in CSS

### ISSUE THREAD

**Issue by GiovanniSalmeri** [datenstrom/yellow#421]
CSS styles lack presently a table caption declaration. It is true that (if I understand well) Markdown Extra does not provide a way to specify a caption, but for example an extension could generate a table with its caption, and a proper declaration in each style would improve the esthetical uniformity. For example for stockholm.css it could be:

```
.content caption {
    text-align: left;
    padding: 0.3em;
    border-bottom: 1px solid #ddd;
    font-weight: bold;
}
```

If it is useful, I can propose a declaration for all the themes currently supported.

**Comment by markseu** [comment]
Can you explain what the problem is? Can you add a screenshot that shows what is missing?

**Comment by GiovanniSalmeri** [comment]
Thank you very much. Yes, I am adding an CSS following the example of other extensions, but this does not solve entirely the problem: a caption styling which will appear perfect with stockholm can appear ugly with another theme. Anyway, I do understand that this is a problem which will affect one in a million user. So I consider the issue closed! :+1:
