### ISSUE TITLE
Request code - Blog

### ISSUE THREAD

**Issue by bialy03** [datenstrom/yellow#423]
I would like to display the last five blog entries in the form as on the page with all posts on the home page.

**Comment by BsNoSi** [comment]
Following is the content of my "blogpage.html" file:

```
<?php $this->yellow->layout("header") ?>
<div class="content blogpages">
<?php $this->yellow->layout("sidebar") ?>
<div class="main" role="main">
<?php if ($this->yellow->page->isExisting("titleBlog")): ?>
<h1><?php echo $this->yellow->page->getHtml("titleBlog") ?></h1>
<?php endif ?>
<?php foreach ($this->yellow->page->getPages() as $page): ?>
<?php $page->set("entryClass", "entry") ?>
<?php if ($page->isExisting("tag")): ?>
<?php foreach (preg_split("/\s*,\s*/", $page->get("tag")) as $tag) { $page->set("entryClass", $page->get("entryClass")." tag-".$this->yellow->toolbox->normaliseArgs($tag, false)); } ?>
<?php endif ?>
<div class="<?php echo $page->getHtml("entryClass") ?>">
<div class="entry-title"><h1><a href="<?php echo $page->getLocation(true) ?>"><?php echo $page->getHtml("title") ?></a></h1></div>
<div class="entry-meta"><p><?php echo $page->getDateHtml("published") ?> <?php echo $this->yellow->text->getHtml("blogBy") ?> <?php $authorCounter = 0; foreach (preg_split("/\s*,\s*/", $page->get("author")) as $author) { if (++$authorCounter>1) echo ", "; echo "<a href=\"".$this->yellow->page->getLocation(true).$this->yellow->toolbox->normaliseArgs("author:$author")."\">".htmlspecialchars($author)."</a>"; } ?></p></div>
<div class="entry-content"><?php echo $this->yellow->toolbox->createTextDescription($page->getContent(), 0, false, "<!--more-->", " <a href=\"".$page->getLocation(true)."\">".$this->yellow->text->getHtml("blogMore")."</a>") ?></div>
</div>
<?php endforeach ?>
<?php $this->yellow->layout("pagination", $this->yellow->page->getPages()) ?>
</div>
</div>
<?php $this->yellow->layout("footer") ?>
```

It creates a startpage like this:

![image](https://user-images.githubusercontent.com/2784683/56954232-98f75080-6b3e-11e9-8f0d-30884442c3f5.png)

Hope this helps.

**Comment by bialy03** [comment]
Thanks

**Comment by i-do** [comment]
@bialy03, I think you need [this](https://github.com/datenstrom/yellow-extensions/tree/master/features/blog)

> Showing latest blog pages:

> [blogchanges /blog/]
> [blogchanges /blog/ 3]
> [blogchanges /blog/ 10]

**Comment by BsNoSi** [comment]
see manual:

**Comment by bialy03** [comment]
I still do not mean it. I want the page just like on the screenshot above. The code is for blogpage.html, not for home

**Comment by markseu** [comment]
Here's how to adjust the layout of your website: https://developers.datenstrom.se/help/html-files

I would start with the [developer kit](https://github.com/datenstrom/yellow-developers), it comes with many examples. It should take only a few days until a developer can make own layouts. You can post your code here on GitHub, if you have specific technical questions. You can also contact the [commercial support](https://developers.datenstrom.se/help/support), if you want to hire someone to make a layout.

Happy coding. :smile:
