### ISSUE TITLE
META extension → questions

### ISSUE THREAD

**Issue by BsNoSi** [datenstrom/yellow#424]
Why was "socialtags" renamed to "meta" ? Besides that I found the former name more expressive regarding to the job the extension does, there are some additional challenges for all having used it. Unfortunately this is mentioned nowhere.

Previously, the page header needed these entries:

```markdown
SocialtagsTwitterUser: 
SocialtagsImage:    
SocialtagsImageAlt: 
```

Now meta uses either the new entry `Image` or the first [image …] entry from the content. If there is any. I use another extension for displaying images that means nothing will be found. But that is by no means the main problem.

**Questions**

1. How does the extension handle an image with a full path if a sample image from a different site shall be used?
   -  "Socialtags" needed the full path. There this was nothing to worry about.
   -  Simple replacing of *socialtagsimage* to *image* will not work as required. The current code of "meta" will generate a senseless image adress in this case.
   - "Find and replace in files" for changing *SocialtagsImage* to *Image* is no working strategy. 
   One hand it touches the file date messing up the file order ("latest") if "modified" is not set. Other hand there is no way to replace varying full paths to fitting local paths – if possible at all.
2. Why is there no "SocialtagsImageAlt" anymore?
3. Is it still useful to append a "?2434" (random number) at the end of the image to force Twitter retrying loading of image if this fails at the first attempt?
4. Is it possible to set a "standard image" if no image is used in the article (except using the header image entry)? <sub>→ new feature</sub> 
   - Maybe the website icon could be a nice standard replacement especially for blogs that typically do not have an image in every post.
6. Is there an *override* of `MetaTwitterUserName` possible to access different twitter accounts from the same website or depending to the respective author of an article?
8. Is there a (known) length of description which is transferred without cutoff from Twitter? <sub>→ general question regardless to the extension</sub>
   - Knowing this can prevent sense distorting cutoff of text. 

In general I am very happy with the new structure and that "meta" is now part of the standard extensions (Congratualtions Steffen!). Because I used *socialtags* as soon as it was available those general changes in behaviour rise problems that should be adressed and hopefully can be solved without manual rework in hundreds of files. I'm sure there are some who are facing this task.

**Comment by markseu** [comment]
Please use the latest version of the [meta extension](https://github.com/datenstrom/yellow-extensions/tree/master/features/meta), this should solve most problems.

You can convert old settings at the command line: `php yellow.php update meta force`.
