### ISSUE TITLE
Unexpected Renaming of Content Folder

### ISSUE THREAD

**Issue by BsNoSi** [datenstrom/yellow#425]
I want to pull up #112 but giving  a more precise description of the things that happen in V0.8.4 (and before).

See following folder structure

    1-home
    2-wiki
       page.md
    3-impress

Opening page.md with the online editor and changing 

    title: This is the page

to

    title: A new Title
    published: 2019-05-06

will  lead to this folder structure:

    1-home
    3-impress
    2019-05-06-a-new-title
       page.md

Without additional `published` or `modified` it leads to

    1-home
    2-a-new-title
       page.md
    3-impress

Both lead to "file not found" for links into this folder.

You can simply prevent this by editing the header area of "page.md" files not online.

 I think it is not worth the time to fix this but I think it would be good to know it. Maybe it should be added as a hint in the online manuals.

**Comment by markseu** [comment]
Here are some tips for the [online editor](https://github.com/datenstrom/yellow-extensions/tree/master/features/edit):

1. Do not change the `Title`, if you don't want to rename a page. 
2. Do use `TitleSlug`, if you want a fixed filename/URL regardless of title.
3. You can edit the content of a page, it will not change filename/URL.

If more people want to change the current behaviour/documentation, let us know how.
