### ISSUE TITLE
How to show blog information in layouts

### ISSUE THREAD

**Issue by bialy03** [datenstrom/yellow#427]
I need to show TAGS of the post. I've been thinking about it for two months.
![Helpful image](https://user-images.githubusercontent.com/37421974/57731931-250b8b00-769c-11e9-9359-f8ed40dd733c.png)

**Comment by datenstromse** [comment]
Please post your code, if you have specific technical questions. See #423

**Comment by bialy03** [comment]
I just want to get tags for a given post. Is it so difficult to understand?

**Comment by markseu** [comment]
I am sorry, the support on Github consists of volunteers.

Everything you see in this repository is open source. I believe that listening to people's ideas, needs and complains is an important part of product design. Then it needs volunteers and a lot of work to turn good ideas into good products. It's obvious that good software doesn't happen over night. We're here to make things for people, to find like-minded people and do it together.

Active contribution is the most effective tool you have to make things happen. If you like to see good software, please consider contributing. If you have a problem with something, please consider asking for help. If you think something can be improved, please consider giving us feedback. But again - nothing will happen without volunteers to do the work.
