### ISSUE TITLE
JSON rest api

### ISSUE THREAD

**Issue by pbuzdin** [datenstrom/yellow#439]
Is there any kind of JSON REST API?
Will it be in future?

**Comment by schulle4u** [comment]
Currently there's no JSON API available. What would be the benefit of such an API for Yellow users or developers? 
In my opinion this is bayond Yellow's scope, but we are always open for new ideas.  😀

**Comment by pbuzdin** [comment]
For example:
Using Yellow as backend and GUI for JSON API.
Utilizing in mobile app, JS app or in third-party integration.

**Comment by datenstromse** [comment]
Sounds like a good idea for an extension. It can be added in the future if there is more demand.

You can suggest new ideas/wishes at https://github.com/datenstrom/yellow-extensions/issues
