### ISSUE TITLE
manage the (website|wiki|blog) entirely from the browser/edit screen

### ISSUE THREAD

**Issue by munyard** [datenstrom/yellow#440]
Is it possible to manage the (website|wiki|blog) entirely from the browser/edit screen?  

I've not found a way to make new folders from the browser/edit? is there a way to do this? 

When I create new documents they do not appear automatically anywhere in the menu however I discovered that if I install the Sitemap Extension I can find the files I've created.

So I thought it might be nice to have a Primary and Secondary Menu: 

The primary menu shows the Folders.
The secondary menu shows the Files in the folder.

**Comment by schulle4u** [comment]
Website management in Datenstrom Yellow primarily focusses on files and folders. Therefore website management from the browser is limited to creation/deletion/editing of pages. The edit extension will create pages in the current folder. So if you create a new page while on the homepage, it will be created in the `1-home` folder as well. But you can create new content folders from the browser simply by adding it to the end of an edit URL, e. g.: 

`https://example.com/edit/new-folder/`

The website will tell you that the page doesn't exist and offer you the possibility to create it if you are logged in. However there's no possibility to sort folders, this has to be done in the file system directly or with an online file manager. 

See also: [how to make a website](https://extensions.datenstrom.se/help/how-to-make-a-website).

HTH
Steffen

**Comment by datenstromse** [comment]
Thanks for your feedback. Features can be added in the future if there is more demand.

You can suggest new ideas/wishes at https://github.com/datenstrom/yellow-extensions/issues
