### ISSUE TITLE
How to set .md template for the location?

### ISSUE THREAD

**Issue by khomutovspace** [datenstrom/yellow#456]
Hello! There is default page-new-default.md and something like this for blog extension. But i can't set it myself for new locations. How to make ir work? For example, i have three locations: magazine, team and blog. And i want to set a new page template for them, so when you are adding page while you are on magazine folder, it has it's own markdown header, and another folder has different. Is there any way to deal with it?

**Comment by markseu** [comment]
If I am not mistaken, a new file is based on the `Layout` and this is customisable. Here's an example:
```
---
Title: Blog
Description: Blog
Layout: blogpages
LayoutNew: blog
---
```

Change `LayoutNew: magazine` and the online editor will use file `page-new-magazine.md`. 

Is this what you're looking for?
