### ISSUE TITLE
[question] Extension connect to fediverse network ?

### ISSUE THREAD

**Issue by BogusCurry** [datenstrom/yellow#457]
Hello ;D
At first, sorry for my bad englisch .. 
My question, give a extension for a connect to the fediverse network (Mataston, Pleroma etc.)? 

Greetings
Bogus

**Comment by schulle4u** [comment]
What should this extension do for you? At least in Mastodon you can use RSS and Atom feeds to display content on your site, e. g. by using [my Ticker extension](https://github.com/schulle4u/yellow-extensions-schulle4u/tree/master/ticker). For other services a JSON feed option might be useful, I'll consider adding this. 

Possible douplicate of #398?

**Comment by BogusCurry** [comment]
Ups yes thats right, ok I closed this issue ;D 

Sorry, my fail ;D

Have a nice Day ;D
