### ISSUE TITLE
How can I prevent user from deleting or adding pages?

### ISSUE THREAD

**Issue by khomutovspace** [datenstrom/yellow#458]
I have designed a website for my user. Can I set some pages that way, so user can edit them but can't delete or add new ones. And from another pages can. Any ways to turn off add and delete buttons on some pages?

**Comment by markseu** [comment]
You can change a user's home page. Users are allowed to add, edit and delete pages within their home page. But nowhere else. This is what the [edit extension](https://github.com/datenstrom/yellow-extensions/tree/master/features/edit) supports out of the box. For more detailed user restrictions you probably have to write your own extension and handle edit events.

This is not exactly what you were asking for, anyway, hope it helps.

**Comment by khomutovspace** [comment]
Well, thanks. But I think that the thing I described is really important in some case. So can it become a feature request maybe?

**Comment by markseu** [comment]
Of course, just open a new issue with your idea. [See contributing guidelines](https://github.com/datenstrom/yellow/blob/master/CONTRIBUTING.md).
