### ISSUE TITLE
What's the way to make a draft page?

### ISSUE THREAD

**Issue by khomutovspace** [datenstrom/yellow#459]
Hello! I use a draft page to save and edit posts later, but how can I make a page, which would consist all the draft pages and be shown only when I am logged in?

**Comment by markseu** [comment]
You can use the [draft extension](https://github.com/datenstrom/yellow-extensions/tree/master/features/draft) together with the [search extension](https://github.com/datenstrom/yellow-extensions/tree/master/features/search).

Once you're logged in you can search for `status:draft`, this allows you to show draft pages. For example log in and search for `status:draft coffee` to see draft pages about coffee. 

As a web developer, you can also make custom HTML files. The API has an example layout for showing draft pages. It's worth learning to make layouts, sooner or later. What's probably missing is a quick way to do this in Markdown files. Do far nobody has requested a `[draftpages]` shortcut.

Hope it helps. 😄

**Comment by khomutovspace** [comment]
Yeah, of course it worth. My task is to build a page, which can be shown in menu only when you are signed in, and I don't know how to, because I have a custom menu layout. And there is nothing in guides about settings, which can implement something, which can be draft into custom layouts.

**Comment by markseu** [comment]
You can use `$this->yellow->getRequestHandler()=="edit"` to check if a user is logged in.  Datenstrom Yellow is modular and has extensions that work together. The normal request handler is the "core", but when a user is logged in the "edit" extension handles most requests.

**Comment by markseu** [comment]
Did you find a solution for your layout?

**Comment by markseu** [comment]
Now there's support to show drafts in the latest [update](https://github.com/datenstrom/yellow-extensions/tree/master/features/update). All draft pages are available on your website as `http://website/edit/drafts/`. It shows a list of pages in alphabetical order. You can customise this in file `system/layouts/draftpages.html`.

**Comment by BsNoSi** [comment]
https://website/edit/drafts/ → not found  (updated to latest version today).

**Comment by markseu** [comment]
If this happens, delete file `system/extensions/draft.php` and install draft extension again.

**Comment by BsNoSi** [comment]
Fixed. :)
