### ISSUE TITLE
links.zip is missing in extension zip folder / master-branch

### ISSUE THREAD

**Issue by icnicl** [datenstrom/yellow#463]
hi, i wanted to download the links extension https://github.com/datenstrom/yellow-extensions/tree/394e8ab7ca31db33dc67e22ac0da98d3fc65d055/features/links but it seems like the `links.zip` is missing in the master branch.

i downloaded the `links.php` and included it i my project, but the zip-file would be more convenient ;-)

**Comment by schulle4u** [comment]
Hello, 

you are referencing an old commit of the master branch. The links extension has been renamed to `previousnext` a while ago. You can find it in the features directory, please use [the latest repository link](https://github.com/datenstrom/yellow-extensions/tree/master/features/previousnext). 

Steffen

**Comment by icnicl** [comment]
hello schulle4u,

thx for the quick response.

the `blog.html` was a bit misleading.

`<?php echo $this->yellow->page->getExtra("links") ?>`

so i looked for a "links" extension, mentioned in issue #137 

it's working now. thx for the support.
