### ISSUE TITLE
What about WebP?

### ISSUE THREAD

**Issue by BsNoSi** [datenstrom/yellow#464]
Because speed is number one issue for a website I am thinking about intensive use of webp which is supported by all current browsers. Reduced size by keeping the same (visual) quality is especially on mobile devices or via wifi a significant "speeder".

Currently, I personally have no time to have a look on it but I want to place some ideas here as a reminder and ask for further ideas an approches for solution:

I love the drag & drop option of the editor. Whould it be [handy|nice|useful] to offer after dropping an option to convert the upload into webp (or …) within a maximum size range (w, h, kB, …) ? 

Especially multi user sites where some not so experienced users upload full size images from their mobile possibly would profit significantly by this – If admin could optionally set this "change to" as a preset – without popup as a standard or selective for users.

   - Where is the entry point in the code if I would like to add such a feature?
   - How can this feature possibly be added to the gallery and other image extensions?

**Comment by markseu** [comment]
Wikipedia says about WebP image format:

>CMS (Content Management Systems) usually do not support WebP natively or by default. However, for most popular CMS, extensions are available for automated conversion from other image formats to WebP and delivering WebP images to compatible browsers.

Let's see how this works in Datenstrom Yellow. 

At the moment the following image formats are supported: `gif jpg png svg`. If you want to add an additional image format, a good starting point would be looking into the core and image extension. Basically search the PHP source code for occurrences of `jpg` and `png`. The image extension uses GD graphics library by Thomas Boutell, so this would be another thing to look into.

The image extension already supports resizing uploaded images. There's a maximum width/height setting you can configure. However the image format stays the same. If you want to convert uploaded images to a different image format, feel free to make a feature request.

Happy coding. 😄

**Comment by BsNoSi** [comment]
Generally, webp is supported by Datenstrom Yellow out of the box as long as you do not us thumbnail creation. This ends up in "desaster". Because my [extension imgpop](https://github.com/BsNoSi/yellow-extension-imgpop) simply scales the image with CSS, I use it currently as a workaround. 

Unfortunately, the exif comments for Webp seem to work differently as with jpeg - reading out longer information about the image from there is still a challenge to be solved with webp…

**Comment by markseu** [comment]
If someone wants to experiment, please go ahead and send a pull request.
