### ISSUE TITLE
PageExtra only on pages with extra

### ISSUE THREAD

**Issue by BsNoSi** [datenstrom/yellow#469]
The »onParsePageExtra« adds extension extras to all pages with 
~~~
<?php echo $this->yellow->page->getExtra("…") ?>
~~~
regardless if this is necessary for the current page.

How can I restrict the "extras" to those pages where an extension is actually in use?

**Comment by schulle4u** [comment]
There are several methods imaginable to check if an extension is in use, depending on what the extension offers. The `onParsePageExtra` function gives access to page content and settings. If an extension uses page or system settings you can check their presence / value presence upon loading the header or footer content

```
if ($name == "header && $page->isExisting("exampleSomething")) {
    $output = "Your extra content here.";
}
```

Or if your extension provides a shortcut, simply `preg_match` the page content for this shortcut. 

Steffen

**Comment by BsNoSi** [comment]
Thanks Steffen, this works and is a valuable hint. 

My target is somehow different: Your solution offers checking "header entries". For shure I can add something like 
~~~
title: Bla
theextention: whatever
~~~
and then check `page->isExisting("theextention")`to add or leave out something. 

I am looking for a stable and simple way to add for example huge scripts of extensions only to the footer of pages where the extension is used to avoid the unnecessary traffic on other pages. Especially the homepage would be cleaned from code used only on few  subpages. If you want to check something from your mobile this can save a lot of traffic and speeds up the access.

Best practice from the point of usage: It should be dealed from the extension itself, otherwise the use is too "tricky". If there were an option to add header entries dynamically, combined with your code, everything would be done. Possibly there is a slightly simpler option to achieve this.

**Comment by BsNoSi** [comment]
Found a solution:

~~~
if ($name == "footer" && (strpos($this->yellow->page->getContent($rawFormat = true, $sizeMax = 0),"shortcut-name"))) { …
~~~

Not shure if it is a good idea this way but it works and it has no real impact to loading speed of page(s).

**Comment by schulle4u** [comment]
Looks good to me, probably I would have done the same. According to the php manual, `strpos()` in many cases can be the better choice over `preg_match()` because it processes the string faster.

**Comment by BsNoSi** [comment]
Both options (search an header entry) [available in a new extension »dload«](https://github.com/BsNoSi/Yellow-Extension-dload), basically tested and doing well.
