### ISSUE TITLE
Extension for CSS image slider

### ISSUE THREAD

**Issue by BsNoSi** [datenstrom/yellow#470]
*Plugin* ishow replaced with [*extension* ishow](https://github.com/BsNoSi/yellow-extension-ishow):

- Code reworked 
- better description 
- 8 different presentation modes 
- optionally linking to different hyperlink targets for each image
- no libraries required
- primarily CSS based (with very little javascripting)
- no additional CSS file → only in pages that use ishow

Give it a try (feedback welcome).

**Comment by gdippe** [comment]
It works fine so-far. It does however seem to leave a 3-pixel wide stripe on the left side. The jpg's are equally wide (1240 px but one jpg is 26 px smaller (height). You can check it out at my test site [https://gdfoto.se](GDfoto).

**Comment by gdippe** [comment]
It's the padding 3px that's the problem in ishow.php. I set it to 0px and the problem disappeared.

**Comment by BsNoSi** [comment]
I am not shure if it is nice to have a frame by default. Because of this I tried the padding. Because of this reply I will change the css to "no frame, no padding". A frame might be added with aditional css of the page css. 

Is this o.k. for you?

**Comment by gdippe** [comment]
Probably yes! Upload your mod and I'll test it ASAP :)

**Comment by BsNoSi** [comment]
I updated iShow:
- images are centered now depending to area taken from the first image in queue. This compensates different image sizes. 
- frame optional → new parameter, preset "no frame". Standard is a light gray 1px solid one. You may change this in extension (see comment), update is "careful", means: you have to force an extension update, if you change something inside, which will overwrite your changes ( → save a copy of your changes…).
- reorganized code to ease individual tuning of given CSS, if necessary.

**Comment by gdippe** [comment]
Great job! I did a quick test on my site also with the default frame and it works very well indeed! Thank you!

**Comment by BsNoSi** [comment]
If you want to see the extension "in action" with the option, to try all *showtypes*, go to [Buoa.de/showtime](https://buoa.de/wiki/showtime). Page is written in German but scrolling down will give understanding how to switch between the modes.
