### ISSUE TITLE
Update fails and I get kicked out of backend

### ISSUE THREAD

**Issue by JetGum** [datenstrom/yellow#475]
Hi,

I login into my Yellow backend on my live server. The update dialogue tells me that there is a long list of files that need to be updated (even the Theme files I don't use).

When I click on "Update" I get **kicked out of the backend**.

I see the "Login failed. E-Mail or Password is wrong. Try again" - Message. 

Plus **I cannot login anymore**.

What's going on?

**Comment by markseu** [comment]
I would reset the password or create a new user account. Additionally, I would check if there are any errors in file `system/extensions/yellow.log`. I am only guessing what's going on, but it sound like user accounts have not been converted to the new file format.

**Comment by schulle4u** [comment]
It looks like your `system/settings/users.ini` hasn't been updated to the new structure introduced a few releases ago. I'm not sure if the updater still contains the necessary routines to do this. You can try to recreate your user accounts at the [command line](https://github.com/datenstrom/yellow-extensions/tree/master/features/command). Or grab a fresh copy of Yellow and re-install your website, make sure to not overwrite content files and layout modifications. 

HTH
Steffen

**Comment by JetGum** [comment]
PW reset of admin did the trick. No errors in logfile though.

Seems I had a little confusion with the user/admin account, probably because I installed Yellow on localhost (and created an admin) and then transferred the files onto the live server. Could be that the confirmation mail for admin/user has been missing or Apache on localhost has not been configured to send out emails for confirmation.

Maybe the best way to create admin and user accounts would be online.

Thx for the support.
