### ISSUE TITLE
Templates

### ISSUE THREAD

**Issue by cup** [datenstrom/yellow#476]
Is it possible to call PHP code from Markdown file?

- https://gohugo.io/content-management/shortcodes
- https://php.net/language.basic-syntax.phpmode

**Comment by markseu** [comment]
Yes. I would install the [help extension](https://github.com/datenstrom/yellow-extensions/tree/master/features/help), have a look at Markdown cheat sheet and API for developers.

**Comment by cup** [comment]
Ok I see options for built-in templates here:

https://github.com/datenstrom/yellow-extensions/blob/master/features/help/en/markdown-cheat-sheet.md#shortcuts

but no option for custom templates. Is it possible? I need to use `readFile`
from here:

https://github.com/datenstrom/yellow-extensions/blob/master/features/help/en/api.md#yellow-toolbox

**Comment by markseu** [comment]
Here's how to adjust the layout of your website: https://extensions.datenstrom.se/help/html-files
and here's a PHP tutorial for new developers: https://www.w3schools.com/php7/default.asp

Have a look at the API for developers, it comes with many examples. It should take only a few days until you can make your own layouts. Happy coding. :smile:

**Comment by cup** [comment]
I didnt ask how to use PHP. I know how to use PHP. I for a template (shortcut) that uses `readFile`, or how to create a customer template (shortcut).

**Comment by cup** [comment]
Here is what I came up with. First create `system/extensions/ReadFile.php`:

~~~php
<?php
class YellowReadFile {
   public $yellow;
   function onLoad($yellow) {
      $this->yellow = $yellow;
   }
   function onParseContentShortcut($page, $name, $text) {
      $s1 = dirname($page->fileName);
      return $this->yellow->toolbox->readFile("$s1/$text");
   }
}
~~~

Then you can use like this:

~~~
[ReadFile day.txt]
~~~

**Comment by markseu** [comment]
Great start. Let us know if you have more questions or run into problems.

**Comment by cup4** [comment]
Did someone ban @cup ? If so why?

**Comment by BsNoSi** [comment]
Why do you think that @cup is banned?
