### ISSUE TITLE
image orientation / exif tag

### ISSUE THREAD

**Issue by nzyeehaa** [datenstrom/yellow#478]
having some problems with image orientation.

image taken on cell phone inserts exif tag from accelerometer re:orientaion
transfer image to computer, software accomodates exif tag automatically and shows image upright - but doesnt save the new orientation

upload image to yellow - it strips exif tag and image is upside down

https://www.lifewire.com/why-is-my-picture-turned-sideways-1701398
https://www.ryadel.com/en/change-image-orientation-iphone-andor-android-phone-pics-net-c/

**Comment by markseu** [comment]
Now the  [image extension](https://github.com/datenstrom/yellow-extensions/tree/master/features/image) supports resizing and reorienting uploaded images. This happens automatically when uploading large JPG images, typically taken on a mobile phone.

**Comment by nzyeehaa** [comment]
wow, mark - thanks for your speedy response and fix

mobile phone exif tags now work and image is upright

thanks
