### ISSUE TITLE
Redirected Core…Location(s)

### ISSUE THREAD

**Issue by BsNoSi** [datenstrom/yellow#481]
Accidentally, I found the redirection of »Core…Location« entries of system.ini. 

What is the difference to »Core…Dir« ?

Is it possible, to address a php file with this redirection?

~~~
$TheFile = $this->yellow->system->get("serverBase").$this->yellow->system->get("ressourceLocation")."test.php";
~~~

Because the resources folder this will not work, placing "test.php" into extensions does not work either, if it is no extension (and in this case doesn't need any redirecting).

What will happen, if such a »test.php« is truly placed in a created location `/media/extensions/` ?

I was thinking about organizing additional helper files for extensions in `/media/extension/` but I want to avoid conflicts with this virtual path(es).

**Comment by markseu** [comment]
Yup, I can explain. Direct access to the system folders is not allowed, no direct access to PHP.
Files needed for extensions and resources are mapped via media locations, e.g. JS and CSS.

About putting PHP in media folders, let's call it undefined behaviour, it's not recommended.

**Comment by markseu** [comment]
I answered you in #471, in short it's an [undefined behaviour](https://en.wikipedia.org/wiki/Undefined_behavior).
