### ISSUE TITLE
reStructuredText

### ISSUE THREAD

**Issue by cup4** [datenstrom/yellow#483]
I see that Markdown is supported:

https://github.com/datenstrom/yellow/blob/master/system/extensions/markdown.php

Is reStructuredText supported?

https://docutils.sourceforge.io/docs/user/rst/quickref.html

**Comment by schulle4u** [comment]
Markdown (with MarkdownExtra enhancements) currently is the only supported parser in Yellow. Other parsers can be added as an extension, depending on available developers or popular feature requests. Thumbs up!
