### ISSUE TITLE
Edit plugin redesign

### ISSUE THREAD

**Issue by khomutovspace** [datenstrom/yellow#485]
I have some thoughts on Edit extension design. It work ok, but looks kinda odd and outdated now, in 2020 and also it's layout has the same characteristics. Of course, it can depend on the matter of taste adn changed by every developer for every site, but as it is not so easy because of dynamic building via JS, I suppose it would be great to change it in the way everyone would like to use.

I can write more specific things and help somehow with markup.

**Comment by markseu** [comment]
Good idea for a new extension. [Read more about contributing](https://github.com/datenstrom/yellow/blob/master/CONTRIBUTING.md).
