### ISSUE TITLE
status: ignore / status: hidden / private folder no longer private

### ISSUE THREAD

**Issue by nzyeehaa** [datenstrom/yellow#492]
after a breach of data following an upgrade from 0.8.6 to 0.8.10 I have needed to investigate further...

current version 0.8.10 has page _status_ settings of "**unlisted**" or " " (meaning listed) - which is handy if you want to leave a page off the menu...

...and if additional extensions are installed, you can add "**private**" (which needs a password to view) and/or "**draft**" (which hides it from the menu, but is searchable when logged in)

And with the new status button on the editor, you can cycle between the status's that have been installed ("private", "draft", "unlisted", " ")

prior to 0.8.6 there also used to be "hidden" and "ignore"  which was handy as I could hide a page from the menu, and hide it from the search, and therefore hide it from the public or website users...

There was also the _private folder_ - but that is **fully searchable now** which has created a leak of information on one of my sites

so currently I can have a page in the private folder, log out and search for it - and it shows

STATUS | public URL | menu | keyword search | keyword search logged in | search status logged in
----|----|----|----|----|----
listed               | y | y | y | y | 
unlisted           | **Y** | x | x | x | Y
draft                | x | x | x | x | Y
private folder  | **Y** | x | Y | Y | 

*** please be aware - if testing this - the cache will hold search results and needs to be refreshed every time
... also I havent tested the "private" plugin

Suggested behaviour...

STATUS | public URL | menu | keyword search | keyword search logged in | search status logged in
----|----|----|----|----|----
listed                | y | y | y | y |
unlisted            | x | x | y | y | y
draft                 | x | x | x | x | y
private folder   | X | X | X | X | X
OR hidden       | x | x | x | x | x | x

this is quite a complex issue and I imagine there will be a lot of different use cases, and differing opinions about what each should do - but data breaches due to an update are never ok.

**Comment by schulle4u** [comment]
The [private extension](https://github.com/schulle4u/yellow-extensions-schulle4u/tree/master/private) was using a layout file in it's first version, while the latest version uses page settings. This allows to define every page as private, no matter which layout they use. In order to protect your pages again you need to update every page in your private folder.

**Comment by markseu** [comment]
The website update process should have taken care of updating your content files to the new settings and you shouldn't have noticed any problems. I would check if there are any errors in file `system/extensions/yellow.log`.

What you call a "private folder" was previously called an "invisible folder", it marked all files in that folder as not visible. Instead of a folder prefix you can now use a setting for individual pages:
https://github.com/datenstrom/yellow-extensions/tree/master/features/core#how-to-hide-a-page

Or use the online editor and click the status button:

![screenshot status button](https://user-images.githubusercontent.com/2429165/76032642-a1789e80-5f3a-11ea-9b5f-eb4224894c76.png)

**Comment by BsNoSi** [comment]
I updated today and have an empty »status« button without (recognizable) funktion. Is there an additional extension required that is not installed by the update?

**Comment by nzyeehaa** [comment]
@schulle4u thanks for the comment
as mentioned - I hadn't tested the [private](https://github.com/schulle4u/yellow-extensions-schulle4u/tree/master/private) extension. it looks good.

my understanding of the purpose of the private **folder** originally was to hide pages/files from the menu and search - and had understood it was not tied to the "private extension"
In fact I have never used the "private extension", but the private folder was always installed by default

**Comment by nzyeehaa** [comment]
@markseu thanks for the comment

the content files in the private folder were unmodified as far as status goes, they were marked status: ignore

error-log showed nothing

re: private folder=invisible folder
exactly, but following the update the pages were all searchable

**Status: unlisted**
has some issues - note the URL of the page...
mark the page status: unlisted
go to the url of the page and it still shows as per the table above - it is not hidden / unlisted / ignored from any where but a menu perhaps
This is **not** a cache issue...
ctrl-refresh
**page url still exists**

**Comment by nzyeehaa** [comment]
@BsNoSi

try pressing "status" again...

if it is working as I have experienced, on a **new** install...
press the status button in the editor, it will add **status: unlisted** to the "front matter"
press it again it "unlisted" is removed...

if you add the draft plugin...
press the status button in the editor, it will add **status: draft**
press the status button again, it will modify to **status: unlisted**
press the status button again, it will remove **status:**

in my experience, if you have any modifications on the core files, updates don't always work smoothly. 
I generally need to install a new version, copy in my content files, copy in my settings, copy in my templates, re-modify my core files, check functionality, then research what has changed and change any of my own code/layouts to suit

**Comment by markseu** [comment]
I suspect that the problem with the current core comes from being used to an old version of the core, which used a folder prefix to determine visibility. The current core offers more possibilities, by letting you chose visibility and availability via the status setting.

If you would like to have a better website update process, you should join the team that tests new releases and gives timely feedback. We generally aim to make the update as smooth as possible.

**Comment by nzyeehaa** [comment]
@markseu thanks for your comment 

I do appreciate where yellow is heading with the status settings, I also realise it is technically still pre-release, and development is moving rapidly.

> A stock standard yellow using original layout and original theme may update smoothly.

however, my websites were smashed due to the updates from 8.6 to 8.10 I suspect it came in with 
8.7 - API updates break custom themes
 - preview no longer available
 - replaced folder prefix
 - replaced obsolete status
8.8 - added core prefix to some settings - text.ini file not updated?
8.9 - breadcrumbs to breadcrumb - custom layout/css needs updating
 - removed matomo
8.10 - core prefix to language but text.ini not updated
 - sidebar to themes - breaks existing custom theme - sidebar no longer works

and **a lot of this will be due to custom layouts**, still using old API commands, **custom text.ini**. 

Other software I have been involved in decides if an update is a transition, or breaking update and changes the version number to suit ie: transition v6.1 transition v6.2 breaking v7 e.g an API change is going to break existing sites/themes/custom layouts still using old API calls
...and when applying updates includes all past transition updates ie: if you have v5.3 and upgrading 5.4 5.5 5.6 - will include all transition updates for each version but wont update you to 6 if it is a breaking update - this allows you to investigate the changes and rebuild your website.

and some software uses a compatability file - which contains the old commands and redirecting to new commands - like you would do on htaccess to redirect old to new page, therefore all old versions still work, until you hit a major milestone release which may include new core /new API. This extends serviceability of websites and reduces overheads in rebuilding for each release.

`I also note sitemap is cached and still shows page links after marked as draft / unlisted until hard reset`

testing releases would be ok,
is there a roadmap?

**Comment by nzyeehaa** [comment]
@markseu have found a solution which helps until Status: unlisted is repaired.

Status: shared (**url not found** / not shown in sitemap / menu / search)
Status: unlisted ( url found**!** )

**Comment by markseu** [comment]
You're now part of the release testing team, I'll send you an email before making a new release.  😄

**Comment by datenstromse** [comment]
Thanks for your feedback. I am closing this issue, there's not enough information to reproduce a website update problem. As far as I can see, the existing status values are working as documented. I am afraid to say that we don't change status handling, not unless there is more demand. However, you can make an extension that gives you any behaviour you like. If you want to make a new extension, [go ahead and let us know if you need help](https://github.com/datenstrom/yellow/blob/master/CONTRIBUTING.md).

**Comment by BsNoSi** [comment]
Sorry for delay of information: Try "no status" – to be precisly: there ist no status entry  in header – this leaves the status field empty. This is objectivly correct – if there is no status defined no status can be shown. But it is somehow confusing to have an empty button. Maybe a „undefined“ icon ( for instance  `👁?` ) should inform about „no status defined“.
