### ISSUE TITLE
Open help in blank page 

### ISSUE THREAD

**Issue by nzyeehaa** [datenstrom/yellow#495]
contributing.md  suggests to list ideas (rather than pull requests?)

you are working on a page, cant remember some command, want help, click editor help button and lose your page when you go to another website, 
you find what you want but your tab has gone...

**solution:** open another tab, work stays in the background
v 0.8.10 change edit.js line 668
```
 // Process help
    processHelp: function() {
        this.hidePane(this.paneId);
        window.open(this.getText("YellowHelpUrl"), "_self");
    },
```

```
    // Process help
    processHelp: function() {
        this.hidePane(this.paneId);
        window.open(this.getText("YellowHelpUrl"), "_blank");
    },
```

**Comment by datenstromse** [comment]
Thanks for your feedback. I am adding your idea to our internal TODO list. 😀
