### ISSUE TITLE
New extension: Quiz (for self-assessment tests)

### ISSUE THREAD

**Issue by GiovanniSalmeri** [datenstrom/yellow#497]
A little new extension: https://github.com/GiovanniSalmeri/yellow-quiz

It creates very easily multiple-choice and true/false tests from markdownish files.. IMHO writing a text file is one hundred times faster and easier than clicking and clicking and clicking in a graphical interface, like in functionally similar plugins for other CMSs. A button allows to correct the test, check the right answers and obtain a score. So this extension is good for self-assessment tests (even if it could easily be adapted for other purposes). Comments and corrections (also for the language file from native speakers :-)) are welcome!

**Comment by schulle4u** [comment]
Nice to have you back in business. 😀
There is a minor mistake in the `MultichoiceScore` language setting for german, the word "Pünkten" should be translated as "Punkten". 

Steffen

**Comment by GiovanniSalmeri** [comment]
Dankeschön! And thank you for bringing implicitly my attention to the fact that all the names of strings were wrong :-)
