### ISSUE TITLE
New extension: Accordion

### ISSUE THREAD

**Issue by GiovanniSalmeri** [datenstrom/yellow#501]
Another small extension: https://github.com/GiovanniSalmeri/yellow-accordion

It will automatically present in an accordion style so-called definition lists (an extension to Markdown supported by PHP Markdown Extra, the parser currently used by Yellow). The accordion generated is fully accessible with the keyboard and should be accessible also with screen readers. All with about 35 lines of Javascript and a tiny style-sheet :-) I have written this extension for my personal use, hope it will be useful to someone else. Comments welcomed!

**Comment by BsNoSi** [comment]
Very nice. One question: How can I combine a "normal" list (no accordion) with an accordion? 

A glimpse look on it (did not test) seems to offer a general solution: either an accordion or a list. This excludes the use of both simultaneously . Might be an accademical question but spontaneously I have circumstances where this would be a challenge.

**Comment by GiovanniSalmeri** [comment]
> Very nice.

Thank you :-)

> How can I combine a "normal" list (no accordion) with an accordion?

In **different** pages it is very easy: for example it is sufficient to add in a page a setting `AccordionType: none` to disable the extension only for that page (for example, it would be advisable in a page where the extension https://github.com/GiovanniSalmeri/yellow-quiz is used, which marks up questions and answers as definition lists). In the **same** page it is indeed currently not possible, but I am wondering how often it would be necessary: *definition* lists are after all not so often used (they are not even cited in Yellow Markdown cheatsheet nor styled in standard styles). It would be however rather easy to devise and implement a method for doing so (with something like `<div class="no-accordion">`, for example).

**Comment by BsNoSi** [comment]
> You can also set the AccordionType in the settings at the top of a page: 

My fault: A too glimpse look…

I think together in one page is unlikly – I have no idea, where this necessarily might happen. Therefore this is something might be thought about, if there is a very good *must have* explananation… 

To make it clear: is a system entry neccessary anyway?
If `auto` is default no entry in system creates accordions everywhere with one panel open at a time as I understand »setting *can* be configured« – right?

**Comment by GiovanniSalmeri** [comment]
> If auto is default no entry in system creates accordions everywhere with one panel open at a time as I understand »setting can be configured« – right?

Yes, right!
