### ISSUE TITLE
Video controls lost since last update?

### ISSUE THREAD

**Issue by BsNoSi** [datenstrom/yellow#503]
Is there a change of `<video>` tag handling in last update 0.8.11?

Code in markdown source (CONTROLS AUTOBUFFER set):
```
<video controls autobuffer width="100%"  height="auto">
<source src="….mp4" type="video/mp4">
</video>
```

Output created (no controls no autobuffer!!):
```
<video width="100%" height="auto">
<source src="….mp4" type="video/mp4">
 </video>
```

Pasting the code from markdown into a hard coded html page shows video controls as expected (same domain root).

**Comment by schulle4u** [comment]
Yellow 0.8.11 introduces a new HTML filter which replaces markdowns safe mode, maybe it has an impact on some HTML tags. You could try to use XHTML syntax: 

```
<video controls="controls" autobuffer="autobuffer" width="100%"  height="auto">
```

BTW: Autobuffer is a deprecated option. I suggest to use preload instead.

**Comment by schulle4u** [comment]
I've just tested my audio extension on an already updated site. The `controls`  attribute is not present in the list of allowed HTML attributes, therefore audio and also your video controls are not being displayed. 

@markseu it should be save to add this to the filter? 

Steffen

**Comment by BsNoSi** [comment]
@schulle4u: "preload" is removed aswell, ;) (regardless to this you  are right, thanks).

Using XHTML style does not help anyway:

```
<video controls="controls"  preload=none" width="100%"  height="auto">
 <source src="https://buoa.de/media/images/20170228/istgleich.mp4" type="video/mp4">
</video>
```
turnes to
```
<video width="100%" height="auto">
<source src="https://buoa.de/media/images/20170228/istgleich.mp4" type="video/mp4">
</video>
```
The above (intended) code works fine copied between `<html>…</html>` in a *handmade* file located in the same domain.

Is it possible to modify the filter by myself temporarily (where?) to fix this?
It has a very unpleasant impact to the two domains where I found this.

**Comment by schulle4u** [comment]
@BsNoSi the preload attribute actually should work, it is already in the list. Maybe the missing quote breaks your code. 

you can modify the array of allowed HTML attributes in `system/extensions/core.php` until a fix has been published. Jump to line 2390 and look for `$attributesHtml = array(`. Just add your missing attributes to the list of values.

**Comment by BsNoSi** [comment]
Yes – mising quotes are the reason for missing preload. Added `controls` to core.php and everything works fine again.

Thank you, Steffen!

**Comment by BsNoSi** [comment]
I expect a fix in one of the forthcoming updates – therefore closed. Temporary fix for those in a hurry is described above.

**Comment by markseu** [comment]
Go ahead and send a pull request, @BsNoSi.

**Comment by BsNoSi** [comment]
Thanks for the nudge - I just submitted my very first pull request :)
