### ISSUE TITLE
Search reveals markdown code

### ISSUE THREAD

**Issue by BsNoSi** [datenstrom/yellow#508]
I noticed that the search function returns partially unprocessed markdown code. 

In concrete case a footnote is output as text ( `[^note]` → [^note] ) and created content of extensions (Alt text of image). 

Generally, in the search results markdown code and code of extensions should be stripped off.

---
Samples:

![image](https://user-images.githubusercontent.com/2784683/79734228-a761ed80-82f6-11ea-8e06-7a51f4e399c9.png)

Note: It doesn't matter if or if not in edit mode…

**Comment by BsNoSi** [comment]
I my case I found a workaround for »part I« of the challenge: Images do not appear before use of `[--more--]` separator in my content pages. To *stripp off* the ALT-content I changed  `search.html` slightly:

Original line 14:
```
<div class="entry-content"><?php echo htmlspecialchars($this->yellow->toolbox->createTextDescription($page->getContent(false, 4096), $this->yellow->system->get("searchPageLength"))) ?></div>
```
Modified line 14:
```
<div class="entry-content"><?php echo htmlspecialchars($this->yellow->toolbox->createTextDescription($page->getContent(), 0, true, "<!--more-->")) ?></div>
```
Instead of a fixed count of letters the page description (text *before* `[--more--]`) is shown regardless of it's length.

Footnotes still show up (in progress…).

**Comment by schulle4u** [comment]
Regarding footnotes, I can't reproduce the problem. 

```
---
Title: Test
---
This is a test page with footnotes[^1].

[^1]: Does this work?
```

Searching for "footnotes" correctly returns the page excerpt without markdown tags. 

```
Test
This is a test page with footnotes1. Does this work? ↩︎
```

Steffen

**Comment by BsNoSi** [comment]
Same now in my environment after my changes: The footnote is „as a number“ still visible like in your sample with `footnote1` comparably to my screenshot:

![image](https://user-images.githubusercontent.com/2784683/79742294-df6f2d80-8302-11ea-89e6-322388c0b967.png)

I think »this is it« – removing of the number is very difficult and not worth the effort for a very seldom effect (→ avoid footnotes in page descriptions is a simple workaround 😁)

**Comment by markseu** [comment]
Regarding images, I can't reproduce this problem.

Searching the official website for "help" returns the page without alt attributes:

~~~
Help for your website

Get help How to make a website How to make a blog How to make a wiki Markdown cheat sheet API for developers Adjusting content Adjusting media Adjusting system Security configuration Troubleshooting HTML files CSS files JavaScript files Ge…
https://datenstrom.se/yellow/help/
~~~

Not sure what problem you found... can you test this again with a new installation?

**Comment by BsNoSi** [comment]
I checked this: The "ALT" text of [imgpop](https://github.com/BsNoSi/yellow-extension-imgpop) is not stripped. therefore I think it is a specific effect of my extension. I *thought* that it behaves like the image extension but obviously, there is a difference.

Currently I have not the time to clear this but I will put it on the stack of "Yellow to do's".
