### ISSUE TITLE
Configuring the edit extension

### ISSUE THREAD

**Issue by BsNoSi** [datenstrom/yellow#511]
As described in the [settings](https://github.com/datenstrom/yellow-extensions/tree/master/features/edit#settings) it is possible to define a `EditUploadNewLocation`. Default is `/media/@group/@filename`.

How can I direct files *dropped into the edit area* with these settings
- to store all pdf and zip files in `/media/downloads`
- to store all image files (gif,webp,jpg,svg) in `/media/images`  <sub>and, if possible</sub>
- to store all files starting with `thefiles` (or any different grouping property) in `/media/images/thefiles` (for binding all media files of a single page in a folder)

**Comment by markseu** [comment]
The first two items should happen automatically, though webp is not supported yet and you have to handle this on your own. The third item should be possible with the event `onEditMediaFile`, where you can specify`fileNewLocation` for each file. This should override the `EditUploadNewLocation`.

For a starting point, have a look how the blog extension overrides the location. 

Hope this helps, feel free to ask more.
