### ISSUE TITLE
Version 0.8.7 → 0.8.12 "kills" functionality of my own extensions

### ISSUE THREAD

**Issue by BsNoSi** [datenstrom/yellow#517]
Updating 0.87 to 0.8.12 is a "show stopper" for me.

Javascript and settings are filtered from extensions which means that extensions are part of the "whitlisting" – this is a strong constraint for creating extensions that typically should be allowed to operate without being restricted by a core filter. This is a tremendous limitation for creating extensions.

I have to admit that I find it rather annoying and time-consuming that I have to fix every few updates a set of extensions because of changes in the core that are not announced in advance (means "readme" offers it *before* updating) and effect of change is not documented for fast fixing.

This also applies to changes e.g. of `get("extensionLocation")`. In version 0.8.7 it refers to ".../system/", after updating to version 0.8.12 it refers to ".../media/". No idea why (really nothing else then "update") but I am "pissed" because I have to explore by my self why and what for this change has happened and which projects are touched upon this (and need to be fixed).

**Comment by datenstromse** [comment]
Thanks for your feedback. I am afraid to say that keeping extensions up to date is the developer's responsibility. Feel free to ask technical questions, if you need help. I am closing this issue, there's little we can do from our side at the moment.

**Comment by BsNoSi** [comment]
I know, that this is the developers (…my…) responsibility. But it is tiring to run into trouble because nowhere is mentioned, that e.g. function results (`get("extensionLocation")`) have changed or that filtering may delete major functionality of extensions (`onclick=` is wiped out) – which is a crutial bug in my opinion.

One more reason to extract the [whitlisting into external file](https://github.com/datenstrom/yellow/issues/515#issue-615330490).

As a "quick and dirty" solution (to get time for fixing without restoring): Is there a setting, to switch of whitlisting?

**Comment by BsNoSi** [comment]
Again: 
As a "quick and dirty" solution (to get time for fixing without restoring): Is there a setting, to switch of whitlisting?

And:
How can you be so sure that only *my* extensions are concerned? I am the one who is telling you this effect.

**Comment by GiovanniSalmeri** [comment]
> As a "quick and dirty" solution (to get time for fixing without restoring): Is there a setting, to switch of whitlisting?

I think that a quick and dirty solution is mentioned here: https://github.com/datenstrom/yellow/issues/499#issuecomment-601439153

**Comment by BsNoSi** [comment]
@GiovanniSalmeri : Jepp – that works (but in my very upsetting case adding "onClick" to withelist is best even temporary solution until next update).

I think there is an urgent need for [extracting the whitelist](https://github.com/datenstrom/yellow/issues/515#issue-615330490) because it is no satisfying solution to step into core code each time to allow/permit code. A `settings.ini` parameter `securityfilter=0` (or alike) to switch filtering off (default on) would be handy, too.
