### ISSUE TITLE
How to reformat the 'Blog' page?

### ISSUE THREAD

**Issue by Ordresser** [datenstrom/yellow#518]
I still really like Datenstrom Yellow and continue using it.

I just overwrote my 'blog' page (thinking I had pressed plus to add a new blog post. What do I put on the page to make it be the blog page again (show the blogroll)?

Thanks

**Comment by schulle4u** [comment]
Try re-adding the default page header, this should bring back all your blogpages. 

```
---
Title: Blog
Layout: blogpages
LayoutNew: blog
---
```

HTH

**Comment by Ordresser** [comment]
Yup that did it thanks @schulle4u
