### ISSUE TITLE
Is there a way to make an RSS feed for a Datenstrom blog?

### ISSUE THREAD

**Issue by Ordresser** [datenstrom/yellow#520]
I mean, to update when new blog posts are published?

**Comment by schulle4u** [comment]
Yes, you will need the [feed extension](https://github.com/datenstrom/yellow-extensions/tree/master/features/feed). It will create a RSS feed with all pages, but you can restrict it to blog pages only by setting `FeedFilterLayout: blog` in your system configuration file.

**Comment by Ordresser** [comment]
Thank you
