### ISSUE TITLE
Where to put own css when using Bundle extension?

### ISSUE THREAD

**Issue by sthesing** [datenstrom/yellow#523]
I'm using the stockholm theme, but I have some additional css styles that I'd like to use. Sure, I can paste those into stockholm.css and hope that they won't get overwritten by some update, soon.
But can I tell the bundle extension to add my own css file, somehow? Is there some directory the bundle extension looks for custom css files?

**Comment by markseu** [comment]
You can put your additional CSS files into your `system/resources` folder and then add them to the website header in file `system/layouts/header.html`. For example with the following line: 

```
<link rel="stylesheet" type="text/css" media="all" href="<?php echo $resourceLocation."custom.css" ?>" />
```

...right before `</head>`. However, I usually rename the theme's CSS and make my own theme.  😄

**Comment by sthesing** [comment]
OK, thanks.
