### ISSUE TITLE
Uncertainty about phrasing of help text for using javascript

### ISSUE THREAD

**Issue by gdippe** [datenstrom/yellow#525]
On the page https://datenstrom.se/yellow/help/javascript-files, it says;
"You can save JavaScript into a file which has a similar name as the CSS file. Then it will be automatically included."

It is the word "similar" that bugs me. 
Could "a similar" be replaced by "the same root word" or does it mean something else?

If the above is correct then it would be even easier to understand to write "Your custom.js must have a custom.css to be automatically included."

The devil is in the details :)

**Comment by markseu** [comment]
Thanks for your feedback, my thoughts below.

When you use `Theme: stockholm` the website looks for `stockholm.css` and `stockholm.js`.  As far as I can see from the source code, JavaScript file name is created from theme name plus `.js`. If you would like to contribute, go ahead and edit the help. Markdown is easy to change. :)

https://github.com/datenstrom/yellow-extensions/tree/master/features/help

**Comment by gdippe** [comment]
I'm referring to including an external js. Should my-special.js also have a css named my-special.css to be automagically recognized by Yellow? Or how is this done?

**Comment by markseu** [comment]
Yes, if the CSS is named `my-special.css` the JavaScript should be named `my-special.js`.

**Comment by markseu** [comment]
I have a feeling we talk about different things. What's the problem you want to solve?

**Comment by gdippe** [comment]
I do too :) How do I add an external javascript which I thought was descibed? E.g. If I'd like to use another lightbox with Yellow?

**Comment by herula** [comment]
Since Version 0.8.15 external javascript code doesn't work on my installation. It did before. I want to use a Liveblog from https://live.hello-matrix.net/.

**Comment by datenstromse** [comment]
Thanks for your feedback. I am afraid to say that we can't answer your question. The support on GitHub consists of volunteers and help is much appreciated. If you want to get involved, [have a look at our contributing guidelines and work together with us](https://datenstrom.se/yellow/help/contributing-guidelines).
