### ISSUE TITLE
Rejected sitemap URL

### ISSUE THREAD

**Issue by ApertureBMX** [datenstrom/yellow#527]
Hi. I'm using the sitemap extension to generate a sitemap for my website. However, Google Search Console doesn't seem to accept the page:sitemap.xml URL.

Is there a way to generate the sitemap at an alternative, simpler URL such as sitemap/sitemap.xml?

**Comment by ApertureBMX** [comment]
Hmm, now Google seems to have fetched the sitemap. It'd still be nice if the extension would generate a simpler URL, but I guess it's working.

**Comment by markseu** [comment]
As far as I know Datenstrom Yellow doesn't support such URLs in a content folder.

The sitemap is available as `http://website/sitemap/` and `http://website/sitemap/page:sitemap.xml`, this is supported out of the box. The argument tells the extension what format is requested. For beautifying the URL, you probably have to [create your own an extension](https://datenstrom.se/yellow/help/contributing-guidelines) and generate an XML file in the root folder.

**Comment by datenstromse** [comment]
Thanks for your feedback. I am closing this issue, extension works as documented.
