### ISSUE TITLE
Sidebar missing

### ISSUE THREAD

**Issue by elixd** [datenstrom/yellow#531]
I have found on the web that some Yellow CMS sites have a side bar. For example here is a [page](https://in.10437.lima.zone/help/how-to-make-a-blog) where is written that it is sufficient to add a sidebar.md in shared folder.

But it does not work for me. Has this functionality been removed? Any plans to bring it back?

I am not a web developer. My goal is to have a blog with a sidebar where I can list all tags and categories.

**Comment by schulle4u** [comment]
The sidebar feature has been moved to themes. This means that the default layout files provide a one-column layout, but it is possible to adapt any theme for Yellow and create individual layout files for your purpose. 

BTW: The official and most up-to-date documentation can be found [here](https://datenstrom.se/yellow/help/).

HTH
Steffen

**Comment by BsNoSi** [comment]
I searched this *most up to date documentation* now completely for "sidebar" but no match.

After updating a site to current version sidebar is lost. I compared core.php and the code for sidebar handling obviously ist completely removed (V 0.8.20: search "sidebar": 0 hits, V0.8.12: 2 hits).

> To be honest I am pissed about this, because it took me now > 6h to search for a clue if the sidebar handling might have been removed without further notice or replacement hints. This is the only entry I found to this but it is lacking the essential: 

Where is the description how to update existing sitessaving their sidebars?
