### ISSUE TITLE
Best practice needed (modified extensions vs extension updates)

### ISSUE THREAD

**Issue by JetGum** [datenstrom/yellow#532]
Hi all,

I have modified a couple of extensions to my needs while the original extension name has remained the same. These changes obviously get overwritten whenever extension is updated.

Question: What would be best practice to keep my changes **and** use updated (and improved) original extension code? 

One idea that came to mind: 

a) Copy modified extension code into a new .php file and rename it so it is still identifiable (eg: breadcrumbs.php > brdcrmbs.php). 
b) Change shortcodes on website ([breadcrumbs] > [brdcrmbs])
c) Evaluate and compare my modified extension on code line level whenever an update is available
d) Do a-c for multiple projects

Does that make sense to you? Does that even work?

Cheers,

Carsten

**Comment by markseu** [comment]
You can either...

1. send a pull request to the original developer or
2. create your own extension, based on existing code.

Here are some tips for later case:

- pick a unique file name, for example `breadcrumbc.php`, the letter `c` stands for Carsten
- use the name in class/shortcut/settings, for example `class YellowBreadcrumbc` and `[breadcrumbc]`
- publish the modified source code, as required by the terms and conditions of the license
- keep the original attribution, for example: `// Modified from https://github.com/datenstrom/...`
- have a look at our contribution guidelines, [how to create your own extension](https://datenstrom.se/yellow/help/contributing-guidelines)

Good to see more extensions, looking forward to see what else you create.

**Comment by schulle4u** [comment]
Hello Carsten, 

an even better practice would be to suggest your modifications as possible new features to the developers, perhaps you will then have less trouble updating your sites. 😀
But I think your strategy should be OK. I have done the same with the Feed extension and extended/renamed it for [podcast publishing](https://github.com/schulle4u/yellow-extensions-schulle4u/tree/master/podcast). I try to keep track of the original extension code and apply API and layout changes to my modified extension. 

Steffen

**Comment by JetGum** [comment]
Hi guys,

thx for your answers. This clarifies things for me!

From my perspectivem my modifications would not require the creation of a new extension, for I am usually not adding much code or functionality but rather comment and replace a couple of minor things (mainly with regard to SEO or Page speed). Standing on the shoulders of giants, so to speak. Example: In toc.php, I have commented out a couple of lines to blend out 2nd/3rd level headings. And I have changed the code slightly so the numbering of the headings would not be included in the toc links. Thereforem I would refrain from creating a separate extension, but would opt for what I have initially proposed (rename locally, and check from time 2 time the original code). 

On top of that and in cases when there is substantial modification created, I would send a pull request and/or contact the developer. Here, I agree with you,

Cheers,

Carsten

**Comment by datenstromse** [comment]
Thanks for your feedback. I am closing this issue, it appears to be answered. Please consider publishing your extensions. Sharing your improvements may not only help someone else, it may also attracts more developers, which in the long run is from benefit for all of us.
