### ISSUE TITLE
Core pagePrevious pageNext

### ISSUE THREAD

**Issue by i-do** [datenstrom/yellow#534]
Can't find where I can change shortcuts for core [pagePrevious] [pageNext]. 

Found extension witch do the same thing but it's perfectly lay straight under the core [pagePrevious] [pageNext] so I have double links in my Blog.

I need some advice how can I configure this parameters.

**Comment by schulle4u** [comment]
Do you still have the old links extension installed? It has been renamed to `previousnext`. Check your extensions folder for the `links.php` file and delete it, this should solve the problem. 

Steffen

**Comment by i-do** [comment]
@schulle4u, you're right! 
Thanks a lot!
