### ISSUE TITLE
Level 3 headings in TOC extension

### ISSUE THREAD

**Issue by kanbeq** [datenstrom/yellow#544]
Hi,
I need tertiary headers to appear in my TOC. Now the headings in the table of contents only show up to the second row. How to do it?
Example:
1. Headline 1
1.1 Heading 11
**1.1.1** Header 111
**1.1.2** Header 112
2. Headline 2
2.1 Headline 21
**2.1.1** Header 211
**2.1.2** Header 212

And so on...
Thank you in advance for your help.

**Comment by GiovanniSalmeri** [comment]
It should be easy enough to modify the extension in order to show the headings up to a certain (configurable) level. As soon as I have some minutes I will try!

**Comment by GiovanniSalmeri** [comment]
More or less it works, but `tocLevel` cannot currently exceed 3, because h4..h6 are not given an id (I do not know why...).

```
<?php
// modified TOC extension, https://github.com/datenstrom/yellow-extensions/tree/master/source/toc

class YellowToc {
    const VERSION = "0.8.5";
    public $yellow;         // access to API
    
    // Handle initialisation
    public function onLoad($yellow) {
        $this->yellow = $yellow;
        $this->yellow->system->setDefault("tocLevel", "2"); // shows headings up to nth level
        $this->yellow->system->setDefault("tocNumbering", "1"); // if 0 numbers are not added before headings
    }

    // Handle page content in HTML format
    public function onParseContentHtml($page, $text) {
        $callback = function ($matches) use ($page) {
            $output = "<ul class=\"toc\">\n";
            $location = $page->getPage("main")->getLocation(true);
            $rawData = $page->getPage("main")->parserData;
            preg_match_all("/<h(\d) id=\"([^\"]+)\">(.*?)<\/h\d>/i", $rawData, $matches, PREG_SET_ORDER);
            $levelNumbers = array_fill(2, 5, 0);
            $compoundNumber = "";
            foreach ($matches as $match) {
		if ($match[1] > 1 && $match[1] <= $this->yellow->system->get("tocLevel")) {
                    if ($this->yellow->system->get("tocNumbering")) {
                        $levelNumbers[(int)$match[1]] += 1;
                        for ($i = $match[1]+1; $i <= 6; $i++) {
                            $levelNumbers[$i] = 0;
                        }
                        $compoundNumber = implode(".", array_slice($levelNumbers, 0, $match[1]-1)).". ";
                    }
                    $output .= "<li><a href=\"$location#$match[2]\">$compoundNumber$match[3]</a></li>\n";
                }
            }
            $output .= "</ul>\n";
            return $output;
        };
        return preg_replace_callback("/<p>\[toc\]<\/p>\n/i", $callback, $text);
    }
}
```

**Comment by GiovanniSalmeri** [comment]
> h4..h6 are not given an id (I do not know why...).

I answer to myself: h4..h6 are intentionally not given an automatic id in lines 3927 and 3937 of markdown.php:

```
        if (empty($attr) && $level>=2 && $level<=3) $attr = $this->getIdAttribute($text);
```

@markseu is there a compelling reason for this? or could this limitation be lifted?

**Comment by markseu** [comment]
I don't remember the reason, but without an actual requirement I would suggest to keep it.

**Comment by markseu** [comment]
TOC and Markdown work together, it's not a limitation rather that they work hand in hand.

**Comment by GiovanniSalmeri** [comment]
If the above line were `if (empty($attr)) $attr = $this->getIdAttribute($text);`, the above modified toc extension would work 😊. Perhaps it could be useful for example in case of documentation pages with deep subheadings. I think it would be possibile to get the same result without modifying markdown.php (the ids could be added with a onParseContentRaw, right?), but it would be a bit more complicated. But perhaps I am missing something else...

**Comment by kanbeq** [comment]
Thank you very much for your interest in the topic and for trying to solve it. 👍😉 In that version of the extension, I had everything classed well, and now I don't know how to keep it that nice.
![My old TOC](https://user-images.githubusercontent.com/37421974/95852297-d613ca80-0d53-11eb-98d1-07638cf2ff77.png)

**Comment by markseu** [comment]
I updated the Markdown extension for you, so that you can experiment with more headings.

**Comment by GiovanniSalmeri** [comment]
@markseu Thank you very much!

@kanbeq Now if you update your markdown.php extension and use the code that I posted as a modified toc.php extension, you should get what you wish. Remark that you have to adjust in system.ini these two new settings (if you leave the default values, the new toc should behave exactly like the old one!):

`tocLevel`: levels shown by toc (the default is 2, write 3 if ypu want 3 levels, etc.)
`tocNumbering`: whether toc adds before the headings an automatic numbering (the default is 1 [= yes], write 0 [= no] if you do not want an automatic numbering to be added, for example because the headings already contain it).

If all seems OK, in the next days I will publish this modified toc (or I will propose as a modification of the old toc, if the core developers prefer this).

**Comment by kanbeq** [comment]
My point is that the previous version did differentiate between the level of headers (so I could set the padding for lower levels in css), and in your version I can't do that. And I don't know why my previous comment was deleted.

**Comment by GiovanniSalmeri** [comment]
> My point is that the previous version did differentiate between the level of headers (so I could set the padding for lower levels in css), and in your version I can't do that.

You are right, I overlooked the CSS class in my version. It would be easy to add them, but your modification solves your needs.

Perhaps the following two lines should be corrected like this?

```php
                    case 2: ++$major; $minor = $lower = 0;
                    case 3: ++$minor; $lower = 0;
  ```
