### ISSUE TITLE
how can I integrate comments?

### ISSUE THREAD

**Issue by ohnonot** [datenstrom/yellow#55]
The issue:
I would like to have comments on my website/blog.
All I see is a disqus plugin, but I don't want to use disqus (or any cloud service).
Is it possible to have an internal comment system - however simple - with yellowcms?
I have rudimentary knowledge of php so I could try to "port" something, if someone would give me a push in the right direction.

The pleasantries:
I love yellowcms! I've been trying out dozens of more-or-less minimal flat-file cms recently, and this one just feels right. The combination of bareboned, yet noob friendly. The fact that the admin backend is _very_ minimal and **optional**. I hope it stays that way. I prefer editing files, although I'm not a full-time coder. Thanks.

**Comment by markseu** [comment]
Thanks for your feedback!

Yes you're right, for user feedback there's currently Disqus and contact template. Maybe someone has a suggestion for a commenting system or wants to write one? Any help would be much appreciated.

**Comment by conchitawurst** [comment]
Here are two commenting systems which could be used:
https://github.com/monperrus/jskomment
https://github.com/jacobwb/hashover
As I got it right, both are flat-file, so both should be easily integratable without the need of special requirements. However, I have to admit that I'm unskilled in any programming. Therefore, I can't try integrating myself, but maybe someone else is so nice!

**Comment by markseu** [comment]
Here is a commenting system that @nasendackel started:
https://github.com/nasendackel/YellowComments

**Comment by wunderfeyd** [comment]
Please checkout the latest [yellow-comments](https://github.com/nasendackel/yellow-comments). Your feedback there is greatly appreciated.
