### ISSUE TITLE
Feed extension, modification date vs publication date

### ISSUE THREAD

**Issue by BsNoSi** [datenstrom/yellow#550]
After moving a site to another plattform a lot of entries where listed with file date.

Going into the code it seems to me that a missing `modified` entry leads to replacement by file date. 

Maybe it would be an improvement to check cascading →modified →published →filedate to prevent older instalations from that what happend to me the last ~1,5h: Addendum of `modied = published` to pull the (very) old entries back to the right place in feed.

**Comment by markseu** [comment]
Did you know that the [feed extension](https://github.com/datenstrom/yellow-extensions/tree/master/source/feed) has a setting to show blog pages based on the publication date? As a general tip when moving web servers, I would use a software that preserves file names and modification dates.  For example zipping/unzipping the complete website or using the rsync command on Mac/Linux.

Hope this helps.

**Comment by BsNoSi** [comment]
I read twice again the description of the plugin. I apologize for don't seeing any hints to this.  There is a `FeedFilterLayout: blog` which I was/am using. It's result was working before transfer to a new place (and updating to 0.815 – I forgot to mention that) as expected. After moving/updating the ancient files where listed first because all without `modified` where sorted to the new date of file copy.

Maybe something has changed in the extension becaus without changing the settings the presentation changed. BUT: Even iv not it was not recognized by me because the previous file date was old enough to keep these entries "out of sight". Therefore I would say this behaviour in not realy new and normally will not be relevant.

Nevertheless it might be an improvement, if `modified` is used, a two stepp fallback to `published` and then to `filedate` could make  very old content files *forward compatible`.

**Comment by markseu** [comment]
Thanks for your suggestion. I am in favour of keeping modification date and publication date separate. They represent two different concepts. In some contexts you want to show pages in the order they are published (i.e. blog) and sometimes in the order they are modified (i.e. wiki). In any case, the file modification date is used by various extensions not just the feed extension.

The situation you describe is perhaps more of a website migration problem? I am not familiar with Windows software... most FTP software offers a "Preserve timestamp transfer option" to solve this kind of problem.

**Comment by BsNoSi** [comment]
Separation of `modification`and `published` is a very useful and necessary thing – I think the same. 

My idea ist born from the concrete challenge of having very old pages with `published` only and the described effect. Lifting a second site to 0.815 doesn't have this – maybe, because it is not that old and `modified` was used from the beginning.

To be honest I can not say why/where the files date has changed. I can not remember this in the past and with "the next one" all looks fine even of the same processing. Maybe, my idea is academic…

**Comment by datenstromse** [comment]
Thanks for your feedback. Feel free to close your own issues once they are resolved and you are happy with the answers. The support on GitHub consists of volunteers and help is much appreciated. If you want to get involved, [have a look at open issues and work together with us](https://datenstrom.se/yellow/help/contributing-guidelines).
