### ISSUE TITLE
wiki tags do not show a list

### ISSUE THREAD

**Issue by BsNoSi** [datenstrom/yellow#551]
After updating a site to current release (V0.812 → 0.820 /  wiki.pzp 0.85 → 0.811) the `[wikitags]` show a list of tags but clicking one of them does not generate a list:
![image](https://user-images.githubusercontent.com/2784683/95305887-e248e500-0886-11eb-8a19-24609936a195.png)

Before update (1) crated a list for wikitags, afterwards the page (2) is empty.

Any hints?

**Comment by markseu** [comment]
Have a look at #488 and [troubleshooting](https://datenstrom.se/yellow/help/troubleshooting#system-diagnostics).

**Comment by BsNoSi** [comment]
I forgot to mention, that I remember #488 – therefore I am asking.

Perhaps you may have a look on this:

![image](https://user-images.githubusercontent.com/2784683/95337351-0b329f80-08b2-11eb-9b1f-9ce62babbe36.png)
[wikipages-does-not-exist.zip](https://github.com/datenstrom/yellow/files/5340980/wikipages-does-not-exist.zip)

I attached the files as final result that where used for these four steps.

I have to admit, that even debug level 3 does not give (to me) any helpful information:

![image](https://user-images.githubusercontent.com/2784683/95338820-9fe9cd00-08b3-11eb-8c37-46bf9b024fd0.png)

**Comment by markseu** [comment]
Thanks for the detailed information, always a good idea to investigate problems with a fresh installation.

As far as I can see, the [wiki extension](https://github.com/datenstrom/yellow-extensions/tree/master/source/wiki) works as documented.

Wiki shortcuts require an argument, for example `[wikitags /wiki/]`.

**Comment by BsNoSi** [comment]
! My fault – Sorry. 

I am trying to update sites last updated beginning of 2020 and running into several problems. Maybe I should do something else for a while because don't see the forest for the trees...

**Comment by BsNoSi** [comment]
(Does not solve my originally problem but this is solved)
