### ISSUE TITLE
Description up to date?

### ISSUE THREAD

**Issue by BsNoSi** [datenstrom/yellow#552]
The [description of making a wiki](https://datenstrom.se/yellow/help/how-to-make-a-small-wiki) says:

> To show a header create the file content/shared/header.md. You can also create a header.md in your wiki folder and it will only be shown on pages in the same folder. 

A fresh installed Yellow shows a `header.md` placed in `shared` but not if it is placed in content/1-home.

API description says:

> page->getExtra($name) → Return page extra data

which is used in `header.html`. Wie muss dies modifiziert werden, um `header.md` innerhalb eines verwendeten Inhaltsordners zu erhalten, falls verfügbar?

Or was this possibility omitted with the latest versions?

**Comment by markseu** [comment]
I updated the documentation. 

The API was simplified in a recent release, shared pages should be stored inside `content/shared/` folder. The following code `$this->yellow->page->getPage("header")->getContent()`  can be used to show a header. This is how the default layout files work, see https://github.com/datenstrom/yellow/tree/master/system/layouts.

**Comment by BsNoSi** [comment]
The jumping between languages shows me: I was visibly overworked yesterday - but at least I was on the right track when it came to adapting some of the older systems.

Collecting the common data in one place makes structural sense - then they may have to have different names (sidebarA, sidebarB, ...). This creates overview and order. At least in my case it will even simplify things significantly. Why - no idea - but in the inventory data I had the same sidebar in subfolders, which had to be maintained in each case. Probably "historical remains".
