### ISSUE TITLE
Development History

### ISSUE THREAD

**Issue by BsNoSi** [datenstrom/yellow#554]
I am "Yellow part time customizer" using spare project time with variable time space between other projects I have to do. Therefore I regularly miss updates "in between" which leads regularly to very gruelling sessions upgrading existing sites.

For me it would be very helpful to have a "changes diary" of the versions: New, changed, deprecated, removed. Simply to have an idea why things that worked perfectly are nonfunctional or "show stopper" after an update.

It is very time consuming to install previous an new versions side by side comparing them file by file and go into deep to understand what may be the reason for failure. 

The requirements for such a document would be low. Just a few key points, what has changed where, perhaps with a short "why", would help people like me, who are not part of the constant development, to find out if time can be invested in Yellow again. Above all, there would be more time for new things instead of chasing after old ones.

A "latest first" list of changes would allow the quick identification of possible problems, because it would make the gap between "then" and "now" very quickly tangible.

**Comment by markseu** [comment]
There are [release notes](https://github.com/datenstrom/yellow/releases) and for everything else you can [ask questions](https://datenstrom.se/yellow/help/).

We generally aim to make the update as smooth as possible. If you would like to have a better website update process, you should join the team that tests releases and gives timely feedback. If you would like to have a better developer documentation, you should start a team that collects and creates detailed documentation for developers. So I am passing the ball back to you. There are hundreds of CMS to chose from, maybe there one that has what you're looking for? Maybe there's something you can do to make Datenstrom Yellow better?

**Comment by BsNoSi** [comment]
I know from other projects, especially commercial products for which I have been very successful in marketing and sales for many years, that there is a defined place for a changelog with changes to the central system. Based on this, further documents are created and maintained. Among other things, there is a note that documents need to be revised or created - which others can then do in a targeted manner.

As far as I have time for this, I am happy to contribute to it. However, as already mentioned, I have no possibility to do this continuously. Therefore, with the current form of information flow, it is difficult for me to get to the point where I can contribute something new or additional.

My time currently available for Yellow is almost used up and the actual goal to be up to date with several websites and plugins developed for them, including updates of my [repositories](https://github.com/BsNoSi?tab=repositories), is in undefined distance. 

At the moment I see the danger that I will have to break this off and that the distance until the next "session" will be even greater. Then possibly with even greater frictional losses, which would ultimately leave me behind. Which would make any form of support on my part impossible.

In my opinion the "pick list with keyword informations" is missing, offering topics to be worked through *by others* in a targeted manner, which in the end benefits everyone. If most of the time has to be spent by people who want to work, trying to find out where something needs to be done or could be done, it ultimately slows everyone down.

The most successful "CMS" for change logs I know is a "changes.txt" as part of the package. In case of YELLOW, I'd prefer a "changes.md" that is part of the install sample data.

**Comment by markseu** [comment]
Thanks for your feedback. I personally don't plan to do more detailed release notes.

**Comment by BsNoSi** [comment]
Maybe there is a misunderstanding. 

I do not expect or want "more details". It's simply a question of "where to find all". If  a "changes.md" would be part of the download package there is – in my opinion – no need for further places. The advantage would be having the history automatically for those missing changes between their installation to the current.

Possibly this may less to do than currently because there is no need to change existing documents but only adding the lates information at the beginning of an existing file leaving the previous entries below.

**Comment by markseu** [comment]
Go ahead and let us know what you come up with.

**Comment by BsNoSi** [comment]
As I said: A "changes.md" (or "history.md") as part of the download package collecting in reverse chronological order changes like a log file. Instead of waiting for being asked pointing out changes directly together with changes in package. This saves time on both sides.
