### ISSUE TITLE
Telegram Icon Missing in Font Awesome Extension

### ISSUE THREAD

**Issue by thumos333** [datenstrom/yellow#557]
Hi,

[An icon for the popular messenger Telegram](https://fontawesome.com/icons/telegram-plane?style=brands) seems to be absent from the [corresponding extension](https://github.com/datenstrom/yellow-extensions/blob/master/source/fontawesome/fontawesome.css) for Yellow. Could you please add it?

**Comment by markseu** [comment]
I updated the extension. Now there's `fa-telegram` and `fa-paper-plane`, please try again.
