### ISSUE TITLE
Format Extension: Update suggestion to correspond to new API

### ISSUE THREAD

**Issue by JetGum** [datenstrom/yellow#560]
In the extremely useful Format-Extension, "getTextArgs" needs to be changed to "getTextArguments" (format.php, line 20). 
See [#559](https://github.com/datenstrom/yellow/issues/559).

**Comment by markseu** [comment]
Sounds like a 3rd party extension, which is not listed in Datenstrom Yellow extensions. Backwards compatibility with the old API has been removed. Some extensions may not be compatible with the latest release and may no longer work. If your website is affected, please contact the developer and let him/her know.

**Comment by markseu** [comment]
You can find the extension here: https://github.com/BsNoSi/yellow-extension-format

Thanks for your feedback, let us know if you find more problems. 😀
