### ISSUE TITLE
Fresh install v0.8.16 (blog)  : pagination does not work

### ISSUE THREAD

**Issue by ThryLry** [datenstrom/yellow#561]
Hello,
Fresh installation v0.8.16 (blog) without modification, seven test posts: pagination does not work.

Fresh installation v0.8.15 (blog), without modification, seven test posts: pagination works.

Update v0.8.15 to v0.8.16 : pagination works.

Sorry, I'm French, not computer scientist and I don't speak English (DeepL assists me) but Datenstrom Yellow is exactly what I need, in form and spirit (thanks).

**Comment by markseu** [comment]
Hello, I updated the pagination to the new API. Now a fresh installation should work, please try it out.

**Comment by ThryLry** [comment]
> Now a fresh installation should work, please try it out.

Exactly, the pagination now works perfectly after a recent installation. Thank you very much.
