### ISSUE TITLE
Lost my 'Blog' page

### ISSUE THREAD

**Issue by Ordresser** [datenstrom/yellow#562]
Accidentally lost my blog page by thinking it was a new blog entry and saving the changes. 

What do I put on the blog page and edit it to get my blogroll back? 

Thanks

**Comment by schulle4u** [comment]
See #518

**Comment by datenstromse** [comment]
Thanks for your feedback. Feel free to close your own issues once they are resolved. The support on GitHub consists of volunteers and help is much appreciated. If you want to get involved, [have a look at our contributing guidelines and work together with us](https://datenstrom.se/yellow/help/contributing-guidelines).
