### ISSUE TITLE
404 loading resource generated by bundle extension

### ISSUE THREAD

**Issue by spotthehall** [datenstrom/yellow#563]
With Datenstrom Yellow 0.8.16, PHP 7.4.9, Apache 2.4.46, I am getting a 404 error when trying to load the extension bundle: /media/extensions/bundle-****.min.css

Two site effected, so far, They work Ok on a fresh upload, but in use fail.

**Comment by spotthehall** [comment]
A way I have got around just replacing the extensions folder every time if fails, is (I think) to build the site locally, upload everything, change permissions on the extensions folder to 777 let it write the bundle, then change the permissions back to 775.

**Comment by BsNoSi** [comment]
You method may help but it seems to me a little bit too much effort for something that can be possibly solved quite easier:

- Have you set first line of `core.php` to `<?php define("DEBUG", 1);` and checked the error messages?
- Have you checked what happens if you move `bundl.php` out of extensions folder (= is ignored)?
- Have you checked wether a css file has wrong coding?

**Comment by spotthehall** [comment]
Thanks, 

I did check the css files as I'd seen somewhere that minifying caused issues.

DEBUG showed:
YellowCore::sendPage Content-Type: text/html; charset=utf-8
YellowCore::sendPage Content-Modified: Tue, 17 Nov 2020 16:53:44 GMT
YellowCore::sendPage Last-Modified: Fri, 20 Nov 2020 14:28:16 GMT
YellowCore::sendPage language:en layout:front theme:stockholm parser:markdown
YellowCore::processRequest file:content/home/page.md
YellowCore::request status:200 time:67 ms

So, I've removed bundl.php for now and it seems OK.

**Comment by markseu** [comment]
Hello, I updated the way how bundles are generated and cleaned up. I suspect that the cleaning up part was the problem on your web server, I think it deleted too much. Now the [bundle extension](https://github.com/datenstrom/yellow-extensions/tree/master/source/bundle) should work without 404 error.

Can you update your website and try it out?

**Comment by spotthehall** [comment]
Thanks markseu, I installed the update yesterday on both sites and everything seems to be working just fine now.
Cheers.

**Comment by markseu** [comment]
Thanks for testing and giving feedback. 😀
