### ISSUE TITLE
How to get contact extension to work

### ISSUE THREAD

**Issue by JetGum** [datenstrom/yellow#564]
Hi all,

on my "domain.de", I would love to get the contact plugin to work but so far, no email was sent via contact form.

These are the yellow-system.ini - settings:
Author: John Doe
Email: john@domain.de
ContactLocation: /contact/

On the Contact page header, Author and Email is repeated. Contact form shows up, but no email is sent.

What am I missing? Or how can I track the error?

Cheers & thanks!

Carsten

**Comment by IngoBelka** [comment]
https://www.guru99.com/php-mail.html

**Comment by JetGum** [comment]
Ingo, 
how does the link help me track eventual misconfigurations or errors?

Cheers,

Carsten

**Comment by IngoBelka** [comment]
Hi Carsten,

you have to set some values

    SMTP = smtp.example.com
    smtp_port = 25
    auth_username = example_username@example.com
    auth_password = example_password

in the php.ini to get it work, because contact extension depends of PHP function mail(), which uses this variables to work.

**Comment by JetGum** [comment]
Hi, 

thx for the explanation. I contacted my hoster who confirmed that the mail() is activated and working - I have tested mail() function with a small script and a mail was sent.

<?php
// Send email
mail('info@domain.de','hello','test mail function');
?>

Will try again with the contact extension and report back.

Cheers,

Carsten
