### ISSUE TITLE
Upload your extension and add the topic datenstrom-yellow

### ISSUE THREAD

**Issue by datenstromse** [datenstrom/yellow#566]
Hi developers and designers.

Have you made an extension for Datenstrom Yellow? Upload your extension to GitHub. Add the topic `datenstrom-yellow` to your repository. You can also add additional topics. This will help people to discover your extension. https://github.com/topics/datenstrom-yellow

Want to publish your extension in the official repository? This step is optional and will make it easier to install your extension. Published extensions are also included in the update process. [Learn more about publishing extensions](https://github.com/datenstrom/yellow-extensions/tree/master/source/publish).

Stay safe and kind regards from Sweden.

**Comment by markseu** [comment]
Ping @GiovanniSalmeri, @wunderfeyd, @hysonlee, @schulle4u. 😄
