### ISSUE TITLE
VideoJS/HTML5 video support

### ISSUE THREAD

**Issue by varakh** [datenstrom/yellow#57]
See plugin. :-)

https://github.com/varakh/yellowcms-extensions-videojs

**Comment by markseu** [comment]
Great to see so more and more plugins from @datenstrom/developers. :smile:

I want to suggest to rename the extisting [Yellow plugins](https://github.com/datenstrom/yellow-extensions/tree/master/plugins/zzz-more). It would be nice if we developers use the same naming pattern. How about naming repositories `yellow-something` or `yellow-type-something`, if that is okay with you?

**Comment by BsNoSi** [comment]
Good idea. I changed `imgscale` repository to `yellow-imgpop` (see https://github.com/BsNoSi/yellow-imgpop) i.e. following `yello-something`.

**Comment by markseu** [comment]
Thank you for repository update. :+1:
