### ISSUE TITLE
How to make external links with Markdown?

### ISSUE THREAD

**Issue by i-do** [datenstrom/yellow#570]
Suddenly find that markdown {target="_blank"} doesn't work any more.
I often use this add on my site.

`
[Text Title](url){target="_blank"}
`

Does somebody knows why?

**Add:** I've find [Pasedown Extra extention](https://github.com/erusev/parsedown-extra). 
Will try to fix it in the evening.

**Comment by markseu** [comment]
This works in the official server: 

`[Open link in a new tab](https://datenstrom.se){target=_blank}`
`<a href="https://datenstrom.se" target="_blank">Open link in new tab</a>.`

For more information see:
https://github.com/datenstrom/yellow-extensions/tree/master/source/markdown
https://github.com/datenstrom/yellow-extensions/tree/master/source/parsedown
