### ISSUE TITLE
How to integrate widget column?

### ISSUE THREAD

**Issue by martinbetz** [datenstrom/yellow#62]
I would love to have an editable widget column on the right, but I don't know how to set it up with Yellow.

If it wasn't editable, I would just create another `snippet`, but how can I go about with a widget that is a page itself?

Should I set it up as on own page and write a snippet and integrate it with a snippet? And change the content by accessing the page itself?

**Comment by markseu** [comment]
You're right, there should be an example how to make a sidebar. I thought about it last week and came to the same conclusion, put content into extra page and then include it via snippet. For example something like GitHub [Wiki](https://github.com/datenstrom/yellow/wiki) does, if there's a sidebar.txt it's integrated into the page. Would that work?

**Comment by martinbetz** [comment]
Yes, that wiki type `sidebar.txt` would be enough.

**Comment by markseu** [comment]
It's added to latest version. You can add sidebar to any page, the sidebar content is also editable. Set `Sidebar: sidebar` at the top of a page. This will check if there is a `sitebar.txt` in the current folder. Here's an example content file:

```
---
Title: Sidebar
Status: hidden
---
* [Yellow](http://datenstrom.se/yellow)
* [Twitter](https://twitter.com/datenstromse)
```
Hope it works for you.

**Comment by martinbetz** [comment]
Super! Thanks
