### ISSUE TITLE
Markdown demo in YellowCMS

### ISSUE THREAD

**Issue by nibreh** [datenstrom/yellow#67]
How about demo markdown syntax include in YellowCMS ?

If I suggest this, it's for beginners who have never learned about markdown (I was one of them). Once yellow is uploaded, you can found a tiny example page for introduce markdown. Very helpful for starting editing page just right after uploading Yellow.

It can be the page *about* by default, or a PDF in media folder, or a link in the menu ...

**Comment by markseu** [comment]
Thanks Nibreh, that's a good idea. What would be a good place for an Markdown example? What do you guys like better, adding an example page to the installation or adding it to the [documentation](https://github.com/datenstrom/yellow)?

**Comment by Fourwinged** [comment]
I would add a page to the documentation, and a link pointing to it in the default page.
This way, the Markdown demo can always be accessed and bookmarked for reference, but it allows new users to find it easily.

**Comment by BsNoSi** [comment]
I have created a markdown description in German. I can translate it into English, to be included in the download package. I will send it to Mark, as soon as it is available.

**Comment by Truckle** [comment]
Does Yellow support Github flavored markdown? And how about that cheat sheet? I'll take it in German if you don't have it in English.

**Comment by BsNoSi** [comment]
Change file extender from "png" to "zip" after download (right mouse click - download) and unpack "markdown-quickguide.txt". Rename it suitable for you and use it in yellow as required. 

**Note**: It is a `quickguide` without detailed explanations. 


![markdown-quickguide](https://cloud.githubusercontent.com/assets/2784683/10855138/47436816-7f40-11e5-9079-1a5b7a5f8efd.png)

**Comment by markseu** [comment]
Here are some links about Markdown syntax:

* https://warpedvisions.org/projects/markdown-cheat-sheet/
* https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet
* https://raymii.org/s/tutorials/Markdown_Introduction_Tutorial_Overview.html
* http://blog.nosi.de/markdown/
* http://markdown.de

**Comment by markseu** [comment]
Writing documentation just got easier. There's a new Yellow help. Search-friendly and in English, German, French. Could be good place to add a Markdown example. http://developers.datenstrom.se/help/

**Comment by markseu** [comment]
I added a Markdown cheat sheet, feel free to contribute and add more information. :smile: 

http://developers.datenstrom.se/help/markdown-cheat-sheet

**Comment by markseu** [comment]
I added a link to the Markdown cheat sheet. When editing a page in a web browser, there's a Markdown link in the right corner. This brings you to the Markdown syntax and shows some examples.

What do you think @nibreh, does this work?

**Comment by nibreh** [comment]
Hi. 

Yes it's working. This is very useful for beginners, who can now quickly learn to use yellow. And the new better installation makes it even easier to use.

Thanks !
