### ISSUE TITLE
Looking for a French translator

### ISSUE THREAD

**Issue by markseu** [datenstrom/yellow#68]
Hi, I am looking for help. Does someone speak French and want to translate the Yellow website? It's two text files and shouldn't take too long. Would be great to get some help, thanks!

**Comment by nibreh** [comment]
I can do that ! The Home page and what else ?

**Comment by markseu** [comment]
Cool @nibreh, I'lll send you an email. It's just the home page.

**Comment by markseu** [comment]
Thank you @nibreh for the French translation! :+1:
