### ISSUE TITLE
Missing "related posts" Plugin or "random posts"

### ISSUE THREAD

**Issue by idefixxx** [datenstrom/yellow#71]
Sorry, for my bad english.
I miss a plugin for "Related Posts" for better internal linking.
It is not easy to program, i know.
Therefore, I want something simple. 

I like to show 5 posts by chance (random)
I'm not so good in PHP and I think it's easy when you know how.

Who can program as a snippet?

Regards

**Comment by markseu** [comment]
Thanks for your suggestion!

I updated the [blog plugin](https://github.com/datenstrom/yellow-extensions/tree/master/plugins/blog). You can now create a list of related pages. It works without special meta data, related pages are based on title, tag and author. Add `[blogrelated /blog/ 5]` to your content files or call it from `system/themes/snippets/content-blog.php` like this:

```
<div class="content main">
<div class="entry">
<div class="entry-header"><h1><?php echo $yellow->page->getHtml("titleContent") ?></h1></div>
<div class="entry-meta"><?php echo htmlspecialchars($yellow->page->getDate("published")) ?> <?php echo $yellow->text->getHtml("blogBy") ?> <?php $authorCounter = 0; foreach(preg_split("/,\s*/", $yellow->page->get("author")) as $author) { if(++$authorCounter>1) echo ", "; echo "<a href=\"".$yellow->page->getParentTop()->getLocation().$yellow->toolbox->normaliseArgs("author:$author")."\">".htmlspecialchars($author)."</a>"; } ?></div>
<div class="entry-content"><?php echo $yellow->page->getContent() ?></div>
<div class="entry-footer">
<?php if($yellow->page->isExisting("tag")): ?>
<p><?php echo $yellow->text->getHtml("blogTag") ?> <?php $tagCounter = 0; foreach(preg_split("/,\s*/", $yellow->page->get("tag")) as $tag) { if(++$tagCounter>1) echo ", "; echo "<a href=\"".$yellow->page->getParentTop()->getLocation().$yellow->toolbox->normaliseArgs("tag:$tag")."\">".htmlspecialchars($tag)."</a>"; } ?></p>
<?php endif ?>
</div>
</div>
<?php echo $yellow->page->getExtra("blogrelated") ?>
<?php echo $yellow->page->getExtra("comments") ?>
</div>
```

At the moment it does not randomize pages or create image preview. Hope it's a starting point.
