### ISSUE TITLE
Link inside same domain

### ISSUE THREAD

**Issue by FlTr** [datenstrom/yellow#72]
Is there a comfortable way to link inside the same domain?
Scenario:
Yellow is located under ````www.example.com/cms````. Some other stuff is located under ````www.example.com/stuff`````. Now i want to insert a link from a CMS file to /stuff/anything.html. 

````
[Anything](/stuff/anything.html)
````
This doesn't work because serverbase is added and href results in ````/cms/stuff/anything.html````. A possible solution is to use the absolute link:
````
[Anything](www.example.com/stuff/anything.html)
````

But this is neither comfortable nor practible when using 2 different servers (development/production <-> "localhost" / "example.com" ).

**Comment by nibreh** [comment]
hello

To create a link from `domain.com/yellow` to `domain.com/stuff`, you can use this trick

`[link](../stuff)`

(only working on your home page at `domain.com/yellow`)

Don't know if this can be usefull

**Comment by FlTr** [comment]
Hm thank you. This works. But i'm not very happy with this solution.

**Comment by FlTr** [comment]
P.S: The resulting href then looks somehow like this:
```html
<a href="/cms/../../stuff/anything.html" >Anything</a>
```

**Comment by markseu** [comment]
Hi, how about putting Yellow under `www.example.com` and add extra folders?

Here's an example:

```
-webserver
  -content
  -media
  -system
  -stuff       <- here is your extra folder
```

**Comment by FlTr** [comment]
I think it will be difficult if there is something like this:
```
www
 - content
   - 1-stuff
 - stuff

**Comment by markseu** [comment]
Out of curiosity, what do you have in `/stuff/anything.html`?

**Comment by markseu** [comment]
You can also create links with HTML code `<a href="/stuff/anything.html">Anything</a>`.

**Comment by FlTr** [comment]
Ok this is a suitable solution. However not "perfect". 
A kind of flag in the normal link syntax?

**Comment by markseu** [comment]
I'm afraid to say that I don't know of another alternative.

Have a look into the source code if you are a developer. The link generation works like this. Page content is parsed by [YellowMarkdown::onParseContentRaw](https://github.com/datenstrom/yellow/blob/master/system/plugins/markdown.php#L18), which calls  [YellowLookup::normaliseLocation](https://github.com/datenstrom/yellow/blob/master/system/core/core.php#L2033) for all links, it takes care of converting relative links. Here is probably a good place for improvements. 

Hope this helps. Let me know if you find something that works better for you.

**Comment by FlTr** [comment]
thanks for the hint. If i have some time left, i will look inside

**Comment by markseu** [comment]
What do you think about `[Anything](@server/stuff/anything.html)`?

You can try it out by updating file `system/plugins/markdown.php` in line 49:

	function transform($text)
	{
		$text = preg_replace("/@server/i", $this->page->serverScheme."://".$this->page->serverName, $text);
		$text = preg_replace("/@pageRead/i", $this->page->get("pageRead"), $text);
		$text = preg_replace("/@pageEdit/i", $this->page->get("pageEdit"), $text);
		$text = preg_replace("/@pageError/i", $this->page->get("pageError"), $text);
		$text = preg_replace("/@pageFile/i", $this->page->get("pageFile"), $text);
		return parent::transform($text);
	}

**Comment by FlTr** [comment]
Yes. It seems to be the right way when there are already other special indicators. What about something more abstract like ```@domain```?

**Comment by markseu** [comment]
I suggest one of these alternatives:

```
Special links: [Webserver](@webserver), [Read](@pageread), [Edit](@pageedit). 
Special links: [Website](@website), [Read](@pageread), [Edit](@pageedit). 
Special links: [Domain](@domain), [Read](@pageread), [Edit](@pageedit). 
```

You can decide what's best.

**Comment by FlTr** [comment]
I prefer the third one.

**Comment by markseu** [comment]
Great, let's do that. Please update the pull request and if it passes the tests I'll merge it.

**Comment by markseu** [comment]
Added to latest version.

**Comment by FlTr** [comment]
Another idea:

```php
function transform($text)
{
	$text = preg_replace("/@pageRead/i", $this->page->get("pageRead"), $text);
	$text = preg_replace("/@pageEdit/i", $this->page->get("pageEdit"), $text);
	$text = preg_replace("/@pageError/i", $this->page->get("pageError"), $text);
	$text = parent::transform($text);
	$text = preg_replace("/".$this->page->base.$this->page->location."@domain/i", "", $text);
	return $text;
}
```

**Comment by FlTr** [comment]
#83

**Comment by markseu** [comment]
I rolled back Markdown changes, let's try a plugin.

**Comment by markseu** [comment]
Sorry for leaving you hanging without example for [plugin events](https://github.com/datenstrom/yellow/wiki/Yellow-API#events).

Here's an example plugin file `system/plugins/smartlink.php`:

```
<?php
// Copyright (c) 2013-2015 Datenstrom, http://datenstrom.se
// This file may be used and distributed under the terms of the public license.

// Smartlink plugin
class YellowSmartlink
{
	const Version = "0.1.1";
	var $yellow;			//access to API
	
	// Handle initialisation
	function onLoad($yellow)
	{
		$this->yellow = $yellow;
	}
	
	// Handle page content parsing
	function onParseContentText($page, $text)
	{
		return preg_replace("#href=\"$page->base[^\"]+@domain#", "href=\"", $text);
	}
}

$yellow->plugins->register("smartlink", "YellowSmartlink", YellowSmartlink::Version);
?>
```

A Markdown link starting with `@domain` will create links without base. Hope this helps.

**Comment by FlTr** [comment]
I think, i understand your event system, but there was no time for open source things. Support is faster than requests, AWESOME. Wish this will be in other things equal.
Plugin looks good.

**Comment by markseu** [comment]
Good to hear. Feel free to close the issue when it works for you.

**Comment by FlTr** [comment]
It works as it is.
