### ISSUE TITLE
Toc plugin error

### ISSUE THREAD

**Issue by i-do** [datenstrom/yellow#76]
Just add the plugin and copy the sample text from documentation.

     Fatal error: Call to undefined method YellowPage::getPage() in /home/lzr3/lzr3.com/system/plugins/toc.php on line 24

[link to page] (http://www.lzr3.com/blog/test/)

**Comment by markseu** [comment]
Please update to latest Yellow. It needs the latest system files.

**Comment by i-do** [comment]
Yes, it works with latest core files. 
Thank you!
