### ISSUE TITLE
isActive() doesn't work properly

### ISSUE THREAD

**Issue by FlTr** [datenstrom/yellow#77]
Content structure:
```
content/
  - stuff/
    - page.txt
    - file.txt
    - file_v2.txt
```

If we go to */stuff/file* all is ok, but if we go to */stuff/file_v2*, file and file_v2 are marked as active.

**Comment by markseu** [comment]
Sorry about that. Should be fixed now.

**Comment by FlTr** [comment]
will test it soon, thanks

**Comment by FlTr** [comment]
It works, could be closed.
