### ISSUE TITLE
A way to insert the latest 3 Blogposts on my "Home"

### ISSUE THREAD

**Issue by MrMacStripe** [datenstrom/yellow#79]
Hi, is there a way to display the latest three blog posts on my One-Page-Layout home site? The /blog/ site has to be available, too. I think that should be easy to do, but I don´t see how to do it.

Thank you in advance!

**Comment by markseu** [comment]
Hi, you can add `[blogrecent /blog/ 3]` to your home page. Is that what you're looking for?

**Comment by MrMacStripe** [comment]
This adds a list to my page. I need something like a preview as you can create with wordpress for example: headline, image, first paragraph.

**Comment by markseu** [comment]
Yes that's possible, have a look at [Yellow customisation](https://github.com/datenstrom/yellow/wiki/Yellow-customisation).

Here's an example snippet file `system/themes/snippets/content-blogpreview.php`:
```
<?php list($name, $location, $pagesMax) = $yellow->getSnippetArgs() ?>
<?php if(empty($location)) $location = $yellow->config->get("blogLocation"); ?>
<?php if(empty($pagesMax)) $pagesMax = 3; ?>
<?php $blog = $yellow->pages->find($location); ?>
<?php $pages = $blog ? $blog->getChildren(!$blog->isVisible()) : $yellow->pages->clean(); ?>
<?php $pages->filter("template", "blog")->sort("published", false)->limit($pagesMax); ?>
<?php $yellow->page->setLastModified($pages->getModified()); ?>
<?php foreach($pages as $page): ?>
<div class="entry">
<div class="entry-header"><h1><a href="<?php echo $page->getLocation() ?>"><?php echo $page->getHtml("title") ?></a></h1></div>
<div class="entry-meta"><?php echo htmlspecialchars($page->getDate("published")) ?> <?php echo $yellow->text->getHtml("blogBy") ?> <?php $authorCounter = 0; foreach(preg_split("/,\s*/", $page->get("author")) as $author) { if(++$authorCounter>1) echo ", "; echo "<a href=\"".$yellow->page->getLocation().$yellow->toolbox->normaliseArgs("author:$author")."\">".htmlspecialchars($author)."</a>"; } ?></div>
<div class="entry-content"><?php echo $yellow->toolbox->createTextDescription($page->getContent(), 1024, false, "<!--more-->", " <a href=\"".$page->getLocation()."\">".$yellow->text->getHtml("blogMore")."</a>") ?></div>
</div>
<?php endforeach ?>
```

Here's an example template file `system/themes/templates/home.html`:
```
<?php $yellow->snippet("header") ?>
<?php $yellow->snippet("content-sidebar") ?>
<?php $yellow->snippet("content-blogpreview") ?>
<?php $yellow->snippet("footer") ?>
```

Hope this helps.

**Comment by MrMacStripe** [comment]
Thank you very much, that´s exactly what I was looking for. Great support!

**Comment by markseu** [comment]
Glad I could help. I just realised that blog customisation was easier a few versions ago, probably have to look into it again. Let us know how Yellow works for you. Feedback is always welcome. :smile:

**Comment by MrMacStripe** [comment]
So far, it works inmsanly fast and is super easy. Exactly what I was looking for to get rid of wordpress since that is way to big for most of my projects. Your system provides basically anything that´s needed.

**Comment by sashatravkina** [comment]
It doesn't work anymore. Nothing is displayed.

**Comment by markseu** [comment]
Updated for Datenstrom Yellow 0.7.8.
