### ISSUE TITLE
Advice needed — Portfolio automate based on blog and preview plugins

### ISSUE THREAD

**Issue by i-do** [datenstrom/yellow#81]
I trying to make an portfolio. On Home screen I want to show recent works, last 7 or 10 works from different folders.
 
Do not exactly understood how can I do it. Looks like I need some functions from blog plugin and some from preview plugin.

It will be great to make plugin witch can show pictures and text descriptions with the links below it. 
Like this:
![screen shot 2015-06-08 at 18 26 46](https://cloud.githubusercontent.com/assets/2960014/8035688/0c05eb16-0e0c-11e5-9851-f7ae77f597f0.png)

My folder structure organised like this:
![lzr-folders](https://cloud.githubusercontent.com/assets/2960014/8034201/f070be4c-0dfe-11e5-9a5c-7bda6493a7ee.png)

In each folder (Apps, Sites, Logo, Print) I want to make many txt files. One file — one project.

Am I right? Or, maybe, will be better to use tags? But I don't know how to show tag marked projects.
So I need your advice, Mark.

**Comment by markseu** [comment]
Yes that's possible, have a look at [Yellow customisation](https://github.com/datenstrom/yellow/wiki/Yellow-customisation).

Here's an example snippet file `system/themes/snippets/content-portfolio.php`:
```
<?php list($name, $location, $pagesMax) = $yellow->getSnippetArgs() ?>
<?php if(empty($location)) $location = $yellow->page->location ?>
<?php if(empty($style)) $style = "portfolio" ?>
<?php if(empty($size)) $size = "100%"  ?>
<?php if(empty($pagesMax)) $pagesMax = 10; ?>
<?php $content = $yellow->pages->find($location); ?>
<?php $pages = $content ? $content->getChildren(!$content->isVisible()) : $yellow->pages->clean(); ?>
<?php $pages->sort("modified", false)->limit($pagesMax); ?>
<?php $yellow->page->setLastModified($pages->getModified()); ?>
<div class="content main">
<h1><?php echo $yellow->page->getHtml("titleContent") ?></h1>
<?php echo $yellow->page->getContent() ?>
<ul class="<?php echo htmlspecialchars($style) ?>">
<?php foreach($pages as $page): ?>
<?php $description = $page->getHtml("description"); if(empty($description)) $description = $page->getHtml("title"); ?>
<?php if($yellow->plugins->isExisting("image")): ?>
<?php $fileName = $yellow->config->get("imageDir").basename($page->location).".jpg"; ?>
<?php list($src, $width, $height) = $yellow->plugins->get("image")->getImageInfo($fileName, $size, $size); ?>
<?php endif ?>
<li><a href="<?php echo $page->getLocation() ?>"><img src="<?php echo htmlspecialchars($src) ?>" width="<?php echo htmlspecialchars($width) ?>" height="<?php echo htmlspecialchars($height) ?>" alt="<?php echo $page->getHtml("title") ?>" title="<?php echo $page->getHtml("title") ?>"><br /><?php echo $description ?></a></li>
<?php endforeach ?>
</ul>
</div>
```

Here's an example template file `system/themes/templates/portfolio.html`:
```
<?php $yellow->snippet("header") ?>
<?php $yellow->snippet("content-portfolio") ?>
<?php $yellow->snippet("footer") ?>
```

Put all your pages into `/content/02-portfolio` folder, no need to create sub folders. For every page there should be an jpg-image of similar file name in your `media/images folder`. Hope this helps.

**Comment by i-do** [comment]
Thank you! It's not so easy to me but I'll do my best.

**Comment by markseu** [comment]
Glad I could help. Let us know if something can be made better or more documentation is needed. Feedback is always welcome. :smile:
