### ISSUE TITLE
Seeing Unnecessary Tags Rendered

### ISSUE THREAD

**Issue by nogginfuel** [datenstrom/yellow#84]
After installing Yellow and several extensions (specifically blog and search). The code rendered in the browser was showing extra code tags in view. 
OS: Windows 8
Browser:Chrome (latest)

The rendered codes tags look like this: [blogTag]  and are displayed next to the actual element.
In the "Search" bar the extra tag displays inside the search field as: [Search button].

I'm not sure what is going on with those extra tags. I removed the corresponding information from the file where it was in the format >gethtml ("blogTag") and things seem to still work fine?

**Comment by markseu** [comment]
Thanks for your feedback. It sounds like the language file is missing something. 

Please download [language-en.ini](https://github.com/datenstrom/yellow-extensions/blob/master/languages/english/language-en.ini?raw=true) and copy it to your `system/config` folder. Does that work for you?

**Comment by nogginfuel** [comment]
Great suggestion. I must have had an old version? Updating the _language-en.ini_ file worked! I'm looking forward testing more this weekend.
