### ISSUE TITLE
How to render external RSS content on the home page

### ISSUE THREAD

**Issue by schulle4u** [datenstrom/yellow#92]
Currently I consider Yellow CMS as an entry point for different blogs and projects I'm maintaining, as well as for some further information about myself. One thing I'd like to have is a news section on the home page which displays the RSS content of my projects (a WordPress blog, a podcast and so on). Displaying RSS feeds as HTML pages is not the problem, I have several scripts that will do the job. However, I'm not sure how to integrate this script into Yellow CMS without breaking the CMS or using ugly IFrames. I tried putting it into the sidebar snippet, but this looked very bad due to the fact that  the sidebar is to narrow for such content. Putting the feeds into the main content snippet works better, but this automatically displays the feeds on all sub pages. Is there a way to display my feeds only on the home page?

**Comment by markseu** [comment]
Is the script you want to integrate programmed in PHP?

**Comment by schulle4u** [comment]
Yes, it's a PHP script.

**Comment by markseu** [comment]
Okay then it should be possible, have a look at [Yellow customisation](https://github.com/datenstrom/yellow/wiki/Yellow-customisation).

Here's an example snippet file `system/themes/snippets/content-home.php`:
```
<div class="content main">
<h1><?php echo $yellow->page->getHtml("titleContent") ?></h1>
<?php echo $yellow->page->getContent() ?>
<?php /* Add more PHP code here */ ?>
</div>
```

Here's an example template file `system/themes/templates/home.html`:
```
<?php $yellow->snippet("header") ?>
<?php $yellow->snippet("content-sidebar") ?>
<?php $yellow->snippet("content-home") ?>
<?php $yellow->snippet("footer") ?>
```
This allows to put PHP code into Yellow and generate any HTML code you want. You could also write a plugin, but it's less work to integrate exiting code into templates. Yellow checks if there's a template with the name of the current folder.  If your home page is in folder `1-home` the this example should work automatically.

Hope this helps, happy coding. :smile:

**Comment by schulle4u** [comment]
Many thanks, exactly what I was looking for. I've read the documentation before but wasn't able to adapt the description of templates and snippets to my needs. Works like a charm now. 

Steffen
