### ISSUE TITLE
need costum navigation for theme/template

### ISSUE THREAD

**Issue by meentix** [datenstrom/yellow#93]
Hello,

I have bought a css/html template from themeforest and tried to adapt it to yellow. But I don't know how to modify the code for the navigation. I think there should only be some little modifactions in the navigation-tree.php but I'm not a coder. I have attached an example for the html code the navigation-tree.php must output so that it works with the design. It's important that in a submenu the first child element is also the parent element as you can see in the html code. Also important are the classes "has-sub-menu" and "sub-menu".

Is there someone who can do this maybe little necessary coding for me please?

Thanks and Regards,
Christian

![navigation](https://cloud.githubusercontent.com/assets/13523010/8910570/ddc377d0-3487-11e5-8291-0357653dd01d.jpg)

**Comment by meentix** [comment]
Nobody? :-(

**Comment by nibreh** [comment]
There is sub-child navigation in your example. 

From what I know, navigation-tree only work with one parent (folders in /content) and child (pages in this folder). For example: __/content/01-folder/name-page.txt__

Navigation-tree is not working with sub-folder like this: __/content/01-folder/sub-folder/name-page.txt__

Even if `http://domain.com/folder/sub-folder/name-page` is working

Please give a link to the theme you want

```
<div class="navigation-tree">
<ul>
<li><a class="active" href="/">home</a></li>
<li><a href="/01-folder/">folder01</a>
     <ul>
       <li><a href="/01-folder/page1">page1</a></li>
       <li><a href="/01-folder/page2">page2</a></li>
     </ul>
</li>
<li><a href="/02-folder/">folder02</a></li>
<li><a href="/03-folder/">folder03</a></li>
</ul>
</div>
```

In order that the theme works, you can just change _class name_ in _div tag_, and must be the same name in CSS, like this
```
<div class="navigation-tree">
CSS must be: . navigation-tree {some style}
```

**Comment by meentix** [comment]
Yes, I know that navigation-tree not work thats because I need from someone a new modified code for the navigation-tree.php so that it generate the html output I posted above. Because I also need the class names and the first child element has to be the parent element.

**Comment by nibreh** [comment]
Yeah, I know you know ;) 

Wait and see from coders. I'm not really good with [yellow API](https://github.com/datenstrom/yellow/wiki/Yellow-API)

**Comment by meentix** [comment]
:-) hopefully I get a response in the next few days. :-/

**Comment by meentix** [comment]
Still nobody who can do this little job for me?!? :-( Can not be so difficult, I think only a few lines of code modifications in the navigation-tree.php are necessary and could be done in a few minutes by a php / yellow experienced user. But for a coding noob like me its unfortunately impossible :-(

**Comment by meentix** [comment]
Would also pay $ for this job... :-/
