### ISSUE TITLE
using image plugin [image] in a div-Tag

### ISSUE THREAD

**Issue by meentix** [datenstrom/yellow#95]
Hello,

it seems that I can not use the [image]-Tag within a div. For example:

<div>[image picture.jpg Picture left]</div>

That will not execute :-(

Can someone confirm and fix it?

**Comment by nibreh** [comment]
You mean you use this when editing your page online ? 

`<div class="style">[image picture.jpg Picture left]</div>`

**Comment by meentix** [comment]
yes and the image is not shown up, only the code.

**Comment by nibreh** [comment]
OK

Insert markdown in a html tag is not working, this is normal, but you can use this trick:

<div class="name" markdown="1">[image picture.jpg Picture left]</div>

tell me

**Comment by meentix** [comment]
Perfect, that works :-) Thank you.
