### ISSUE TITLE
Blog customisation

### ISSUE THREAD

**Issue by markseu** [datenstrom/yellow#97]
It would be good if blog postings could be visually styled, if the blog could have something like categories that look different. One solution would be to use tags. They are already used in the blog and this informations could be exported to the page.

**Comment by nogginfuel** [comment]
I totally agree. The bonus of this approach is that it is reusing existing functionality to enhance the blog product further. Mark, I have been testing what you sent and so far it is going well. I did modify my setup a bit from the standard (but minimally).

**Comment by markseu** [comment]
Good to hear it works and thanks for the feedback. Here is an CSS example for the blog start page:

    .blogpages .content .red { background-color:#fee; }
    .blogpages .content .yellow { background-color:#ffe; }
    .blogpages .content .green { background-color:#eef; }

I updated the repository, it should be working now.
